<?php
$title = $this->translate('Contas Corrente');
$this->headTitle($title);
?>

<div class="panel panel-default">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-6">
                <h1 class="panel-title"><i class="glyphicon glyphicon-random"></i> <?php echo $this->escapeHtml($title); ?></h1>
            </div>
            <div class="col-md-6">
                <div class="btn-group btn-group-sm pull-right">
                    <a class="btn btn-default" href="<?php echo $this->url('dtladmin/dtlcurrentaccount/add'); ?>"> <i class="glyphicon glyphicon-plus-sign"></i> <?php echo $this->translate('Novo'); ?></a>
                </div>
            </div> 
        </div>
    </div>
    <table class="table table-condensed table-hover">
        <tr>
            <th class=""><?php echo $this->translate('NOME DA CONTA'); ?></th>
            <th class=""><?php echo $this->translate('BANCO'); ?></th>
            <th class=""><?php echo $this->translate('AGÊNCIA'); ?></th>
            <th colspan="2"><?php echo $this->translate('CONTA'); ?></th>
        </tr>
        <?php if (0 == count($this->currentAccount)): ?>
            <tr>
                <td colspan="10" class="alert alert-info text-center"><?php echo $this->translate('Não nenhum registro no banco de dados.') ?></td>
            </tr>
        <?php else: ?>
            <?php foreach ($this->currentAccount as $currentAccount) : ?>
                <tr>
                    <td><?php echo $this->escapeHtml($currentAccount->getName()); ?></td>
                    <td><?php echo $this->escapeHtml($currentAccount->getBank()->getName()); ?></td>
                    <td><?php echo $this->escapeHtml($currentAccount->getAgency()); ?></td>
                    <td><?php echo $this->escapeHtml($currentAccount->getAccount()); ?></td>
                    <td>
                        <div class="btn-group btn-group-xs pull-right">
                            <a class="btn btn-default" href="<?php echo $this->url('dtladmin/dtlcurrentaccount/edit', array('id' => $currentAccount->getId()))
                ?>"><i class="glyphicon glyphicon-edit"></i></a>
                            <a class="btn btn-default" href="<?php echo $this->url('dtladmin/dtlcurrentaccount/delete', array('id' => $currentAccount->getId()))
                ?>"><i class="glyphicon glyphicon-remove"></i></a>
                        </div>
                    </td>
                </tr>
            <?php endforeach; ?>
        <?php endif; ?>
    </table>
    <div class="panel-footer">
        <?php
        $paginationInfo = $this->placeholder('pagination');
        if (!isset($paginationInfo->route)) {
            $paginationInfo->route = 'dtladmin/dtlcurrentaccount';
            $paginationInfo->params = array();
        }
        ?>
        <?php echo $this->paginationControl($this->currentAccount, 'Sliding', 'layout/pagination'); ?>
    </div>
</div>
