<?php
$title = $this->translate('Apagar Tipo de Documento');
$this->headTitle($title);
$url = $this->url('dtladmin/dtldocumenttype/delete', array('id' => $this->id));
?>
<div class="modal-header">
    <h3 class="modal-title"><i class="fa fa-trash-o"></i> <?php echo $this->escapeHtml($title); ?></h3>
</div>
<div class="modal-body">
    <blockquote>
        <p><?php echo $this->translate('Você tem certeza de que deseja apagar ') ?>
            '<?php echo $this->escapeHtml($this->documentType->getName()); ?>'?
        </p>
    </blockquote>
</div>
<div class="modal-footer">
    <form action="<?php echo $url; ?>" method="post">
        <div>
            <input type="hidden" name="id" value="<?php echo $this->documentType->getId(); ?>" />
            <div class="form-group">
                <button type="submit" name="del" value="Sim" class="btn btn-danger"><i class="fa fa-eraser"></i>&nbsp;<?php echo $this->translate('Sim');?></button>
                <button class="btn btn-default" type="button" data-dismiss="modal"><i class="fa fa-times"></i>&nbsp;<?php echo $this->translate('Não');?></button>
            </div>
        </div>
    </form>
</div>

