<?php
$title = $this->translate('Tipos de Documentos');
$this->headTitle($title);
$this->placeholder('title')->set($title);
$this->placeholder('title-icon')->set('<i class="fa fa-file-o"></i>');
?>
<div class="page-body">
    <div class="widget-box">
        <div class="widget-header">
            <div class="widget-caption">
                <div class="widget-icon">
                    <i class="fa fa-bars"></i>
                </div>
                <?php echo $this->escapeHtml($title); ?>
            </div>
            <div class="widget-toolbar">
                <div class="btn-group">
                    <a data-toggle="modal" data-target="#documentTypeNew" class="btn btn-normal btn-success" href="<?php echo $this->url('dtladmin/dtldocumenttype/add'); ?>"> <i class="fa fa-plus-circle"></i> <?php echo $this->translate('Novo Item'); ?></a>
                </div>
            </div>
        </div>
        <div class="widget-body">
            <div class="widget-main">
                <table class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th><?php echo $this->translate('TIPO DE DOCUMENTO'); ?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->documentType as $documentType) : ?>
                            <tr>
                                <td><?php echo $this->escapeHtml($documentType->getName()); ?></td>
                                <td>
                                    <div class="btn-group-xs text-right">
                                        <a data-toggle="modal" data-target="#documentTypeEdit" class="btn btn-info icon-only btn-xs" href="<?php echo $this->url('dtladmin/dtldocumenttype/edit', array('id' => $documentType->getId()))
                            ?>"><i class="fa fa-edit"></i></a>
                                        <a data-toggle="modal" data-target="#documentTypeDelete" class="btn btn-danger btn-xs icon-only" href="<?php echo $this->url('dtladmin/dtldocumenttype/delete', array('id' => $documentType->getId()))
                            ?>"><i class="fa fa-times"></i></a>
                                    </div>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<div class="modal modal-danger fade" role="modal" tabindex="-1" aria-hidden="true" id="documentTypeDelete">
    <div class="modal-dialog"><div class="modal-content"></div></div>
</div>
<div class="modal modal-primary fade" role="modal" tabindex="-1" aria-hidden="true" id="documentTypeEdit">
    <div class="modal-dialog"><div class="modal-content"></div></div>
</div>
<div class="modal modal-success fade" role="modal" tabindex="-1" aria-hidden="true" id="documentTypeNew">
    <div class="modal-dialog"><div class="modal-content"></div></div>
</div>