<?php

namespace DoctrineORMModule\Proxy\__CG__\DtlRealty\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class RealtyFeature extends \DtlRealty\Entity\RealtyFeature implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'builtArea', 'balconyArea', 'totalArea', 'usefulArea', 'groundArea', 'groundLength', 'groundWidth', 'bedroomAmount', 'roomAmount', 'suiteAmount', 'bathtubAmount', 'bathroomAmount', 'hallAmount', 'bathroomStall', 'bathroomCabinet', 'roomCabinet', 'restroom', 'livingRoom', 'doubleLiving', 'diningRoom', 'tvRoom', 'office', 'kitchen', 'plannedKitchen', 'storeRoom', 'serviceArea', 'storeHouse', 'liningSlab', 'pvcLiner', 'planking', 'finishPlaster', 'gasHeater', 'solarHeater');
        }

        return array('__isInitialized__', 'id', 'builtArea', 'balconyArea', 'totalArea', 'usefulArea', 'groundArea', 'groundLength', 'groundWidth', 'bedroomAmount', 'roomAmount', 'suiteAmount', 'bathtubAmount', 'bathroomAmount', 'hallAmount', 'bathroomStall', 'bathroomCabinet', 'roomCabinet', 'restroom', 'livingRoom', 'doubleLiving', 'diningRoom', 'tvRoom', 'office', 'kitchen', 'plannedKitchen', 'storeRoom', 'serviceArea', 'storeHouse', 'liningSlab', 'pvcLiner', 'planking', 'finishPlaster', 'gasHeater', 'solarHeater');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (RealtyFeature $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getBuiltArea()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBuiltArea', array());

        return parent::getBuiltArea();
    }

    /**
     * {@inheritDoc}
     */
    public function getBalconyArea()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBalconyArea', array());

        return parent::getBalconyArea();
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalArea()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalArea', array());

        return parent::getTotalArea();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsefulArea()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsefulArea', array());

        return parent::getUsefulArea();
    }

    /**
     * {@inheritDoc}
     */
    public function getGroundArea()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGroundArea', array());

        return parent::getGroundArea();
    }

    /**
     * {@inheritDoc}
     */
    public function getGroundLength()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGroundLength', array());

        return parent::getGroundLength();
    }

    /**
     * {@inheritDoc}
     */
    public function getGroundWidth()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGroundWidth', array());

        return parent::getGroundWidth();
    }

    /**
     * {@inheritDoc}
     */
    public function getBedroomAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBedroomAmount', array());

        return parent::getBedroomAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function getRoomAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoomAmount', array());

        return parent::getRoomAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function getSuiteAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSuiteAmount', array());

        return parent::getSuiteAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function getBathtubAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBathtubAmount', array());

        return parent::getBathtubAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function getBathroomAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBathroomAmount', array());

        return parent::getBathroomAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function getHallAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHallAmount', array());

        return parent::getHallAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function getBathroomStall()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBathroomStall', array());

        return parent::getBathroomStall();
    }

    /**
     * {@inheritDoc}
     */
    public function getBathroomCabinet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBathroomCabinet', array());

        return parent::getBathroomCabinet();
    }

    /**
     * {@inheritDoc}
     */
    public function getRoomCabinet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoomCabinet', array());

        return parent::getRoomCabinet();
    }

    /**
     * {@inheritDoc}
     */
    public function getRestroom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRestroom', array());

        return parent::getRestroom();
    }

    /**
     * {@inheritDoc}
     */
    public function getLivingRoom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLivingRoom', array());

        return parent::getLivingRoom();
    }

    /**
     * {@inheritDoc}
     */
    public function getDoubleLiving()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDoubleLiving', array());

        return parent::getDoubleLiving();
    }

    /**
     * {@inheritDoc}
     */
    public function getDiningRoom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiningRoom', array());

        return parent::getDiningRoom();
    }

    /**
     * {@inheritDoc}
     */
    public function getTvRoom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTvRoom', array());

        return parent::getTvRoom();
    }

    /**
     * {@inheritDoc}
     */
    public function getOffice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOffice', array());

        return parent::getOffice();
    }

    /**
     * {@inheritDoc}
     */
    public function getKitchen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKitchen', array());

        return parent::getKitchen();
    }

    /**
     * {@inheritDoc}
     */
    public function getPlannedKitchen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlannedKitchen', array());

        return parent::getPlannedKitchen();
    }

    /**
     * {@inheritDoc}
     */
    public function getStoreRoom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStoreRoom', array());

        return parent::getStoreRoom();
    }

    /**
     * {@inheritDoc}
     */
    public function getServiceArea()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getServiceArea', array());

        return parent::getServiceArea();
    }

    /**
     * {@inheritDoc}
     */
    public function getStoreHouse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStoreHouse', array());

        return parent::getStoreHouse();
    }

    /**
     * {@inheritDoc}
     */
    public function getLiningSlab()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLiningSlab', array());

        return parent::getLiningSlab();
    }

    /**
     * {@inheritDoc}
     */
    public function getPvcLiner()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPvcLiner', array());

        return parent::getPvcLiner();
    }

    /**
     * {@inheritDoc}
     */
    public function getPlanking()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlanking', array());

        return parent::getPlanking();
    }

    /**
     * {@inheritDoc}
     */
    public function getFinishPlaster()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFinishPlaster', array());

        return parent::getFinishPlaster();
    }

    /**
     * {@inheritDoc}
     */
    public function getGasHeater()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGasHeater', array());

        return parent::getGasHeater();
    }

    /**
     * {@inheritDoc}
     */
    public function getSolarHeater()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSolarHeater', array());

        return parent::getSolarHeater();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setBuiltArea($builtArea)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBuiltArea', array($builtArea));

        return parent::setBuiltArea($builtArea);
    }

    /**
     * {@inheritDoc}
     */
    public function setBalconyArea($balconyArea)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBalconyArea', array($balconyArea));

        return parent::setBalconyArea($balconyArea);
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalArea($totalArea)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalArea', array($totalArea));

        return parent::setTotalArea($totalArea);
    }

    /**
     * {@inheritDoc}
     */
    public function setUsefulArea($usefulArea)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsefulArea', array($usefulArea));

        return parent::setUsefulArea($usefulArea);
    }

    /**
     * {@inheritDoc}
     */
    public function setGroundArea($groundArea)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGroundArea', array($groundArea));

        return parent::setGroundArea($groundArea);
    }

    /**
     * {@inheritDoc}
     */
    public function setGroundLength($groundLength)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGroundLength', array($groundLength));

        return parent::setGroundLength($groundLength);
    }

    /**
     * {@inheritDoc}
     */
    public function setGroundWidth($groundWidth)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGroundWidth', array($groundWidth));

        return parent::setGroundWidth($groundWidth);
    }

    /**
     * {@inheritDoc}
     */
    public function setBedroomAmount($bedroomAmount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBedroomAmount', array($bedroomAmount));

        return parent::setBedroomAmount($bedroomAmount);
    }

    /**
     * {@inheritDoc}
     */
    public function setRoomAmount($roomAmount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoomAmount', array($roomAmount));

        return parent::setRoomAmount($roomAmount);
    }

    /**
     * {@inheritDoc}
     */
    public function setSuiteAmount($suiteAmount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSuiteAmount', array($suiteAmount));

        return parent::setSuiteAmount($suiteAmount);
    }

    /**
     * {@inheritDoc}
     */
    public function setBathtubAmount($bathtubAmount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBathtubAmount', array($bathtubAmount));

        return parent::setBathtubAmount($bathtubAmount);
    }

    /**
     * {@inheritDoc}
     */
    public function setBathroomAmount($bathroomAmount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBathroomAmount', array($bathroomAmount));

        return parent::setBathroomAmount($bathroomAmount);
    }

    /**
     * {@inheritDoc}
     */
    public function setHallAmount($hallAmount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHallAmount', array($hallAmount));

        return parent::setHallAmount($hallAmount);
    }

    /**
     * {@inheritDoc}
     */
    public function setBathroomStall($bathroomStall)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBathroomStall', array($bathroomStall));

        return parent::setBathroomStall($bathroomStall);
    }

    /**
     * {@inheritDoc}
     */
    public function setBathroomCabinet($bathroomCabinet)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBathroomCabinet', array($bathroomCabinet));

        return parent::setBathroomCabinet($bathroomCabinet);
    }

    /**
     * {@inheritDoc}
     */
    public function setRoomCabinet($roomCabinet)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoomCabinet', array($roomCabinet));

        return parent::setRoomCabinet($roomCabinet);
    }

    /**
     * {@inheritDoc}
     */
    public function setRestroom($restroom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRestroom', array($restroom));

        return parent::setRestroom($restroom);
    }

    /**
     * {@inheritDoc}
     */
    public function setLivingRoom($livingRoom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLivingRoom', array($livingRoom));

        return parent::setLivingRoom($livingRoom);
    }

    /**
     * {@inheritDoc}
     */
    public function setDoubleLiving($doubleLiving)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDoubleLiving', array($doubleLiving));

        return parent::setDoubleLiving($doubleLiving);
    }

    /**
     * {@inheritDoc}
     */
    public function setDiningRoom($diningRoom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiningRoom', array($diningRoom));

        return parent::setDiningRoom($diningRoom);
    }

    /**
     * {@inheritDoc}
     */
    public function setTvRoom($tvRoom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTvRoom', array($tvRoom));

        return parent::setTvRoom($tvRoom);
    }

    /**
     * {@inheritDoc}
     */
    public function setOffice($office)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOffice', array($office));

        return parent::setOffice($office);
    }

    /**
     * {@inheritDoc}
     */
    public function setKitchen($kitchen)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKitchen', array($kitchen));

        return parent::setKitchen($kitchen);
    }

    /**
     * {@inheritDoc}
     */
    public function setPlannedKitchen($plannedKitchen)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlannedKitchen', array($plannedKitchen));

        return parent::setPlannedKitchen($plannedKitchen);
    }

    /**
     * {@inheritDoc}
     */
    public function setStoreRoom($storeRoom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStoreRoom', array($storeRoom));

        return parent::setStoreRoom($storeRoom);
    }

    /**
     * {@inheritDoc}
     */
    public function setServiceArea($serviceArea)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setServiceArea', array($serviceArea));

        return parent::setServiceArea($serviceArea);
    }

    /**
     * {@inheritDoc}
     */
    public function setStoreHouse($storeHouse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStoreHouse', array($storeHouse));

        return parent::setStoreHouse($storeHouse);
    }

    /**
     * {@inheritDoc}
     */
    public function setLiningSlab($liningSlab)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLiningSlab', array($liningSlab));

        return parent::setLiningSlab($liningSlab);
    }

    /**
     * {@inheritDoc}
     */
    public function setPvcLiner($pvcLiner)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPvcLiner', array($pvcLiner));

        return parent::setPvcLiner($pvcLiner);
    }

    /**
     * {@inheritDoc}
     */
    public function setPlanking($planking)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlanking', array($planking));

        return parent::setPlanking($planking);
    }

    /**
     * {@inheritDoc}
     */
    public function setFinishPlaster($finishPlaster)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFinishPlaster', array($finishPlaster));

        return parent::setFinishPlaster($finishPlaster);
    }

    /**
     * {@inheritDoc}
     */
    public function setGasHeater($gasHeater)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGasHeater', array($gasHeater));

        return parent::setGasHeater($gasHeater);
    }

    /**
     * {@inheritDoc}
     */
    public function setSolarHeater($solarHeater)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSolarHeater', array($solarHeater));

        return parent::setSolarHeater($solarHeater);
    }

}
