<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'DtlPatrimony\Form\Fieldset\Patrimony' => __DIR__ . '/src/DtlPatrimony/Form/Fieldset/Patrimony.php',
  'DtlPatrimony\Entity\Patrimony'        => __DIR__ . '/src/DtlPatrimony/Entity/Patrimony.php',
  'DtlPatrimony\Module'                  => __DIR__ . '/Module.php',
);
