<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'PaymentType\Form\Fieldset\PaymentType'        => __DIR__ . '/src/PaymentType/Form/Fieldset/PaymentType.php',
  'PaymentType\Form\PaymentType'                 => __DIR__ . '/src/PaymentType/Form/PaymentType.php',
  'PaymentType\Factory\PaymentType'              => __DIR__ . '/src/PaymentType/Factory/PaymentType.php',
  'PaymentType\Controller\PaymentTypeController' => __DIR__ . '/src/PaymentType/Controller/PaymentTypeController.php',
  'PaymentType\Entity\PaymentType'               => __DIR__ . '/src/PaymentType/Entity/PaymentType.php',
  'PaymentType\Module'                           => __DIR__ . '/Module.php',
);
