<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'DtlSeller\Form\Fieldset\Seller'        => __DIR__ . '/src/DtlSeller/Form/Fieldset/Seller.php',
  'DtlSeller\Form\Seller'                 => __DIR__ . '/src/DtlSeller/Form/Seller.php',
  'DtlSeller\Factory\Seller'              => __DIR__ . '/src/DtlSeller/Factory/Seller.php',
  'DtlSeller\Controller\SellerController' => __DIR__ . '/src/DtlSeller/Controller/SellerController.php',
  'DtlSeller\Entity\Repository\Seller'    => __DIR__ . '/src/DtlSeller/Entity/Repository/Seller.php',
  'DtlSeller\Entity\Seller'               => __DIR__ . '/src/DtlSeller/Entity/Seller.php',
  'DtlSeller\Module'                      => __DIR__ . '/Module.php',
);
