<?php
$title = $this->translate('Novo Tipo de Veículo');
$this->headTitle($title);
$form = $this->form;
$form->prepare();
?>
<h2 class="container-header"><?php echo $this->escapeHtml($title); ?></h2>
<div class="row">
    <div class="col-md-4">
        <?php echo $this->form()->openTag($form); ?>
        <fieldset>
            <legend><?php echo $title; ?></legend>
            <?php $vehicleType = $form->get('vehicleType'); ?>
            <div class="form-group">
                <?php echo $this->formHidden($vehicleType->get('id')); ?>
                <div class="row">
                    <div class="col-md-12">
                        <?php echo $this->formLabel($vehicleType->get('brand')); ?>
                        <?php echo $this->formSelect($vehicleType->get('brand')); ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <?php echo $this->formLabel($vehicleType->get('name')); ?>
                        <?php echo $this->formSelect($vehicleType->get('name')); ?>
                    </div>
                </div>
                <?php echo $this->formHidden($form->get('security')); ?>
            </div>
            <div class="btn-group btn-group-sm">  
                <?php echo $this->formElement($form->get('submit')); ?>
                <?php echo $this->formElement($form->get('cancel')); ?>
            </div>
        </fieldset>
        <?php echo $this->form()->closeTag(); ?>
    </div>
    <div class="col-md-8">
        <legend>Lista de Tipos</legend>
        <div class="vehicle-type-list">
            <div class="alert alert-info">
                Selecione a Marca do veículo que deseja listar os tipos disponíveis.
            </div>
        </div>
    </div>
</div>