<table class="table table-condensed table-hover">
    <tr>
        <th colspan="10"><?php echo $this->translate('TIPO'); ?></th>
    </tr>
    <?php if (0 == count($this->vehicleType)): ?>
        <tr>
            <td colspan="10" class="alert alert-info text-center"><?php echo $this->translate('Nenhum registro encontrado.') ?></td>
        </tr>
    <?php else: ?>
        <?php foreach ($this->vehicleType as $vehicleType) : ?>
            <tr>
                <td><?php echo $this->escapeHtml($vehicleType->getName()); ?></td>
                <td>
                    <div class="btn-group btn-group-xs pull-right">
                        <a class="btn btn-default" href="javascript: vehicleTypeDelete('<?php echo $vehicleType->getId();?>','<?php echo $vehicleType->getBrand()->getId();?>');"><i class="glyphicon glyphicon-remove"></i></a>
                    </div>
                </td>
            </tr>
        <?php endforeach; ?>
    <?php endif; ?>
</table>
