<?php
$title = $this->translate('Adicionar Produto');
$this->headTitle($title);
$form = $this->form;
$form->prepare();
?>
<h1 class="container-header"><i class="glyphicon glyphicon-th-large"></i> <?php echo $this->escapeHtml($title); ?></h1>
<div class="row">
    <div class="col-md-4">
        <?php echo $this->form()->openTag($form); ?>
        <div class="form-gorup">
            <?php $product = $form->get('product'); ?>
            <?php echo $this->formHidden($product->get('id')); ?>
            <div class="row">
                <div class="col-md-12">
                    <?php echo $this->formLabel($product->get('category')); ?>
                    <?php echo $this->formSelect($product->get('category')); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <?php echo $this->formLabel($product->get('name')); ?>
                    <?php echo $this->formText($product->get('name')); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <?php echo $this->formLabel($product->get('variantCommission')); ?>
                    <div class="input-group">
                        <?php echo $this->formText($product->get('variantCommission')); ?>
                        <span class="input-group-addon">%</span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <?php echo $this->formLabel($product->get('fixedCommission')); ?>
                    <div class="input-group">
                        <span class="input-group-addon">R$</span>
                        <?php echo $this->formText($product->get('fixedCommission')); ?>
                    </div>
                </div>
            </div>
        </div>
        <?php echo $this->formHidden($form->get('security')); ?>
        <br/>
        <div class="btn-group">
            <?php echo $this->formElement($form->get('submit')); ?>
            <?php echo $this->formElement($form->get('cancel')); ?>
        </div>
        <?php echo $this->form()->closeTag(); ?>
    </div>
    <div class="col-md-8">
        <div class="product-list"></div>
    </div>
</div>
<script type="text/javascript">
    productList(null);
</script>
