<?php $total = 0; ?>
<div class="panel panel-warning">
    <div class="panel-heading">
        <div class="panel-title">
            <i class="glyphicon glyphicon-home"></i> 
            Listagem de Imóveis
        </div>
    </div>
    <?php if (0 == count($this->realties)): ?>
        <div class="panel-body">
            <div class="alert alert-info">
                <?php echo $this->translate('Nenhum registro encontrado.') ?>
            </div>
        </div>
    <?php else: ?>
        <table class="table table-condensed table-hover">
            <tr>
                <th><?php echo $this->translate('TIPO'); ?></th>
                <th><?php echo $this->translate('CIDADE'); ?></th>
                <th colspan="2"><?php echo $this->translate('VALOR'); ?></th>
            </tr>
            <?php foreach ($this->realties as $key => $realty) : ?>
                <tr>
                    <td><?php echo $realty['realtyTypeName']; ?></td>
                    <td><?php echo $realty['addressCity']; ?></td>
                    <td class="col-md-2"><?php echo $this->currency($realty['realtyValue']); ?></td>
                    <td class="col-md-1">
                        <div class="btn-group btn-group-xs pull-right">
                            <a class="btn btn-default btn-xs" href="javascript: realtyProposalDelete('<?php echo $key ?>')"><i class="glyphicon glyphicon-remove"></i></a>
                        </div>
                    </td>
                </tr>
                <?php $total += $realty['realtyValue']; ?>
            <?php endforeach; ?>
            <tr class="text-success">
                <td colspan="2" class="text-right"><b>TOTAL:</b></td>
                <td colspan="2"><b><?php echo $this->currency($total); ?></b></td>
            </tr>
        </table>
    <?php endif; ?>
</div>