<div class="row">
    <div class="col-md-12">
        <?php $realtyProposal = $this->realtyProposal; ?>
        <?php $realty = $realtyProposal; ?>
        <div class="form-group">
            <div class="row">
                <div class="col-md-6">
                    <div class="row">
                        <div class="col-md-4">
                            <?php echo $this->formLabel($realty->get('type')); ?>
                            <?php echo $this->formSelect($realty->get('type')); ?>
                        </div>
                        <div class="col-md-4">
                            <?php echo $this->formLabel($realty->get('code')); ?>
                            <?php echo $this->formText($realty->get('code')); ?>
                        </div>
                        <div class="col-md-4">
                            <?php echo $this->formLabel($realty->get('value')); ?>
                            <div class="input-group">
                                <span class="input-group-addon">R$</span>
                                <?php echo $this->formText($realty->get('value')); ?>
                            </div>
                        </div>
                    </div>
                    <?php $realtyFeature = $realty->get('feature'); ?>
                    <div class="row">
                        <div class="col-md-4">
                            <?php echo $this->formLabel($realtyFeature->get('builtArea')); ?>
                            <div class="input-group">
                                <?php echo $this->formText($realtyFeature->get('builtArea')); ?>
                                <span class="input-group-addon">m²</span>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <?php echo $this->formLabel($realtyFeature->get('balconyArea')); ?>
                            <div class="input-group">
                                <?php echo $this->formText($realtyFeature->get('balconyArea')); ?>
                                <span class="input-group-addon">m²</span>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <?php echo $this->formLabel($realtyFeature->get('totalArea')); ?>
                            <div class="input-group">
                                <?php echo $this->formText($realtyFeature->get('totalArea')); ?>
                                <span class="input-group-addon">m²</span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <?php echo $this->formLabel($realtyFeature->get('groundLength')); ?>
                            <div class="input-group">
                                <?php echo $this->formText($realtyFeature->get('groundLength')); ?>
                                <span class="input-group-addon">m²</span>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <?php echo $this->formLabel($realtyFeature->get('groundWidth')); ?>
                            <div class="input-group">
                                <?php echo $this->formText($realtyFeature->get('groundWidth')); ?>
                                <span class="input-group-addon">m²</span>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <?php echo $this->formLabel($realtyFeature->get('groundArea')); ?>
                            <div class="input-group">
                                <?php echo $this->formText($realtyFeature->get('groundArea')); ?>
                                <span class="input-group-addon">m²</span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <?php echo $this->formLabel($realty->get('notes')); ?>
                            <?php echo $this->formTextarea($realty->get('notes')); ?>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <?php $address = $realty->get('address'); ?>
                    <?php echo $this->formHidden($address->get('id')); ?>
                    <div class="row">
                        <div class="col-md-8">
                            <?php echo $this->formLabel($address->get('name')); ?>
                            <?php echo $this->formText($address->get('name')); ?>
                        </div>
                        <div class="col-md-4">
                            <?php echo $this->formLabel($address->get('number')); ?>
                            <?php echo $this->formText($address->get('number')); ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <?php echo $this->formLabel($address->get('complement')); ?>
                            <?php echo $this->formText($address->get('complement')); ?>
                        </div>
                        <div class="col-md-4">
                            <?php echo $this->formLabel($address->get('quarter')); ?>
                            <?php echo $this->formText($address->get('quarter')); ?>
                        </div>
                        <div class="col-md-4">
                            <?php echo $this->formLabel($address->get('postalCode')); ?>
                            <?php echo $this->formText($address->get('postalCode')); ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-8">
                            <?php echo $this->formLabel($address->get('city')); ?>
                            <?php echo $this->formSelect($address->get('city')); ?>
                        </div>
                        <div class="col-md-4">
                            <?php echo $this->formLabel($address->get('state')); ?>
                            <?php echo $this->formSelect($address->get('state')); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>