<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'DtlCompany\Form\Fieldset\User'                   => __DIR__ . '/src/DtlCompany/Form/Fieldset/User.php',
  'DtlCompany\Form\Fieldset\Company'                => __DIR__ . '/src/DtlCompany/Form/Fieldset/Company.php',
  'DtlCompany\Form\Company'                         => __DIR__ . '/src/DtlCompany/Form/Company.php',
  'DtlCompany\Factory\CompanyControllerFactory'     => __DIR__ . '/src/DtlCompany/Factory/CompanyControllerFactory.php',
  'DtlCompany\Controller\CompanyController'         => __DIR__ . '/src/DtlCompany/Controller/CompanyController.php',
  'DtlCompany\Entity\Repository\Company'            => __DIR__ . '/src/DtlCompany/Entity/Repository/Company.php',
  'DtlCompany\Entity\Company'                       => __DIR__ . '/src/DtlCompany/Entity/Company.php',
  'DtlCompany\Module'                               => __DIR__ . '/Module.php',
);
