<?php
$title = $this->translate('Moedas');
$this->headTitle($title);
?>
<div class="panel panel-default">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-6">
                <h4 class="panel-title"><i class="glyphicon glyphicon-flag"></i> <?php echo $this->escapeHtml($title); ?></h4>
            </div>
            <div class="col-md-6">
                <div class="btn-group btn-group-sm pull-right">
                    <a class="btn btn-default" href="<?php echo $this->url('dtladmin/dtlcurrency/add'); ?>"> <i class="glyphicon glyphicon-plus-sign"></i> <?php echo $this->translate('Novo'); ?></a>
                </div>
            </div>
        </div>
    </div>
    <table class="table table-condensed table-hover">
        <tr>
            <th class="" colspan="2"><?php echo $this->translate('MOEDA'); ?></th>
        </tr>
        <?php if (0 == count($this->currency)): ?>
            <tr>
                <td colspan="10" class="alert alert-info text-center"><?php echo $this->translate('Não há registros no banco de dados.') ?></td>
            </tr>
        <?php else: ?>
            <?php foreach ($this->currency as $currency) : ?>
                <tr>
                    <td><?php echo $this->escapeHtml($currency->getName()); ?></td>
                    <td>
                        <div class="btn-group btn-group-xs pull-right">
                            <a class="btn btn-default" href="<?php echo $this->url('dtladmin/dtlcurrency/edit', array('id' => $currency->getId()))
                ?>"><i class="glyphicon glyphicon-edit"></i></a>
                            <a class="btn btn-default" href="<?php echo $this->url('dtladmin/dtlcurrency/delete', array('id' => $currency->getId()))
                ?>"><i class="glyphicon glyphicon-remove"></i></a>
                        </div>
                    </td>
                </tr>
            <?php endforeach; ?>
        <?php endif; ?>
        </tbody>
    </table>
    <div class="panel-footer">
        <?php
        $paginationInfo = $this->placeholder('pagination');
        if (!isset($paginationInfo->route)) {
            $paginationInfo->route = 'dtladmin/dtlcurrency';
            $paginationInfo->params = array();
        }
        ?>
        <?php echo $this->paginationControl($this->currency, 'Sliding', 'layout/pagination'); ?>
    </div>
</div>
