<?php
$title = $this->translate('Adicionar Item Contábil');
$this->headTitle($title);
$form = $this->form;
$form->setAttribute('action', $this->url('dtladmin/dtlaccountingitem/add'));
$form->prepare();
?>
<?php echo $this->form()->openTag($form); ?>
<div class="modal-header">
    <h3 class="modal-title"><i class="fa fa-plus-circle"></i> <?php echo $this->escapeHtml($title); ?></h3>
</div>
<div class="modal-body">
    <?php $accountingItem = $form->get('accountingItem'); ?>
    <?php echo $this->formHidden($accountingItem->get('id')); ?>
    <div class="form-group">
        <?php echo $this->formLabel($accountingItem->get('name')); ?>
        <?php echo $this->formText($accountingItem->get('name')); ?>
    </div>
    <div class="control-group">
        <div class="radio">
            <?php echo $this->formRadio($accountingItem->get('type')); ?>
        </div>
    </div>
</div>
<div class="modal-footer">
    <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> <?php echo $this->translate('Salvar'); ?></button>
    <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="fa fa-times"></i> <?php echo $this->translate('Cancelar'); ?></button>
</div>
<?php echo $this->form()->closeTag(); ?>
