<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'DtlEmployeeStatus\Form\EmployeeStatus'                 => __DIR__ . '/src/DtlEmployeeStatus/Form/EmployeeStatus.php',
  'DtlEmployeeStatus\Form\Fieldset\EmployeeStatus'        => __DIR__ . '/src/DtlEmployeeStatus/Form/Fieldset/EmployeeStatus.php',
  'DtlEmployeeStatus\Factory\EmployeeStatus'              => __DIR__ . '/src/DtlEmployeeStatus/Factory/EmployeeStatus.php',
  'DtlEmployeeStatus\Controller\EmployeeStatusController' => __DIR__ . '/src/DtlEmployeeStatus/Controller/EmployeeStatusController.php',
  'DtlEmployeeStatus\Entity\EmployeeStatus'               => __DIR__ . '/src/DtlEmployeeStatus/Entity/EmployeeStatus.php',
  'DtlEmployeeStatus\Module'                              => __DIR__ . '/Module.php',
);
