<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'DtlRealty\Form\Fieldset\Realty'               => __DIR__ . '/src/DtlRealty/Form/Fieldset/Realty.php',
  'DtlRealty\Form\Fieldset\RealtyFeature'        => __DIR__ . '/src/DtlRealty/Form/Fieldset/RealtyFeature.php',
  'DtlRealty\Form\Fieldset\RealtyType'           => __DIR__ . '/src/DtlRealty/Form/Fieldset/RealtyType.php',
  'DtlRealty\Form\Realty'                        => __DIR__ . '/src/DtlRealty/Form/Realty.php',
  'DtlRealty\Form\RealtyType'                    => __DIR__ . '/src/DtlRealty/Form/RealtyType.php',
  'DtlRealty\Factory\Realty'                     => __DIR__ . '/src/DtlRealty/Factory/Realty.php',
  'DtlRealty\Factory\RealtyType'                 => __DIR__ . '/src/DtlRealty/Factory/RealtyType.php',
  'DtlRealty\Controller\RealtyTypeController'    => __DIR__ . '/src/DtlRealty/Controller/RealtyTypeController.php',
  'DtlRealty\Controller\RealtyController'        => __DIR__ . '/src/DtlRealty/Controller/RealtyController.php',
  'DtlRealty\Controller\RealtyFeatureController' => __DIR__ . '/src/DtlRealty/Controller/RealtyFeatureController.php',
  'DtlRealty\Entity\Realty'                      => __DIR__ . '/src/DtlRealty/Entity/Realty.php',
  'DtlRealty\Entity\RealtyFeature'               => __DIR__ . '/src/DtlRealty/Entity/RealtyFeature.php',
  'DtlRealty\Entity\RealtyType'                  => __DIR__ . '/src/DtlRealty/Entity/RealtyType.php',
  'DtlRealty\Module'                             => __DIR__ . '/Module.php',
);
