<div class="panel panel-warning">
    <div class="panel-heading">
        <h1 class="panel-title"><i class="glyphicon glyphicon-usd"></i> Lista de Conta do Cliente</h1>
    </div>
    <table class="table table-condensed table-hover">
        <tr>
            <th class=""><?php echo $this->translate('TIPO DA CONTA'); ?></th>
            <th class=""><?php echo $this->translate('BANCO'); ?></th>
            <th class=""><?php echo $this->translate('AGÊNCIA'); ?></th>
            <th class=""><?php echo $this->translate('CONTA'); ?></th>
            <th class="" colspan="2"><?php echo $this->translate('CLIENTE DESDE'); ?></th>
        </tr>
        <?php if (0 == count($this->customerBankAccount)): ?>
            <tr class="alert alert-info">
                <td colspan="10" class="alert alert-info text-center"><?php echo $this->translate('Nenhum registro encontrado.') ?></td>
            </tr>
        <?php else: ?>
            <?php foreach ($this->customerBankAccount as $customerBankAccount) : ?>
                <tr>
                    <td><?php echo $this->escapeHtml($customerBankAccount->getType()); ?></td>
                    <td><?php echo $customerBankAccount->getBank()->getName(); ?></td>
                    <td><?php echo $this->escapeHtml($customerBankAccount->getAgency()); ?></td>
                    <td><?php echo $this->escapeHtml($customerBankAccount->getAccount()); ?></td>
                    <td><?php echo $this->escapeHtml($customerBankAccount->getSince()); ?></td>
                    <td>
                        <div class="btn-group btn-group-xs pull-right">
                            <a class="btn btn-default" href="javascript: customerBankAccountDelete('<?php echo $customerBankAccount->getId(); ?>', '<?php echo $this->customerId; ?>')"><i class="glyphicon glyphicon-remove"></i></a>
                        </div>
                    </td>
                </tr>
            <?php endforeach; ?>
        <?php endif; ?>
    </table>
</div>