<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'DtlAccountingItem\Form\AccountingItem'                 => __DIR__ . '/src/DtlAccountingItem/Form/AccountingItem.php',
  'DtlAccountingItem\Form\Fieldset\AccountingItem'        => __DIR__ . '/src/DtlAccountingItem/Form/Fieldset/AccountingItem.php',
  'DtlAccountingItem\Factory\AccountingItem'              => __DIR__ . '/src/DtlAccountingItem/Factory/AccountingItem.php',
  'DtlAccountingItem\Controller\AccountingItemController' => __DIR__ . '/src/DtlAccountingItem/Controller/AccountingItemController.php',
  'DtlAccountingItem\Entity\AccountingItem'               => __DIR__ . '/src/DtlAccountingItem/Entity/AccountingItem.php',
  'DtlAccountingItem\Module'                              => __DIR__ . '/Module.php',
);
