<h3 class="header-title"><i class="glyphicon glyphicon-lock"></i> Trocar senha para <?php echo $this->zfcUserDisplayName() ?></h3>
<?php if ($status === true) : ?>
    <div class="alert alert-success">Senha alterada com sucesso.</div>
<?php elseif ($status === false) : ?>
    <div class="alert alert-danger">Não foi possível alterar sua senha. Por favor, tente novamente.</div>
<?php endif; ?>
<?php
$form = $this->changePasswordForm;
$form->get('credential')->setAttribute('class', 'form-control input-sm');
$form->get('newCredential')->setAttribute('class', 'form-control input-sm');
$form->get('newCredentialVerify')->setAttribute('class', 'form-control input-sm');
$form->get('identity')->setAttributes(array(
    'class' => 'form-control input-sm',
    'autocomplete' => 'off',
));
$form->get('submit')->setValue('Alterar Senha');

$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/changepassword'));
$form->setAttribute('method', 'post');

echo $this->form()->openTag($form);
?>
<div class="form-group">
    <div class="row">
        <?php echo $this->formElementErrors($form->get('identity')); ?>
        <div class="col-md-2">
            <label for="credential">Usuário ou E-mail</label>
            <?php echo $this->formText($form->get('identity')); ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            <label for="credential">Senha atual</label>
            <?php echo $this->formInput($form->get('credential')) . $this->formElementErrors($form->get('credential')); ?></dd>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            <label for="newCredential">Nova Senha</label>
            <?php echo $this->formInput($form->get('newCredential')) . $this->formElementErrors($form->get('newCredential')); ?></dd>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            <label for="newCredentialVerify">Confirma Senha</label>
            <?php echo $this->formInput($form->get('newCredentialVerify')) . $this->formElementErrors($form->get('newCredentialVerify')); ?>
        </div>
    </div>
    <br/>
    <div>
        <?php echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn btn-primary')); ?>
        <a href="<?php echo $this->url('home');?>" class="btn btn-default">Voltar</a>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>
