<?php
$form = $this->registerForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/register'));
$form->setAttribute('method', 'post');
?>
<?php echo $this->form()->openTag($form) ?>
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <h3 class="modal-title text-center"><i class="glyphicon glyphicon-lock"></i> <?php echo $this->translate('Registrando em Vallorisa'); ?></h3>
</div>
<div class="modal-body">
    <?php
    if (!$this->enableRegistration) {
        print "O registro foi desabilitado.";
        return;
    }
    ?>
    <?php $userProfile = $form->get('userProfile'); ?>
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <?php echo $this->formText($form->get('display_name')->setAttribute('placeholder', 'Nome')); ?>
                    <?php echo $this->formElementErrors($form->get('display_name')); ?>
                </div>
                <div class="form-group">
                    <?php echo $this->formEmail($form->get('email')->setAttribute('placeholder', 'Email')); ?>
                    <?php echo $this->formElementErrors($form->get('email')); ?>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <?php echo $this->formPassword($form->get('password')->setAttribute('placeholder', 'Senha')); ?>
                    <?php echo $this->formElementErrors($form->get('password')); ?>
                </div>
                <div class="form-group">
                    <?php echo $this->formPassword($form->get('passwordVerify')->setAttribute('placeholder', 'Password Verify')); ?>
                    <?php echo $this->formElementErrors($form->get('passwordVerify')); ?>
                </div>
            </div>
        </div>
        <div class="form-group">
            <?php echo $this->formTextarea($userProfile->get('about')); ?>
            <?php echo $this->formElementErrors($userProfile->get('about')); ?>
        </div>
        <div class="form-group text-primary text-center">
            <?php echo $this->formCheckbox($userProfile->get('news')); ?>
            <?php echo $this->formLabel($userProfile->get('news')); ?>
        </div>
    </div>
    <?php if ($this->redirect): ?>
        <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
    <?php endif ?>
    <div class="form-group text-center">
        <?php echo $this->formElement($form->get('submit')->setAttribute('class', 'btn btn-default')); ?>
    </div>
</div>
<?php
echo $this->form()->closeTag();
