<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'DtlPretender\Form\Fieldset\Pretender'        => __DIR__ . '/src/DtlPretender/Form/Fieldset/Pretender.php',
  'DtlPretender\Form\Pretender'                 => __DIR__ . '/src/DtlPretender/Form/Pretender.php',
  'DtlPretender\Factory\Pretender'              => __DIR__ . '/src/DtlPretender/Factory/Pretender.php',
  'DtlPretender\Controller\PretenderController' => __DIR__ . '/src/DtlPretender/Controller/PretenderController.php',
  'DtlPretender\Entity\Repository\Pretender'    => __DIR__ . '/src/DtlPretender/Entity/Repository/Pretender.php',
  'DtlPretender\Entity\Pretender'               => __DIR__ . '/src/DtlPretender/Entity/Pretender.php',
  'DtlPretender\Module'                        => __DIR__ . '/Module.php',
);
