<h1 class="container-header"><i class="glyphicon glyphicon-dashboard"></i> Painel de Controle</h1>
<div class="row">
    <div class="col-md-4">
        <div class="panel panel-warning">
            <div class="panel-heading">
                <h1 class="panel-title">
                    <i class="glyphicon glyphicon-group"></i> 
                    Últimos Clientes
                    <i class="badge pull-right"><?php echo $this->customerCount; ?></i>
                </h1>
            </div>
            <table class="table table-condensed no-datatables">
                <thead>
                    <tr>
                        <th>NOME</th>
                        <th>DATA</th>
                    </tr>
                </thead>
                <?php if (!count($this->customer) > 0): ?>
                    <tbody>
                        <tr>
                            <td colspan="10"><?php echo $this->info('Nenhum cliente cadastrados.'); ?></td>
                        </tr>
                    </tbody>
                <?php else: ?>
                    <?php foreach ($this->customer as $customer): ?>
                        <tr>
                            <td><?php echo $customer['name']; ?></td>
                            <td><?php echo $this->date($customer['timestamp']); ?></td>
                        </tr>
                    <?php endforeach; ?>
                <?php endif; ?>
            </table>
        </div>
    </div>
    <div class="col-md-8">
        <div class="panel panel-warning">
            <div class="panel-heading">
                <h1 class="panel-title">
                    <i class="glyphicon glyphicon-share"></i> 
                    Meus Atalhos
                    <a href="#"><i class="glyphicon glyphicon-cog pull-right"></i></a>
                </h1>
            </div>
            <div class="panel-body">
                <div class="text-center">
                    <a href="<?php echo $this->basePath() ?>/admin/proposal/vehicle-proposal/1/pre" class="btn btn-shortcut">
                        <span><i class="fa fa-truck"></i></span> Nova Proposta
                    </a>
                    <a href="<?php echo $this->basePath() ?>/admin/proposal/loan/1/pre" class="btn btn-shortcut">
                        <span><i class="fa fa-money"></i></span>Nova Proposta
                    </a>
                    <a href="<?php echo $this->basePath() ?>/admin/proposal/realty-proposal/1/pre" class="btn btn-shortcut">
                        <span><i class="fa fa-building-o"></i></span>Nova Proposta
                    </a>
                    <a href="<?php echo $this->basePath() ?>/admin/proposal/caixa-proposal/1/pre" class="btn btn-shortcut">
                        <span><i class="glyphicon glyphicon-usd"></i></span>Nova Proposta
                    </a>
                    <a href="<?php echo $this->basePath() ?>/admin/customer" class="btn btn-shortcut">
                        <span><i class="glyphicon glyphicon-user"></i></span>Clientes
                    </a>
                    <?php // if ($this->isGranted('admin')):?>
                    <a href="<?php echo $this->basePath() ?>/admin/shopman" class="btn btn-shortcut">
                        <span><i class="glyphicon glyphicon-shopping-cart"></i></span>Lojistas
                    </a>
                    <a href="<?php echo $this->basePath() ?>/admin/realtor" class="btn btn-shortcut">
                        <span><i class="glyphicon glyphicon-home"></i></span>Corretores
                    </a>
                    <?php // endif; ?>
                </div>
            </div>
        </div>
    </div>
</div>
