<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'DtlSupplier\Form\Fieldset\Supplier'        => __DIR__ . '/src/DtlSupplier/Form/Fieldset/Supplier.php',
  'DtlSupplier\Form\Supplier'                 => __DIR__ . '/src/DtlSupplier/Form/Supplier.php',
  'DtlSupplier\Factory\Supplier'              => __DIR__ . '/src/DtlSupplier/Factory/Supplier.php',
  'DtlSupplier\Controller\SupplierController' => __DIR__ . '/src/DtlSupplier/Controller/SupplierController.php',
  'DtlSupplier\Entity\Repository\Supplier'    => __DIR__ . '/src/DtlSupplier/Entity/Repository/Supplier.php',
  'DtlSupplier\Entity\Supplier'               => __DIR__ . '/src/DtlSupplier/Entity/Supplier.php',
  'DtlSupplier\Module'                        => __DIR__ . '/Module.php',
);
