<?php
$account = $this->account;
$form = $this->form;
$discharge = $form->get('discharge');
?>  
<div role="dialog" class="modal fade" id="dischargeModal<?php echo $this->account->getAccount()->getId(); ?>" tabindex="-1" aria-labelledby="dischargeLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <?php echo $this->form()->openTag($form); ?>
            <div class="modal-header">
                <h3 class='modal-title'><?php echo $this->translate('Baixa de Conta');?></h3>
            </div>
            <div class="modal-body">
                <?php echo $this->formHidden($discharge->get('id')); ?>
                <?php echo $this->formHidden($discharge->get('parcel')); ?>
                <input type="hidden" name="accountId" value="<?php echo $account->getAccount()->getId(); ?>">
                <div class="form-group">
                    <div class='row'>
                        <label class='col-sm-6 control-label'>Data de Venc.:</label>
                        <p class='form-control input-sm-static col-md-6'>
                            <?php echo $account->getAccount()->getExpirationDate(); ?>
                        </p>
                    </div>
                </div>
                <div class="form-group">
                    <div class='row'>
                        <label class='col-sm-6 control-label'>Valor da Conta</label>
                        <p class='form-control input-sm-static col-sm-6'>
                            <?php echo $this->currency($account->getAccount()->getValue()); ?>
                        </p>
                    </div>
                </div>
                <hr/>
                <div class="row">
                    <div class="col-md-12">
                        <?php echo $this->formLabel($discharge->get('date')); ?>
                        <?php echo $this->formText($discharge->get('date')->setValue(date('d/m/Y'))); ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <?php echo $this->formLabel($discharge->get('value')); ?>
                        <div class="input-group">
                            <span class="input-group-addon">R$</span>
                            <?php echo $this->formText($discharge->get('value')->setValue($account->getAccount()->getValue())); ?>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <?php echo $this->formSubmit($form->get('submit')); ?>
                <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">Fechar</button>
            </div>
            <?php echo $this->form()->closeTag($form); ?>
        </div>
    </div>
</div>