<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'DtlBusiness\Form\Fieldset\Business'        => __DIR__ . '/src/DtlBusiness/Form/Fieldset/Business.php',
  'DtlBusiness\Form\Business'                 => __DIR__ . '/src/DtlBusiness/Form/Business.php',
  'DtlBusiness\Factory\Business'              => __DIR__ . '/src/DtlBusiness/Factory/Business.php',
  'DtlBusiness\Controller\BusinessController' => __DIR__ . '/src/DtlBusiness/Controller/BusinessController.php',
  'DtlBusiness\Strategy\Business'             => __DIR__ . '/src/DtlBusiness/Strategy/\business.php',
  'DtlBusiness\Entity\Business'               => __DIR__ . '/src/DtlBusiness/Entity/Business.php',
  'DtlBusiness\Module'                        => __DIR__ . '/Module.php',
);
