<?php
$title = $this->translate('Adicionar Receita');
$this->headTitle($title);
$form = $this->form;
$form->setAttribute('action', $this->url('dtladmin/dtlfinancial/revenue/add'));
$form->prepare();
?>
<?php echo $this->form()->openTag($form); ?>
<div class="modal-header">
    <h3 class="modal-title"><i class="fa fa-download"></i> <?php echo $this->escapeHtml($title); ?></h3>
</div>
<div class="modal-body">
    <?php $revenue = $form->get('revenue'); ?>
    <?php echo $this->formHidden($revenue->get('id')); ?>
    <?php $launch = $revenue->get('launch'); ?>
    <div class="row">
        <div class="col-md-12">
            <div class="form-group form-group-sm">
                <?php echo $this->formLabel($revenue->get('customer')); ?>
                <?php echo $this->formSelect($revenue->get('customer')); ?>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="form-group form-group-sm">
                <?php echo $this->formLabel($launch->get('description')); ?>
                <?php echo $this->formText($launch->get('description')); ?>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group form-group-sm">
                <?php echo $this->formLabel($launch->get('currentAccount')); ?>
                <?php echo $this->formSelect($launch->get('currentAccount')); ?>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group form-group-sm">
                <?php echo $this->formLabel($launch->get('accountingItem')); ?>
                <?php echo $this->formSelect($launch->get('accountingItem')); ?>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group form-group-sm">
                <?php echo $this->formLabel($launch->get('date')); ?>
                <?php echo $this->dtlBaseFormDate($launch->get('date')); ?>
            </div>
        </div>  
        <div class="col-md-6">
            <div class="form-group form-group-sm">
                <?php echo $this->formLabel($launch->get('value')); ?>
                <div class="input-group">
                    <span class="input-group-addon">R$</span>
                    <?php echo $this->formText($launch->get('value')); ?>
                </div>
            </div>
        </div>
    </div>
    <?php echo $this->formHidden($form->get('security')); ?>
</div>
<div class="modal-footer">
    <?php echo $this->formElement($form->get('submit')); ?>
    <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-remove"></i><?php echo $this->translate('Fechar'); ?></button>
</div>
<?php echo $this->form()->closeTag(); ?>