<?php
$title = $this->translate('Nova Marca');
$this->headTitle($title);
$form = $this->form;
$form->prepare();
?>
<h2 class="container-header"><?php echo $this->escapeHtml($title); ?></h2>
<?php echo $this->form()->openTag($form); ?>
<fieldset>
    <?php $vehicleBrand = $form->get('vehicleBrand'); ?>
    <div class="form-group">
        <?php echo $this->formHidden($vehicleBrand->get('id')); ?>
        <div class="row">
            <div class="col-md-4">
                <?php echo $this->formLabel($vehicleBrand->get('name')); ?>
                <?php echo $this->formText($vehicleBrand->get('name')); ?>
            </div>
        </div>
        <?php echo $this->formHidden($form->get('security')); ?>
    </div>
    <div class="btn-group btn-group-sm">  
        <?php echo $this->formElement($form->get('submit')); ?>
        <?php echo $this->formElement($form->get('cancel')); ?>
    </div>
</fieldset>
<?php echo $this->form()->closeTag(); ?>
