<?php
$title = $this->translate('Marcas de Veículos');
$this->headTitle($title);
?>
<div class="panel panel-default">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-6">
                <h2 class="panel-title"><?php echo $this->escapeHtml($title); ?></h2>
            </div>
            <div class="col-md-6">
                <div class="btn-group pull-right">
                    <a class="btn btn-default btn-sm" href="<?php echo $this->url('dtladmin/dtlvehicle/vehicle-brand/add'); ?>"> <i class="glyphicon glyphicon-plus-sign"></i> <?php echo $this->translate('Novo'); ?></a>
                </div> 
            </div>
        </div>
    </div>
    <table class="table table-condensed table-hover">
        <tr>
            <th colspan="10"><?php echo $this->translate('MARCA'); ?></th>
        </tr>
        <?php if (0 == count($this->vehicleBrand)): ?>
            <tr>
                <td colspan="10" class="alert alert-info text-center"><?php echo $this->translate('Nenhum registro encontrado.') ?></td>
            </tr>
        <?php else: ?>
            <?php foreach ($this->vehicleBrand as $vehicleBrand) : ?>
                <tr>
                    <td><?php echo $this->escapeHtml($vehicleBrand->getName()); ?></td>
                    <td>
                        <div class="btn-group btn-group-xs pull-right">
                            <a class="btn btn-default" href="<?php echo $this->url('dtladmin/dtlvehicle/vehicle-brand/edit', array('id' => $vehicleBrand->getId()))
                ?>"><i class="glyphicon glyphicon-edit"></i></a>
                            <a class="btn btn-default" href="<?php echo $this->url('dtladmin/dtlvehicle/vehicle-brand/delete', array('id' => $vehicleBrand->getId()))
                ?>"><i class="glyphicon glyphicon-remove"></i></a>
                        </div>
                    </td>
                </tr>
            <?php endforeach; ?>
        <?php endif; ?>
    </table>
    <div class="panel-footer">
        <?php
        $paginationInfo = $this->placeholder('pagination');
        if (!isset($paginationInfo->route)) {
            $paginationInfo->route = 'dtladmin/dtlvehicle/vehicle-brand';
            $paginationInfo->params = array();
        }
        ?>
        <?php echo $this->paginationControl($this->vehicleBrand, 'Sliding', 'layout/pagination'); ?>
    </div>
</div>