<?php $shopman = $this->shopman; ?>
<div class="modal fade" id="seller_modal_<?php echo $shopman->getId(); ?>" tabindex="-1" role="dialog" aria-labelledby="seller_modal_label" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="seller_modal_label">Lista de Vendedores do Lojista <?php echo $shopman->getPerson()->getName(); ?></h4>
            </div>
            <div class="modal-body">
                <?php if (!count($shopman->getSellers()) > 0): ?>
                    <div class="row">
                        <div class="col-md-12">
                            <?php echo $this->translate('Não há nenhum registro no banco de dados.') ?>
                        </div>
                    </div>
                <?php else: ?>
                    <?php foreach ($shopman->getSellers() as $seller) : ?>
                        <div class="row">
                            <div class="col-md-9">
                                <?php echo $this->escapeHtml($seller->getPerson()->getName()); ?>
                            </div>
                            <div class="col-md-3">
                                <div class="btn-group btn-group-xs pull-right">
                                    <a class="btn btn-default" href="<?php
                                    echo $this->url('dtladmin/dtlseller/view', array('action' => 'view',
                                        'id' => $seller->getId()));
                                    ?>"><i class="glyphicon glyphicon-folder-open"></i></a>
                                    <a class="btn btn-default" href="<?php
                                    echo $this->url('dtladmin/dtlseller/edit', array('action' => 'edit',
                                        'id' => $seller->getId(), 'type' => base64_encode($seller->getPerson()->getType())));
                                    ?>"><i class="glyphicon glyphicon-edit"></i></a>
                                    <a class="btn btn-default" href="<?php
                                    echo $this->url('dtladmin/dtlseller/delete', array('action' => 'delete',
                                        'id' => $seller->getId()));
                                    ?>"><i class="glyphicon glyphicon-remove"></i></a>
                                </div>
                            </div>
                        </div>
                    <?php endforeach; ?>
                <?php endif; ?>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Sair</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->