<table class="table table-condensed table-hover">
    <tr>
        <th colspan="10"><?php echo $this->translate('VERSÃO'); ?></th>
    </tr>
    <?php if (0 == count($this->vehicleVersion)): ?>
        <tr>
            <td colspan="10" class="alert alert-info text-center"><?php echo $this->translate('Nenhum registro encontrado.') ?></td>
        </tr>
    <?php else: ?>
        <?php foreach ($this->vehicleVersion as $vehicleVersion) : ?>
            <tr>
                <td><?php echo $this->escapeHtml($vehicleVersion->getName()); ?></td>
                <td>
                    <div class="btn-group btn-group-xs pull-right">
                        <a class="btn btn-default" href="javascript: vehicleVersionDelete('<?php echo $vehicleVersion->getId();?>','<?php echo $vehicleVersion->getModel()->getId();?>');"><i class="glyphicon glyphicon-remove"></i></a>
                    </div>
                </td>
            </tr>
        <?php endforeach; ?>
    <?php endif; ?>
</table>
