<?php
$title = $this->translate('Nova Coleção');
$this->headTitle($title);
$form = $this->form;
$form->setAttribute('action', $this->url('dtladmin/dtlcollection'));
$form->prepare();
?>
<h2 class="container-header"><i class="glyphicon glyphicon-briefcase"></i> <?php echo $this->escapeHtml($title); ?></h2>
<?php echo $this->form()->openTag($form); ?>
<?php $boss = $form->get('boss'); ?>
<fieldset>
    <legend><?php echo $this->translate('Coleção') ?></legend>
    <?php echo $this->formHidden($boss->get('id')); ?>
    <div class="form-group">
        <div class="row">
            <div class="col-md-4">
                <?php echo $this->formLabel($boss->get('master')->get('name')); ?>
                <?php echo $this->formText($boss->get('master')->get('name')); ?>
                <?php echo $this->formElementErrors($boss->get('master')->get('name')); ?>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <?php echo $this->formCollection($boss->get('slaves')); ?>
            </div>
        </div>
        <?php echo $this->formElement($form->get('submit')); ?>
    </div>
</fieldset>
<?php echo $this->form()->closeTag(); ?>

<div class="panel panel-default">
    <div class="panel-heading">
        <div class="panel-title">Coleções</div>
    </div>
    <div class="panel-body">
        <table class="table table-bordered table-responsive">
            <thead>
            <td>Nome</td>
            <td>Escravos</td>
            </thead>
            <?php foreach ($this->boss as $boss): ?>
                <tbody>
                    <tr>
                        <td><?php echo $boss->getMaster()->getName(); ?></td>
                        <td>
                            <ul>
                                <?php foreach ($boss->getSlaves() as $slave): ?>
                                    <li><?php echo $slave->getName(); ?> <?php echo $slave->getColor(); ?></li>
                                <?php endforeach; ?>
                            </ul>
                        </td>
                    </tr>
                </tbody>
            <?php endforeach; ?>
        </table>
    </div>
</div>
