<?php if ($this->checking): ?>
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"><i class="glyphicon glyphicon-lock"></i> Status da Proposta Nº <?php echo $this->caixaProposal->getId(); ?></h4>
    </div>
    <div class="modal-body">
        <?php
        echo $this->error('<br>A proposta de número <strong>' .
                $this->caixaProposal->getId() .
                '</strong>, não pode ser direcionada a outro banco.<br>' .
                'A proposta ainda está sob análise no banco: <strong>' .
                $this->caixaProposal->getProposal()->getBank()->getName() .
                '</strong>!');
        ?>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
    </div>
<?php else: ?>
    <?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('dtladmin/dtlproposal/caixa-proposal/bank', array('action' => 'bank',
                'id' => $this->caixaProposal->getId())));
    $form->prepare();
    $bankReport = $form->get('bankReport');
    ?>
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"><i class="glyphicon glyphicon-repeat"></i> Migração Bancária da Proposta Nº <?php echo $this->caixaProposal->getId(); ?></h4>
    </div>
    <?php echo $this->form()->openTag($form); ?>
    <div class="modal-body">
        <div class="form-group">
            <div class="row">
                <div class="col-md-6">
                    <?php echo $this->formLabel($bankReport->get('bank')); ?>
                    <?php echo $this->formSelect($bankReport->get('bank')); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <?php echo $this->formLabel($bankReport->get('parcelAmount')); ?>
                    <?php echo $this->formText($bankReport->get('parcelAmount')); ?>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <?php echo $this->formRow($form->get('submit')); ?>
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
    </div>
    <?php echo $this->form()->closeTag(); ?>
<?php endif; ?>