<?php
$caixaProposal = $this->caixaProposal;
$proposal = $caixaProposal->getProposal();
$customer = $proposal->getCustomer();
$title = 'Detalhes da Proposta nº ' . $caixaProposal->getId();
$this->headTitle($title);
?>
<?php $class = ''; ?>
<?php $status = ''; ?>
<?php if ($caixaProposal->getProposal()->getIsChecking()): ?>
    <?php $class = 'panel-info'; ?>
    <?php $status = 'ABERTA'; ?>
<?php elseif ($caixaProposal->getProposal()->getIsCanceled()): ?>
    <?php $class = 'panel-canceled'; ?>
    <?php $status = 'CANCELADA'; ?>
<?php elseif ($caixaProposal->getProposal()->getIsRefused()): ?>
    <?php $class = 'panel-danger'; ?>
    <?php $status = 'RECUSADA'; ?>
<?php elseif ($caixaProposal->getProposal()->getIsAborted()): ?>
    <?php $class = 'panel-warning'; ?>
    <?php $status = 'ABORTADA'; ?>
<?php elseif ($caixaProposal->getProposal()->getIsApproved()): ?>
    <?php $class = 'panel-muted'; ?>
    <?php $status = 'APROVADA'; ?>
<?php elseif ($caixaProposal->getProposal()->getIsIntegrated()): ?>
    <?php $class = 'panel-success'; ?>
    <?php $status = 'INTEGRADA'; ?>
<?php elseif ($caixaProposal->getProposal()->getIsPending()): ?>
    <?php $class = 'panel-primary'; ?>
    <?php $status = 'PENDENTE'; ?>
<?php endif; ?>
<div class="panel <?php echo $class; ?>">
    <div class="panel-heading">
        <div class="row">
            <div class="col-xs-5">
                <div class="panel-title">
                    <i class="glyphicon glyphicon-plus-sign"></i> 
                    Proposta Nº <?php echo str_pad($caixaProposal->getId(), 8, '0', STR_PAD_LEFT); ?>
                </div>
            </div>
            <div class="col-xs-7 hidden-print">
                <div class="btn-group btn-group-sm pull-right">
                    <a class="btn btn-default" data-toggle="tooltip" title="Apagar" href="<?php
                    echo $this->url('dtladmin/dtlproposal/caixa-proposal/delete', array('action' => 'delete',
                        'id' => $caixaProposal->getId()));
                    ?>"><i class="glyphicon glyphicon-remove"></i> Apagar</a>
                    <a class="btn btn-default" data-toggle="tooltip" title="Editar" href="<?php
                    echo $this->url('dtladmin/dtlproposal/caixa-proposal/edit', array(
                        'id' => $caixaProposal->getId()));
                    ?>"><i class="glyphicon glyphicon-edit"></i> Editar</a>
                       <?php if (!$caixaProposal->getProposal()->getIsIntegrated()): ?>
                        <a class="btn btn-default app-tooltip" data-toggle="modal" data-placement="left" title="Status da Proposta" data-target="#proposalStatus<?php echo $caixaProposal->getId(); ?>"
                           href="<?php echo $this->url('dtladmin/dtlproposal/caixa-proposal/status', array('action' => 'status', 'id' => $caixaProposal->getId())); ?>">
                            <i class="glyphicon glyphicon-repeat"></i> Status</a>
                    <?php endif; ?>
                    <a class="btn btn-default app-tooltip" data-toggle="modal" title="Histórico" data-target="#proposalHistory<?php echo $caixaProposal->getId(); ?>"
                       href="<?php echo $this->url('dtladmin/dtlproposal/caixa-proposal/history', array('action' => 'history', 'id' => $caixaProposal->getId())); ?>">
                        <i class="glyphicon glyphicon-time"></i> Histórico</a>
                    <a href="javascript: window.print();" class="btn btn-default">
                        <i class="glyphicon glyphicon-print"></i> 
                        <?php echo $this->translate('Imprimir'); ?>
                    </a>
                    <a class="btn btn-default" data-toggle="tooltip" title="Voltar" href="<?php
                    echo $this->url('dtladmin/dtlproposal/caixa-proposal', array('action' => 'print',
                        'id' => $caixaProposal->getId()));
                    ?>"><i class="glyphicon glyphicon-chevron-left"></i> Voltar</a>

                    <div class="modal" id="proposalHistory<?php echo $caixaProposal->getId(); ?>" tabindex="-1" role="dialog" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content"></div>
                        </div>
                    </div>
                    <div class="modal" id="proposalStatus<?php echo $caixaProposal->getId(); ?>" tabindex="-1" role="dialog" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="panel-body">
        <div class="panel <?php echo $class; ?>">
            <div class="panel-heading">
                <div class="panel-title"><i class=""></i> Dados Básicos da Proposta</div>
            </div>
            <div class="panel-body">
                <dl class="dl-horizontal">
                    <div class="row">
                        <div class="col-xs-6">
                            <dt>Número da Proposta:</dt>
                            <dd><?php echo $caixaProposal->getId(); ?></dd>
                            <dt>Banco:</dt>
                            <dd><?php echo $caixaProposal->getProposal()->getBank()->getName(); ?></dd>
                            <dt>Cidade:</dt>
                            <dd><?php echo $caixaProposal->getProposal()->getCompany()->getAddress()->getCity()->getName(); ?></dd>
                            <dt>Data de Cadastro:</dt>
                            <dd><?php echo $this->date($caixaProposal->getProposal()->getTimestamp()); ?></dd>
                            <dt>Observações:</dt>
                            <dd><?php echo $caixaProposal->getProposal()->getNotes(); ?></dd>
                        </div>
                        <div class="col-xs-6">
                            <dt>Status da Proposta:</dt>
                            <dd><?php echo $status; ?></dd>
                            <dt>Empresa:</dt>
                            <dd><?php echo $caixaProposal->getProposal()->getCompany()->getFancyName(); ?></dd>
                            <dt>Operador:</dt>
                            <dd><?php echo $caixaProposal->getProposal()->getEmployee()->getName(); ?></dd>
                        </div>
                    </div>
                </dl>
            </div>
        </div>
        <div class="panel <?php echo $class; ?>">
            <div class="panel-heading">
                <div class="panel-title"><i class="glyphicon glyphicon-plus-sign"></i> Produtos da Proposta</div>
            </div>
            <?php if (0 == count($caixaProposal->getProducts())): ?>
                <div class="panel-body">
                    <div class="alert alert-info">
                        <?php echo $this->translate('Nenhum registro encontrado.') ?>
                    </div>
                </div>
            <?php else: ?>
                <table class="table table-condensed table-hover">
                    <tr>
                        <th><?php echo $this->translate('PRODUTO'); ?></th>
                    </tr>
                    <?php foreach ($caixaProposal->getProducts() as $product) : ?>
                        <tr>
                            <td><?php echo $product->getProduct()->getName(); ?></td>
                        </tr>
                    <?php endforeach; ?>
                </table>
            <?php endif; ?>
        </div>

        <?php echo $this->partial('dtl-proposal/proposal/view-customer', array('class' => $class, 'customer' => $customer)); ?>
    </div>
</div>
