<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'DtlCurrency\Form\Fieldset\Currency'        => __DIR__ . '/src/DtlCurrency/Form/Fieldset/Currency.php',
  'DtlCurrency\Form\Currency'                 => __DIR__ . '/src/DtlCurrency/Form/Currency.php',
  'DtlCurrency\Factory\Currency'              => __DIR__ . '/src/DtlCurrency/Factory/Currency.php',
  'DtlCurrency\Controller\CurrencyController' => __DIR__ . '/src/DtlCurrency/Controller/CurrencyController.php',
  'DtlCurrency\Entity\Currency'               => __DIR__ . '/src/DtlCurrency/Entity/Currency.php',
  'DtlCurrency\Module'                        => __DIR__ . '/Module.php',
);
