<?php
$shopman = $this->shopman;
$form = $this->form;
$form->prepare();
?>
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="seller_modal_label">Lista de Produtos do Lojista <?php echo $shopman->getPerson()->getName(); ?></h4>
</div>
<div class="modal-body">
    <div class="row">
        <div class="col-md-4">
            <?php echo $this->form()->openTag($form); ?>
            <div class="form-gorup">
                <?php $shopmanProduct = $form->get('shopmanProduct'); ?>
                <?php echo $this->formHidden($shopmanProduct->get('shopman')->setValue($shopman->getId())); ?>
                <div class="row">
                    <div class="col-md-12">
                        <?php echo $this->formLabel($shopmanProduct->get('product')); ?>
                        <?php echo $this->formSelect($shopmanProduct->get('product')); ?>
                    </div>
                </div>
            </div>
            <br/>
            <div class="btn-group">
                <?php echo $this->formElement($form->get('submit')->setAttribute('onclick', 'javascript: shopmanProductAdd();')); ?>
            </div>
            <?php echo $this->form()->closeTag(); ?>
        </div>
        <div class="col-md-8">
            <div class="shopman-product-list"></div>
        </div>
    </div>
    <script type="text/javascript">
        shopmanProductList(<?php echo $shopman->getId(); ?>);
    </script>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Sair</button>
</div>