<div class="panel panel-default">
    <div class="panel-heading">
        <div class="panel-title"><?php echo $this->translate('Lista de Produtos do Lojista'); ?></div>
    </div>
    <table class="table table-condensed table-hover">
        <tr>
            <th colspan="2"><?php echo $this->translate('PRODUTO'); ?></th>
        </tr>
        <?php if (0 == count($this->shopmanProducts)): ?>
            <tr>
                <td colspan="10" class="alert alert-info text-center">
                    <?php echo $this->translate('Nenhum registro encontrado.') ?>
                </td>
            </tr>
        <?php else: ?>
            <?php foreach ($this->shopmanProducts as $product) : ?>
                <tr>
                    <td><?php echo $this->escapeHtml($product->getName()); ?></td>
                    <td>
                        <div class="btn-group btn-group-xs pull-right">
                            <a class="btn btn-default" href="javascript: shopmanProductDelete(<?php echo $this->shopmanId;?>, <?php echo $product->getId();?>);"><i class="glyphicon glyphicon-remove"></i></a>
                        </div>
                    </td>
                </tr>
            <?php endforeach; ?>
        <?php endif; ?>
        </tbody>
    </table>
</div>