<?php
$title = $this->translate('Nova Proposta de Venda de Imóvel');
$this->headTitle($title);
$form = $this->form;
$form->setAttribute('action', $this->url('dtladmin/dtlproposal/realty-proposal/add'));
$form->prepare();
?>
<?php echo $this->form()->openTag($form); ?>
<div class="row">
    <div class="col-md-6">
        <h2 class="container-header">
            <i class="glyphicon glyphicon-home"></i> <?php echo $this->escapeHtml($title); ?>
        </h2>
    </div>
    <div class="col-md-6">
        <div class="btn-group pull-right">
            <input type="submit" class="btn btn-primary" value="Salvar Proposta" />
        </div>
    </div>
</div>
<div class="clearfix"></div><br/>
<?php $realtyProposal = $form->get('realtyProposal'); ?>
<?php $proposal = $realtyProposal->get('proposal'); ?>
<fieldset>
    <div class="panel-group">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Dados Básicos'); ?></h3>
            </div>
            <div class="panel-body">
                <div class="form-group">
                    <div class="row">
                        <div class="col-md-6">
                            <?php echo $this->formLabel($proposal->get('company')); ?>
                            <?php echo $this->formSelect($proposal->get('company')); ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <?php if ($this->employee()): ?>
                                <?php echo $this->formSelect($proposal->get('employee')->setValue($this->employee()->getId())->setAttribute('class', 'hide')); ?>
                            <?php else: ?>
                                <?php echo $this->formLabel($proposal->get('employee')); ?>
                                <?php echo $this->formSelect($proposal->get('employee')); ?>
                            <?php endif; ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <?php echo $this->formLabel($proposal->get('bank')); ?>
                            <?php echo $this->formSelect($proposal->get('bank')); ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <?php echo $this->formLabel($realtyProposal->get('realtor')); ?>
                            <?php echo $this->formSelect($realtyProposal->get('realtor')); ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <?php echo $this->formLabel($realtyProposal->get('product')); ?>
                            <?php echo $this->formSelect($realtyProposal->get('product')); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Dados do Imóvel'); ?></h3>
            </div>
            <div class="panel-body">
                <?php $realty = $realtyProposal->get('realty') ?>
                <?php echo $this->realtyProposalForm($realty); ?>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Vendedores'); ?></h3>
            </div>
            <div class="panel-body">
                <?php $dealers = $realtyProposal->get('dealers'); ?>
                <?php echo $this->dealerForm($dealers, $this->post); ?>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Compradores'); ?></h3>
            </div>
            <div class="panel-body">
                <legend><h3>Comprador</h3></legend>
                <?php $customer = $proposal->get('customer'); ?>
                <?php echo $this->customerForm($customer, $this->post, true); ?>
                <br/>
                <?php
                echo $this->partial('dtl-proposal/proposal/customercollectionform', array(
                    'customers' => $realtyProposal->get('customers'),
                    'params' => $this->post['preProposal'],
                    'isLoan' => true
                ));
                ?>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Contas do Cliente'); ?></h3>
            </div>
            <div class="panel-body">
                <?php $customerBankAccount = new DtlCustomer\Form\Fieldset\CustomerBankAccount($this->entityManager, 0); ?>
                <?php $customerBankAccount->remove('customer'); ?>
                <?php echo $this->customerBankAccountForm($customerBankAccount); ?>
            </div>
        </div>
    </div>
    <br><input type="submit" class="btn btn-primary" value="Salvar Proposta" />
</fieldset>
<?php echo $this->form()->closeTag(); ?>
<script type="text/javascript">
    function setRealtyProposalTotalValue(value) {
        $('#realtyProposalTotalValue').val(value);
    }
</script>