<?php
$title = $this->translate('Arquivos');
$this->headTitle($title);
?>

<div class="panel panel-default">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-6">
                <h2 class="panel-title"><?php echo $this->escapeHtml($title); ?> </h2>
            </div>
            <div class="col-md-6">
                <div class="btn-group btn-group-sm pull-right">
                    <a class="btn btn-default" href="<?php echo $this->url('dtladmin/file/add'); ?>"> <i class="glyphicon glyphicon-plus-sign"></i> <?php echo $this->translate('Novo'); ?></a>
                </div> 
            </div>
        </div>
    </div>
    <table class="table table-condensed table-hover">
        <tr>
            <th class="col-md-1"><?php echo $this->translate('Nº'); ?></th>
            <th class=""><?php echo $this->translate('BANCO'); ?></th>
            <th class="col-md-1"><?php echo $this->translate('TAXA'); ?></th>
            <th class="col-md-1"><?php echo $this->translate('RETORNO'); ?></th>
            <th class="col-md-2" colspan="10"><?php echo $this->translate('DIRETO'); ?></th>
        </tr>
        <?php if (0 == count($this->file)): ?>
            <tr>
                <td colspan="10" class="alert alert-info text-center"><?php echo $this->translate('Nenhum registro encontrado.') ?></td>
            </tr>
        <?php else: ?>
            <?php foreach ($this->file as $file) : ?>
                <tr>
                    <td><?php echo $this->escapeHtml($file->getFileCode()); ?></td>
                    <td><?php echo $this->escapeHtml($file->getFileName()); ?></td>
                    <td><?php echo $this->escapeHtml($file->getFileTax()); ?> %</td>
                    <td><?php echo $this->escapeHtml($file->getFileReturn()); ?> %</td>
                    <td><?php echo ($file->getFileDirect()) ? '<span class="badge">SIM</span>' : '<span class="badge">NÃO</span>'; ?></td>
                    <td>
                        <div class="btn-group btn-group-xs pull-right">
                            <a class="btn btn-default" href="<?php echo $this->url('dtladmin/file/edit', array('id' => $file->getFileId()))
                ?>"><i class="glyphicon glyphicon-edit"></i></a>
                            <a class="btn btn-default" href="<?php echo $this->url('dtladmin/file/delete', array('id' => $file->getFileId()))
                ?>"><i class="glyphicon glyphicon-remove"></i></a>
                        </div>
                    </td>
                </tr>
            <?php endforeach; ?>
        <?php endif; ?>
    </table>
    <div class="panel-footer">
        <?php
        $paginationInfo = $this->placeholder('pagination');
        if (!isset($paginationInfo->route)) {
            $paginationInfo->route = 'dtladmin/file';
            $paginationInfo->params = array();
        }
        ?>
        <?php echo $this->paginationControl($this->file, 'Sliding', 'layout/pagination'); ?>
    </div>
</div>