<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'DtlDocumentType\Form\Fieldset\DocumentType'        => __DIR__ . '/src/DtlDocumentType/Form/Fieldset/DocumentType.php',
  'DtlDocumentType\Form\DocumentType'                 => __DIR__ . '/src/DtlDocumentType/Form/DocumentType.php',
  'DtlDocumentType\Factory\DocumentType'              => __DIR__ . '/src/DtlDocumentType/Factory/DocumentType.php',
  'DtlDocumentType\Controller\DocumentTypeController' => __DIR__ . '/src/DtlDocumentType/Controller/DocumentTypeController.php',
  'DtlDocumentType\Entity\DocumentType'               => __DIR__ . '/src/DtlDocumentType/Entity/DocumentType.php',
  'DtlDocumentType\Module'                            => __DIR__ . '/Module.php',
);
