<?php
$title = $this->translate('Apagar Ramo de Atividade');
$this->headTitle($title);
$url = $this->url('dtladmin/dtlbusiness/delete', array('id' => $this->id));

?>
<div class="panel panel-default">
    <div class="panel-heading">
        <div class="panel-title"><i class="glyphicon glyphicon-globe"></i> <?php echo $this->escapeHtml($title); ?></div>
    </div>
    <div class="panel-body">
        <blockquote>
            <p><?php echo $this->translate('Você tem certeza de que deseja apagar ') ?>
                '<?php echo $this->escapeHtml($this->business->getName()); ?>'?
            </p>
        </blockquote>
        <form action="<?php echo $url; ?>" method="post">
            <div>
                <input type="hidden" name="id" value="<?php echo $this->business->getId(); ?>" />
                <div class="btn-group">
                    <input  type="submit" name="del" value="Sim" class="btn btn-primary" />
                    <input type="submit" name="del" value="Não" class="btn btn-default" />
                </div>
            </div>
        </form>
    </div>
</div>
