<?php
$title = $this->translate('Clientes');
$this->headTitle($title);
?>
<div class="row">
    <div class="col-md-2">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-md-12">
                        <div class="panel-title"><i class="glyphicon glyphicon-search"></i> <?php echo $this->escapeHtml('Filtrar'); ?></div>
                    </div>
                </div>
            </div>
            <div class="panel-body">
                <?php echo $this->partial('dtl-customer/customer/search'); ?>
            </div>
        </div>
    </div>
    <div class="col-md-10">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-md-6">
                        <div class="panel-title"><i class="glyphicon glyphicon-user"></i> <?php echo $this->escapeHtml($title); ?></div>
                    </div>
                    <div class="col-md-6 text-right">
                        <div class="btn-group">
                            <a class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown" href="#"> <i class="glyphicon glyphicon-plus-sign"></i> <?php echo $this->translate('Novo'); ?> &nbsp; <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="<?php echo $this->url('dtladmin/dtlcustomer/add', array('type' => base64_encode(0)));
                ?>"><i class="glyphicon glyphicon-user"></i> Pessoa Física</a></li>
                                <li><a href="<?php echo $this->url('dtladmin/dtlcustomer/add', array('type' => base64_encode(1)));
                ?>"><i class="glyphicon glyphicon-tower"></i> Pessoa Jurídica</a></li>
                            </ul>
                        </div>
                        <a data-toggle="tooltip" title="Exportar para Excel" class="btn btn-default btn-sm" href="<?php echo $this->url('dtladmin/dtlcustomer/exportCsv'); ?>"><i class="fa fa-download"></i></a>
                    </div>
                </div>
            </div>
            <table class="table table-condensed table-hover">
                <tr>
                    <th class="col-lg-1"><?php echo $this->translate('CÓD'); ?></th>
                    <th class=""><?php echo $this->translate('CLIENTE'); ?></th>
                    <th class="col-md-2"><?php echo $this->translate('CPF/CNPJ'); ?></th>
                    <th class="col-md-2"><?php echo $this->translate('TELEFONE'); ?></th>
                    <th class="col-md-3"><?php echo $this->translate(''); ?></th>
                </tr>
                <?php if (0 == count($this->customer)): ?>
                    <tr>
                        <td colspan="10" class="alert alert-info text-center"><?php echo $this->translate('Não há nenhum registro no banco de dados.') ?></td>
                    </tr>
                <?php else: ?>
                    <?php foreach ($this->customer as $customer) : ?>
                        <tr>
                            <td><?php echo str_pad($customer->getId(), 8, '0', STR_PAD_LEFT); ?></td>
                            <td><?php echo $this->escapeHtml($customer->getPerson()->getName()); ?></td>
                            <?php if ($customer->getPerson()->getType() == 1): ?>
                                <td><?php echo $this->cnpj($customer->getPerson()->getLegal()->getCnpj()); ?></td>
                            <?php else: ?>
                                <td><?php echo $this->cpf($customer->getPerson()->getIndividual()->getCpf()); ?></td>
                            <?php endif; ?>
                            <td><?php echo $this->escapeHtml($this->phone($customer->getPerson()->getContact()->getPhone())); ?></td>
                            <td>
                                <div class="btn-group btn-group-xs pull-right">
                                    <a class="btn btn-default" data-toggle="tooltip" title="Ver Detalhes" href="<?php
                                    echo $this->url('dtladmin/dtlcustomer/view', array('action' => 'view',
                                        'id' => $customer->getId()));
                                    ?>"><i class="glyphicon glyphicon-folder-open"></i></a>
                                    <a class="btn btn-default" data-toggle="tooltip" title="Apagar" href="<?php
                                    echo $this->url('dtladmin/dtlcustomer/delete', array('action' => 'delete',
                                        'id' => $customer->getId()));
                                    ?>"><i class="glyphicon glyphicon-remove"></i></a>
                                    <a class="btn btn-default" data-toggle="tooltip" title="Editar" href="<?php
                                    echo $this->url('dtladmin/dtlcustomer/edit', array('action' => 'edit',
                                        'id' => $customer->getId(), 'type' => base64_encode($customer->getPerson()->getType())));
                                    ?>"><i class="glyphicon glyphicon-edit"></i></a>
                                    <a class="btn btn-default" data-toggle="tooltip" title="Patrimônio do Cliente" href="<?php
                                    echo $this->url('dtladmin/dtlcustomer/customer-patrimony/add', array('action' => 'add',
                                        'id' => $customer->getId()));
                                    ?>"><i class="glyphicon glyphicon-tower"></i></a>
                                    <a class="btn btn-default" data-toggle="tooltip" title="Veículos do Cliente" href="<?php
                                    echo $this->url('dtladmin/dtlcustomer/customer-vehicle/add', array('action' => 'add',
                                        'id' => $customer->getId()));
                                    ?>"><i class="glyphicon glyphicon-road"></i></a>
                                    <a class="btn btn-default" data-toggle="tooltip" title="Contas do Cliente" href="<?php
                                    echo $this->url('dtladmin/dtlcustomer/customer-bank-account/add', array('action' => 'add',
                                        'id' => $customer->getId()));
                                    ?>"><i class="glyphicon glyphicon-usd"></i></a>
                                    <a class="btn btn-default" data-toggle="tooltip" title="Referências" href="<?php
                                    echo $this->url('dtladmin/dtlcustomer/customer-reference/add', array('action' => 'add',
                                        'id' => $customer->getId()));
                                    ?>"><i class="glyphicon glyphicon-thumbs-up"></i></a>
                                </div>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                <?php endif; ?>
            </table>
            <div class="panel-footer">
                <?php
                $paginationInfo = $this->placeholder('pagination');
                if (!isset($paginationInfo->route)) {
                    $paginationInfo->route = 'dtladmin/dtlcustomer';
                    $paginationInfo->params = array();
                }
                ?>
                <?php echo $this->paginationControl($this->customer, 'Sliding', 'layout/pagination'); ?>
            </div>
        </div>
    </div>
</div>