<?php
$customer = $this->customer;
$person = $customer->getPerson();
$address = $person->getAddress();
$contact = $person->getContact();
$individual = $person->getIndividual();
$legal = $person->getLegal();
$title = 'Detalhes de ' . $person->getName();
$this->headTitle($title);
?>
<div class="row">
    <div class="col-md-8">
        <blockquote>
            <p class="text-danger"><?php echo $person->getName(); ?></small>
        </blockquote>
    </div>
    <div class="col-md-4">
        <div class="btn-group pull-right">
            <div class="btn-group">
                <a class="btn btn-default dropdown-toggle" data-toggle="dropdown" href="#"> <i class="glyphicon glyphicon-plus-sign"></i> <?php echo $this->translate('Novo'); ?> &nbsp; <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="<?php
                        echo $this->url('dtladmin/dtlcustomer/add', array('action' => 'add',
                            'type' => base64_encode(0)));
                        ?>"><i class="glyphicon glyphicon-user"></i> Pessoa Física</a></li>
                    <li><a href="<?php
                        echo $this->url('dtladmin/dtlcustomer/add', array('action' => 'add',
                            'type' => base64_encode(1)));
                        ?>"><i class="glyphicon glyphicon-tower"></i> Pessoa Jurídica</a></li>
                </ul>
            </div>
            <a class="btn btn-default" href="<?php
            echo $this->url('dtladmin/dtlcustomer/edit', array('action' => 'edit',
                'id' => $customer->getId(), 'type' => base64_encode($customer->getPerson()->getType())));
            ?>"><i class="glyphicon glyphicon-edit"></i> <?php echo $this->translate('Editar'); ?></a>
            <a class="btn btn-default" href="<?php
            echo $this->url('dtladmin/dtlcustomer/delete', array('action' => 'delete',
                'id' => $customer->getId()));
            ?>"><i class="glyphicon glyphicon-remove"></i> <?php echo $this->translate('Apagar'); ?></a>
            <a class="btn btn-default" href="<?php echo $this->url('dtladmin/dtlcustomer'); ?>"><i class="glyphicon glyphicon-chevron-left"></i> <?php echo $this->translate('Voltar'); ?></a>
        </div>
    </div>
</div>
<dl class="dl-horizontal">
    <?php if ($person->getType()): ?>
        <legend>Dados da Pessoa Jurídica</legend>
        <dt>CNPJ:</dt>
        <dd><?php echo $this->cnpj($legal->getCnpj()); ?>&nbsp;</dd>
        <dt>Inscrição Estadual:</dt>
        <dd><?php echo $legal->getSubscription(); ?>&nbsp;</dd>
        <dt>Representante:</dt>
        <dd><?php echo $legal->getRepresentativeName(); ?>&nbsp;</dd>
        <dt>Telefone do Rep.:</dt>
        <dd><?php echo $this->phone($legal->getRepresentativePhone()); ?>&nbsp;</dd>
    <?php else: ?>
        <legend>Dados da Pessoa Física</legend>
        <div class="row">
            <div class="col-md-6">
                <dt>CPF:</dt>
                <dd><?php echo $this->cpf($individual->getCpf()); ?>&nbsp;</dd>
                <dt>RG:</dt>
                <dd><?php echo $individual->getRg(); ?>&nbsp;</dd>
                <dt>Sexo:</dt>
                <dd><?php echo $this->gender($individual->getGender()); ?>&nbsp;</dd>
                <dt>Natural de:</dt>
                <dd><?php echo $individual->getBirthPlace(); ?>/<?php echo $individual->getBirthUf(); ?>&nbsp;</dd>
                <dt>Nome da Mãe:</dt>
                <dd><?php echo $individual->getMother(); ?>&nbsp;</dd>
            </div>
            <div class="col-md-6">
                <dt>Data de Nascimento:</dt>
                <dd><?php echo $this->birthday($individual->getBirthDay(), $individual->getBirthMonth(), $individual->getBirthYear()); ?></dd>
                <dt>Órgão Expedidor:</dt>
                <dd><?php echo $individual->getRgOrgan(); ?> / <?php echo $individual->getRgUf(); ?></dd>
                <dt>Data de Expedição:</dt>
                <dd><?php echo $individual->getRgDate(); ?>&nbsp;</dd>
                <dt>Nacionalidade:</dt>
                <dd><?php echo $individual->getNationality(); ?>&nbsp;</dd>
                <dt>Nome do Pai:</dt>
                <dd><?php echo $individual->getFather(); ?>&nbsp;</dd>
            </div>
        </div>
    <?php endif; ?>

    <legend>Dados de Contato</legend>
    <div class="row">
        <div class="col-md-6">
            <dt>Endereço:</dt>
            <dd><?php echo $address->getName(); ?>, nº <?php echo $address->getNumber(); ?></dd>
            <dt>Complemento:</dt>
            <dd><?php echo $address->getComplement(); ?>&nbsp;</dd>
            <dt>Bairro:</dt>
            <dd><?php echo $address->getQuarter(); ?>&nbsp;</dd>
            <dt>CEP:</dt>
            <dd><?php echo $this->cep($address->getPostalCode()); ?>&nbsp;</dd>
            <dt>Cidade:</dt>
            <dd><?php echo ($address->getCity()) ? $address->getCity()->getName() : ''; ?>&nbsp;</dd>
            <dt>Estado:</dt>
            <dd><?php echo ($address->getState()) ? $address->getState()->getName() : ''; ?>&nbsp;</dd>
            <dt>País:</dt>
            <dd><?php echo ($address->getCountry()) ? $address->getCountry()->getName() : ''; ?>&nbsp;</dd>
        </div>
        <div class="col-md-6">
            <dt>Email:</dt>
            <dd><?php echo $contact->getEmail(); ?>&nbsp;</dd>
            <dt>Website:</dt>
            <dd><?php echo $contact->getUrl(); ?>&nbsp;</dd>
            <dt>Telefone:</dt>
            <dd><?php echo $this->phone($contact->getPhone()); ?>&nbsp;</dd>
            <dt>Celular:</dt>
            <dd><?php echo $this->phone($contact->getCell()); ?>&nbsp;</dd>
            <dt>FAX:</dt>
            <dd><?php echo $this->phone($contact->getFax()); ?>&nbsp;</dd>
        </div>
    </div>

    <?php if (!$customer->getPerson()->getType()  && ($customer->getPerson()->getIndividual()->getProfessional())): ?>
        <legend>Dados Profissionais</legend>
        <div class="row">
            <div class="col-md-6">
                <dt>Nome da Empresa:</dt>
                <dd><?php echo $customer->getPerson()->getIndividual()->getProfessional()->getCompanyName(); ?></dd>
                <dt>Endereço:</dt>
                <dd><?php echo $customer->getPerson()->getIndividual()->getProfessional()->getAddress()->getName(); ?>, nº <?php echo $customer->getPerson()->getAddress()->getNumber(); ?></dd>
                <dt>Complemento:</dt>
                <dd><?php echo $customer->getPerson()->getIndividual()->getProfessional()->getAddress()->getComplement(); ?>&nbsp;</dd>
                <dt>Bairro:</dt>
                <dd><?php echo $customer->getPerson()->getIndividual()->getProfessional()->getAddress()->getQuarter(); ?>&nbsp;</dd>
                <dt>CEP:</dt>
                <dd><?php echo $this->cep($customer->getPerson()->getIndividual()->getProfessional()->getAddress()->getPostalCode()); ?>&nbsp;</dd>
                <dt>Cidade:</dt>
                <dd><?php echo ($customer->getPerson()->getIndividual()->getProfessional()->getAddress()->getCity()) ? $customer->getPerson()->getIndividual()->getProfessional()->getAddress()->getCity()->getName() : ''; ?>&nbsp;</dd>
                <dt>Estado:</dt>
                <dd><?php echo ($customer->getPerson()->getIndividual()->getProfessional()->getAddress()->getState()) ? $customer->getPerson()->getIndividual()->getProfessional()->getAddress()->getState()->getName(): ''; ?>&nbsp;</dd>
                <dt>País:</dt>
                <dd><?php echo ($customer->getPerson()->getIndividual()->getProfessional()->getAddress()->getCountry()) ? $customer->getPerson()->getIndividual()->getProfessional()->getAddress()->getCountry()->getName() : ''; ?>&nbsp;</dd>
                <dt>Data de Admissão:</dt>
                <dd><?php echo $customer->getPerson()->getIndividual()->getProfessional()->getInDate(); ?></dd>
                <dt>Cargo:</dt>
                <dd><?php echo ($customer->getPerson()->getIndividual()->getProfessional()->getOffice()) ? $customer->getPerson()->getIndividual()->getProfessional()->getOffice()->getName() : ''; ?></dd>
                <dt>Salário:</dt>
                <dd><?php echo $this->currency($customer->getPerson()->getIndividual()->getProfessional()->getSalary()); ?></dd>
            </div>
            <div class="col-md-6">
                <dt>CNPJ:</dt>
                <dd><?php echo $this->cnpj($customer->getPerson()->getIndividual()->getProfessional()->getCompanyCnpj()); ?>&nbsp;</dd>
                <dt>Email:</dt>
                <dd><?php echo $customer->getPerson()->getIndividual()->getProfessional()->getContact()->getEmail(); ?>&nbsp;</dd>
                <dt>Website:</dt>
                <dd><?php echo $customer->getPerson()->getIndividual()->getProfessional()->getContact()->getUrl(); ?>&nbsp;</dd>
                <dt>Telefone:</dt>
                <dd><?php echo $this->phone($customer->getPerson()->getIndividual()->getProfessional()->getContact()->getPhone()); ?>&nbsp;</dd>
                <dt>Celular:</dt>
                <dd><?php echo $this->phone($customer->getPerson()->getIndividual()->getProfessional()->getContact()->getCell()); ?>&nbsp;</dd>
                <dt>FAX:</dt>
                <dd><?php echo $this->phone($customer->getPerson()->getIndividual()->getProfessional()->getContact()->getFax()); ?>&nbsp;</dd>
                <dt>Outra Renda:</dt>
                <dd><?php echo $this->currency($customer->getPerson()->getIndividual()->getProfessional()->getOtherRevenue()); ?>&nbsp;</dd>
                <dt>Tipo de Residência:</dt>
                <dd><?php echo $customer->getResidenceType(); ?></dd>
                <dt>Tempo na Residência:</dt>
                <dd><?php echo $customer->getResidenceTime(); ?></dd>
                <dt>Observações:</dt>
                <dd><?php echo $customer->getPerson()->getIndividual()->getProfessional()->getNotes(); ?>&nbsp;</dd>
            </div>
        </div>
    <?php endif; ?>
    <br/>
    <?php if (count($customer->getAccounts()) > 0): ?>
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="panel-title"><i class="glyphicon glyphicon-usd"></i> Contas Bancárias do Cliente</div>
            </div>
            <table class="table table-condensed table-hover">
                <tr>
                    <th class=""><?php echo $this->translate('TIPO DA CONTA'); ?></th>
                    <th class=""><?php echo $this->translate('BANCO'); ?></th>
                    <th class=""><?php echo $this->translate('AGÊNCIA'); ?></th>
                    <th class=""><?php echo $this->translate('CONTA'); ?></th>
                    <th class=""><?php echo $this->translate('CLIENTE DESDE'); ?></th>
                </tr>
                <?php foreach ($customer->getAccounts() as $customerBankAccount) : ?>
                    <tr>
                        <td><?php echo $this->escapeHtml($customerBankAccount->getType()); ?></td>
                        <td><?php echo $this->escapeHtml($customerBankAccount->getBank()); ?></td>
                        <td><?php echo $this->escapeHtml($customerBankAccount->getAgency()); ?></td>
                        <td><?php echo $this->escapeHtml($customerBankAccount->getAccount()); ?></td>
                        <td><?php echo $this->escapeHtml($customerBankAccount->getSince()); ?></td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>
    <?php endif; ?>
    <br/>
    <?php if (count($customer->getPatrimonies()) > 0): ?>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h1 class="panel-title"><i class="fa fa-building-o"></i> Patrimônio do Cliente</h1>
            </div>
            <table class="table table-condensed table-hover">
                <tr>
                    <th class=""><?php echo $this->translate('PATRIMÔNIO'); ?></th>
                    <th class=""><?php echo $this->translate('VALOR'); ?></th>
                </tr>
                <?php foreach ($customer->getPatrimonies() as $customerPatrimony) : ?>
                    <tr>
                        <td><?php echo $this->escapeHtml($customerPatrimony->getName()); ?></td>
                        <td><?php echo $this->currency($customerPatrimony->getValue()); ?></td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>
    <?php endif; ?>
    <br/>
    <?php if (count($customer->getReferences()) > 0): ?>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h1 class="panel-title"><i class="glyphicon glyphicon-thumbs-up"></i> Referências do Cliente</h1>
            </div>
            <table class="table table-condensed table-hover">
                <tr>
                    <th class=""><?php echo $this->translate('TIPO'); ?></th>
                    <th class=""><?php echo $this->translate('REFERÊNCIA'); ?></th>
                    <th class=""><?php echo $this->translate('TELEFONE'); ?></th>
                </tr>
                <?php foreach ($customer->getReferences() as $customerReference) : ?>
                    <tr>
                        <td><?php echo $this->escapeHtml($customerReference->getType()); ?></td>
                        <td><?php echo $this->escapeHtml($customerReference->getName()); ?></td>
                        <td><?php echo $this->phone($customerReference->getPhone()); ?></td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>
    <?php endif; ?>
    <br/>
    <?php if (count($customer->getVehicles()) > 0): ?>
        <div class='panel panel-default'>
            <div class="panel-heading">
                <h1 class="panel-title"><i class="fa fa-truck"></i> Veículos do Cliente</h1>
            </div>
            <table class="table">
                <tr>
                    <th class=""><?php echo $this->translate('MARCA'); ?></th>
                    <th class=""><?php echo $this->translate('MODELO'); ?></th>
                    <th class=""><?php echo $this->translate('VERSÃO'); ?></th>
                    <th class=""><?php echo $this->translate('ANO/MODELO'); ?></th>
                    <th class=""><?php echo $this->translate('PLACA'); ?></th>
                    <th class=""><?php echo $this->translate('COR'); ?></th>
                    <th class=""><?php echo $this->translate('VALOR'); ?></th>
                </tr>
                <?php foreach ($customer->getVehicles() as $customerVehicle) : ?>
                    <tr>
                        <td><?php echo $this->escapeHtml($customerVehicle->getBrand()->getName()); ?></td>
                        <td><?php echo $this->escapeHtml($customerVehicle->getModel()->getName()); ?></td>
                        <td><?php echo $this->escapeHtml($customerVehicle->getVersion()->getName()); ?></td>
                        <td>
                            <?php echo $customerVehicle->getYear(); ?>
                            <?php echo ($customerVehicle->getYearModel()) ? " / " . $customerVehicle->getYearModel() : ""; ?>
                        </td>
                        <td><?php echo $this->escapeHtml($customerVehicle->getPlate()); ?></td>
                        <td><?php echo $this->escapeHtml($customerVehicle->getColor()); ?></td>
                        <td><?php echo $this->currency($customerVehicle->getValue()); ?></td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>
    <?php endif; ?>
</dl>