<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'DtlRealtor\Form\Fieldset\Realtor'        => __DIR__ . '/src/DtlRealtor/Form/Fieldset/Realtor.php',
  'DtlRealtor\Form\Realtor'                 => __DIR__ . '/src/DtlRealtor/Form/Realtor.php',
  'DtlRealtor\Factory\Realtor'              => __DIR__ . '/src/DtlRealtor/Factory/Realtor.php',
  'DtlRealtor\Controller\RealtorController' => __DIR__ . '/src/DtlRealtor/Controller/RealtorController.php',
  'DtlRealtor\Entity\Repository\Realtor'    => __DIR__ . '/src/DtlRealtor/Entity/Repository/Realtor.php',
  'DtlRealtor\Entity\Realtor'               => __DIR__ . '/src/DtlRealtor/Entity/Realtor.php',
  'DtlRealtor\Module'                       => __DIR__ . '/Module.php',
);
