<?php
$title = $this->translate('Novo Corretor de Imóveis');
$this->headTitle($title);
$form = $this->form;
$form->setAttribute('action', $this->url('dtladmin/dtlrealtor/add', array('type' => $this->personType)));
$form->prepare();
?>
<h2 class="container-header"><i class="glyphicon glyphicon-home"></i> <?php echo $this->escapeHtml($title); ?></h2>
<?php echo $this->form()->openTag($form); ?>
<?php $realtor = $form->get('realtor'); ?>
<fieldset>
    <?php $person = $realtor->get('person'); ?>
    <?php echo $this->personForm($person); ?>

    <?php if ($this->personType == base64_encode(1)): ?>
        <?php $legal = $person->get('legal'); ?>
        <?php echo $this->legalForm($legal); ?>
    <?php elseif ($this->personType == base64_encode(0)): ?>
        <?php $individual = $person->get('individual'); ?>
        <?php echo $this->individualForm($individual); ?>
    <?php endif; ?>
    <div class="row">
        <div class="col-md-2">
            <?php echo $this->formLabel($realtor->get('commission')); ?>
            <div class="input-group">
                <?php echo $this->formText($realtor->get('commission')); ?>
                <span class="input-group-addon">%</span>
            </div>
        </div>
        <div class="col-md-2">
            <?php echo $this->formLabel($realtor->get('fixedCommission')); ?>
            <div class="input-group">
                <span class="input-group-addon">R$</span>
                <?php echo $this->formText($realtor->get('fixedCommission')); ?>
            </div>
        </div>
        <div class="col-md-2">
            <?php echo $this->formLabel($realtor->get('bonus')); ?>
            <div class="input-group">
                <span class="input-group-addon">R$</span>
                <?php echo $this->formText($realtor->get('bonus')); ?>
            </div>
        </div>
    </div>
    <br>
    <?php echo $this->formRow($form->get('security')); ?>
    <div class="btn-group">
        <?php echo $this->formSubmit($form->get('submit')); ?>
        <?php echo $this->formRow($form->get('cancel')); ?>
    </div>
</fieldset>
<?php echo $this->form()->closeTag(); ?>
