<?php
$title = $this->translate('Corretores de Imóveis');
$this->headTitle($title);
?>
<div class="panel panel-default">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-6">
                <div class="panel-title"><i class="glyphicon glyphicon-home"></i> <?php echo $this->escapeHtml($title); ?></div>
            </div>
            <div class="col-md-6">
                <div class="btn-group pull-right">
                    <a class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown" href="#"> <i class="glyphicon glyphicon-plus-sign"></i> <?php echo $this->translate('Novo'); ?> &nbsp; <span class="caret"></span></a>
                    <ul class="dropdown-menu pull-right">
                        <li><a href="<?php echo $this->url('dtladmin/dtlrealtor/add', array('type' => base64_encode(0)));
?>"><i class="glyphicon glyphicon-user"></i> Pessoa Física</a></li>
                        <li><a href="<?php echo $this->url('dtladmin/dtlrealtor/add', array('type' => base64_encode(1)));
?>"><i class="glyphicon glyphicon-tower"></i> Pessoa Jurídica</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <table class="table table-condensed table-hover">
        <tr>
            <th class="col-md-1"><?php echo $this->translate('CÓD'); ?></th>
            <th class=""><?php echo $this->translate('CORRETOR'); ?></th>
            <th class=""><?php echo $this->translate('CIDADE'); ?></th>
            <th class="col-md-2"><?php echo $this->translate('TELEFONE'); ?></th>
            <th class="col-md-2"><?php echo $this->translate('CELULAR'); ?></th>
            <th class="col-md-2"><?php echo $this->translate(''); ?></th>
        </tr>
        <?php if (0 == count($this->realtor)): ?>
            <tr>
                <td colspan="10" class="alert alert-info text-center"><?php echo $this->translate('Não há nenhum registro no banco de dados.') ?></td>
            </tr>
        <?php else: ?>
            <?php foreach ($this->realtor as $realtor) : ?>
                <tr>
                    <td><?php echo str_pad($realtor->getId(), 8, '0', STR_PAD_LEFT); ?></td>
                    <td><?php echo $this->escapeHtml($realtor->getPerson()->getName()); ?></td>
                    <td><?php echo $this->escapeHtml($realtor->getPerson()->getAddress()->getCityName()); ?></td>
                    <td><?php echo $this->escapeHtml($this->phone($realtor->getPerson()->getContact()->getPhone())); ?></td>
                    <td><?php echo $this->escapeHtml($this->phone($realtor->getPerson()->getContact()->getCell())); ?></td>
                    <td>
                        <div class="btn-group btn-group-xs pull-right">
                            <a class="btn btn-default" data-toggle="tooltip" title="Ver Detalhes" href="<?php
                            echo $this->url('dtladmin/dtlrealtor/view', array('action' => 'view',
                                'id' => $realtor->getId()));
                            ?>"><i class="glyphicon glyphicon-folder-open"></i></a>
                            <a class="btn btn-default" data-toggle="tooltip" title="Editar" href="<?php
                            echo $this->url('dtladmin/dtlrealtor/edit', array('action' => 'edit',
                                'id' => $realtor->getId(), 'type' => base64_encode($realtor->getPerson()->getType())));
                            ?>"><i class="glyphicon glyphicon-edit"></i></a>
                            <a class="btn btn-default" data-toggle="tooltip" title="Apagar" href="<?php
                            echo $this->url('dtladmin/dtlrealtor/delete', array('action' => 'delete',
                                'id' => $realtor->getId()));
                            ?>"><i class="glyphicon glyphicon-remove"></i></a>
                        </div>
                    </td>
                </tr>
            <?php endforeach; ?>
        <?php endif; ?>
    </table>
    <div class="panel-footer">
        <?php
        $paginationInfo = $this->placeholder('pagination');
        if (!isset($paginationInfo->route)) {
            $paginationInfo->route = 'dtladmin/dtlrealtor';
            $paginationInfo->params = array();
        }
        ?>
        <?php echo $this->paginationControl($this->realtor, 'Sliding', 'layout/pagination'); ?>
    </div>
</div>