<?php $proposalId = $this->vehicleProposal->getProposal()->getId();?>
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title"><i class="glyphicon glyphicon-time"></i> Histórico da Proposta Nº <?php echo str_pad($this->vehicleProposal->getId(), 8, '0', STR_PAD_LEFT); ?></h4>
</div>
<div class="modal-body">
    <?php if (count($this->vehicleProposal->getProposal()->getLogs()) > 0): ?>
        <table class="table table-condensed table-hover">
            <thead>
                <tr>
                    <th>DATA</th>
                    <th>BANCO</th>
                    <th>MENSAGEM</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach (array_reverse($this->vehicleProposal->getProposal()->getLogs()->toArray()) as $log): ?>
                    <tr>
                        <td><?php echo $this->date($log->getTimestamp(), 'd/m/Y H:i:s'); ?></td>
                        <td><?php echo $log->getBank()->getName(); ?></td>
                        <td><?php echo $log->getMessage(); ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    <?php endif; ?>
</div>
<div class="modal-footer">
    <a target="_blank" href="<?php echo $this->url('dtladmin/dtlproposal/proposal/printHistory', array('id' => $proposalId));?>?scp=<?php echo $this->vehicleProposal->getId();?>" class="btn btn-default"><i class="glyphicon glyphicon-print"></i></a>
    <button type="button" class="btn btn-default" data-dismiss="modal"><i class="glyphicon glyphicon-log-out"></i>&nbsp;<?php echo $this->translate('Fechar');?></button>
</div>