<?php
$title = $this->translate('Propostas de Veículos.');
$this->headTitle($title);
?>

<div class="app-header">
    <div class="app-logo">
        <img src="<?php echo $this->basePath('../images/login_logo.png');?>"/>
        <p class="pull-right"><?php echo $this->translate('Relatório');?></p>
    </div>
</div>

<div class="clearfix"></div>

<h3><?php echo $title; ?></h3>

<table class="table table-condensed">
    <thead>
        <tr>
            <th class=""><?php echo $this->translate('CÓD'); ?></th>
            <th class=""><?php echo $this->translate('CLIENTE'); ?></th>
            <th class=""><?php echo $this->translate('DT. CAD.'); ?></th>
            <th class=""><?php echo $this->translate('VALOR FIN.'); ?></th>
            <th class=""><?php echo $this->translate('PARC.'); ?></th>
            <th class=""><?php echo $this->translate('VALOR PARC.'); ?></th>
            <th class=""><?php echo $this->translate('BANCO'); ?></th>
            <th class=""><?php echo $this->translate('STATUS'); ?></th>
            <th><?php echo $this->translate('INTEGRADA'); ?></th>
        </tr>
    </thead>
    <?php if (0 == count($this->result->vehicleProposal)): ?>
        <tr>
            <td colspan="20" class="alert alert-info text-center"><?php echo $this->translate('Não há nenhum registro no banco de dados.') ?></td>
        </tr>
    <?php else: ?>
        <?php foreach ($this->result->vehicleProposal as $result) : ?>
            <?php $class = ''; ?>
            <?php $status = ''; ?>
            <?php if ($result->getProposal()->getIsChecking()): ?>
                <?php $class = 'text-info'; ?>
                <?php $status = 'ABERTA'; ?>
            <?php elseif ($result->getProposal()->getIsCanceled()): ?>
                <?php $class = 'text-canceled'; ?>
                <?php $status = 'CANCELADA'; ?>
            <?php elseif ($result->getProposal()->getIsRefused()): ?>
                <?php $class = 'text-danger'; ?>
                <?php $status = 'RECUSADA'; ?>
            <?php elseif ($result->getProposal()->getIsAborted()): ?>
                <?php $class = 'text-warning'; ?>
                <?php $status = 'ABORTADA'; ?>
            <?php elseif ($result->getProposal()->getIsApproved()): ?>
                <?php $class = 'text-muted'; ?>
                <?php $status = 'APROVADA'; ?>
            <?php elseif ($result->getProposal()->getIsIntegrated()): ?>
                <?php $class = 'text-success'; ?>
                <?php $status = 'INTEGRADA'; ?>
            <?php elseif ($result->getProposal()->getIsPending()): ?>
                <?php $class = 'text-primary'; ?>
                <?php $status = 'PENDENTE'; ?>
            <?php endif; ?>
            <tr class='<?php echo $class; ?>'>
                <td><?php echo str_pad($result->getId(), 8, '0', STR_PAD_LEFT); ?></td>
                <td><?php echo $this->escapeHtml($result->getProposal()->getCustomer()->getPerson()->getName()); ?></td>
                <td><?php echo $this->date($result->getProposal()->getTimestamp()); ?></td>
                <td><?php echo $this->currency($result->getProposal()->getValue()); ?></td>
                <td><?php echo $this->escapeHtml($result->getProposal()->getParcelAmount()); ?></td>
                <td><?php echo $this->currency($result->getProposal()->getParcelValue()); ?></td>
                <td><?php echo $this->escapeHtml($result->getProposal()->getBank()->getName()); ?></td>
                <td><?php echo $this->escapeHtml($status); ?></td>
                <?php if ($result->getProposal()->getIsIntegrated()): ?>
                    <td><?php echo $result->getProposal()->getBaseDate(); ?></td>
                <?php else: ?>
                    <td><?php echo $this->translate('NÃO'); ?></td>
                <?php endif; ?>
            </tr>
        <?php endforeach; ?>
    <?php endif; ?>
</table>