<?php
$vehicleProposal = $this->vehicleProposal;
$proposal = $vehicleProposal->getProposal();
$customer = $proposal->getCustomer();
$title = 'Detalhes da Proposta nº ' . $vehicleProposal->getId();
$this->headTitle($title);
?>
<?php $class = ''; ?>
<?php $status = ''; ?>
<?php if ($vehicleProposal->getProposal()->getIsChecking()): ?>
    <?php $class = 'panel-info'; ?>
    <?php $status = 'ABERTA'; ?>
<?php elseif ($vehicleProposal->getProposal()->getIsCanceled()): ?>
    <?php $class = 'panel-canceled'; ?>
    <?php $status = 'CANCELADA'; ?>
<?php elseif ($vehicleProposal->getProposal()->getIsRefused()): ?>
    <?php $class = 'panel-danger'; ?>
    <?php $status = 'RECUSADA'; ?>
<?php elseif ($vehicleProposal->getProposal()->getIsAborted()): ?>
    <?php $class = 'panel-warning'; ?>
    <?php $status = 'ABORTADA'; ?>
<?php elseif ($vehicleProposal->getProposal()->getIsApproved()): ?>
    <?php $class = 'panel-muted'; ?>
    <?php $status = 'APROVADA'; ?>
<?php elseif ($vehicleProposal->getProposal()->getIsIntegrated()): ?>
    <?php $class = 'panel-success'; ?>
    <?php $status = 'INTEGRADA'; ?>
<?php elseif ($vehicleProposal->getProposal()->getIsPending()): ?>
    <?php $class = 'panel-primary'; ?>
    <?php $status = 'PENDENTE'; ?>
<?php endif; ?>
<div class="panel <?php echo $class; ?>">
    <div class="panel-heading">
        <div class="row">
            <div class="col-xs-5">
                <div class="panel-title">
                    <i class="fa fa-truck"></i> 
                    Proposta Nº <?php echo str_pad($vehicleProposal->getId(), 8, '0', STR_PAD_LEFT); ?>
                </div>
            </div>
            <div class="col-xs-7 hidden-print">
                <div class="btn-group btn-group-sm pull-right">
                    <a class="btn btn-default" data-toggle="tooltip" title="Apagar" href="<?php
                    echo $this->url('dtladmin/dtlproposal/vehicle-proposal/delete', array('action' => 'delete',
                        'id' => $vehicleProposal->getId()));
                    ?>"><i class="glyphicon glyphicon-remove"></i> Apagar</a>
                    <a class="btn btn-default" data-toggle="tooltip" title="Editar" href="<?php
                    echo $this->url('dtladmin/dtlproposal/vehicle-proposal/edit', array(
                        'id' => $vehicleProposal->getId()));
                    ?>"><i class="glyphicon glyphicon-edit"></i> Editar</a>
                    <a class="btn btn-default app-tooltip" data-toggle="modal" title="Migração Bancária" data-target="#bankReport<?php echo $vehicleProposal->getId(); ?>"
                       href="<?php echo $this->url('dtladmin/dtlproposal/vehicle-proposal/bank', array('action' => 'bank', 'id' => $vehicleProposal->getId())); ?>">
                        <i class="glyphicon glyphicon-lock"></i> Migrar Banco</a>
                    <?php if (!$vehicleProposal->getProposal()->getIsIntegrated()): ?>
                        <a class="btn btn-default app-tooltip" data-toggle="modal" data-placement="top" title="Status da Proposta" data-target="#proposalStatus<?php echo $vehicleProposal->getId(); ?>"
                           href="<?php echo $this->url('dtladmin/dtlproposal/vehicle-proposal/status', array('action' => 'status', 'id' => $vehicleProposal->getId())); ?>">
                            <i class="glyphicon glyphicon-repeat"></i> Status</a>
                    <?php endif; ?>
                    <a class="btn btn-default app-tooltip" data-toggle="modal" title="Histórico" data-target="#proposalHistory<?php echo $vehicleProposal->getId(); ?>"
                       href="<?php echo $this->url('dtladmin/dtlproposal/vehicle-proposal/history', array('action' => 'history', 'id' => $vehicleProposal->getId())); ?>">
                        <i class="glyphicon glyphicon-time"></i> Histórico</a>
                    <a href="javascript: window.print();" class="btn btn-default">
                        <i class="glyphicon glyphicon-print"></i> 
                        <?php echo $this->translate('Imprimir'); ?>
                    </a>
                    <a class="btn btn-default" data-toggle="tooltip" title="Voltar" href="<?php
                    echo $this->url('dtladmin/dtlproposal/vehicle-proposal', array('action' => 'print',
                        'id' => $vehicleProposal->getId()));
                    ?>"><i class="glyphicon glyphicon-chevron-left"></i> Voltar</a>

                    <div class="modal" id="proposalHistory<?php echo $vehicleProposal->getId(); ?>" tabindex="-1" role="dialog" aria-hidden="true" aria-labelledby="Migração Bancária">
                        <div class="modal-dialog">
                            <div class="modal-content"></div>
                        </div>
                    </div>
                    <div class="modal" id="proposalStatus<?php echo $vehicleProposal->getId(); ?>" tabindex="-1" role="dialog" aria-hidden="true" aria-labelledby="Status da Proposta">
                        <div class="modal-dialog">
                            <div class="modal-content"></div>
                        </div>
                    </div>
                    <div class="modal" id="bankReport<?php echo $vehicleProposal->getId(); ?>" tabindex="-1" role="dialog" aria-hidden="true" aria-labelledby="Histórico">
                        <div class="modal-dialog">
                            <div class="modal-content"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="panel-body">
        <div class="panel <?php echo $class; ?>">
            <div class="panel-heading">
                <div class="panel-title"><i class=""></i> Dados Básicos da Proposta</div>
            </div>
            <div class="panel-body">
                <dl class="dl-horizontal">
                    <div class="row">
                        <div class="col-xs-6">
                            <dt>Número da Proposta:</dt>
                            <dd><?php echo $vehicleProposal->getId(); ?></dd>
                            <dt>Banco:</dt>
                            <dd><?php echo $vehicleProposal->getProposal()->getBank()->getName(); ?></dd>
                            <dt>Lojista:</dt>
                            <dd><?php echo $vehicleProposal->getShopman()->getPerson()->getName(); ?></dd>
                            <dt>Produto:</dt>
                            <dd><?php echo $vehicleProposal->getProduct()->getName(); ?></dd>
                            <dt>Vendedor:</dt>
                            <dd><?php echo $vehicleProposal->getSeller()->getPerson()->getName(); ?></dd>
                            <dt>Data de Cadastro:</dt>
                            <dd><?php echo $this->date($vehicleProposal->getProposal()->getTimestamp()); ?></dd>
                            <dt>Data Base:</dt>
                            <dd><?php echo $vehicleProposal->getProposal()->getBaseDate(); ?></dd>
                            <dt>Primeira Parc.:</dt>
                            <dd><?php echo $vehicleProposal->getProposal()->getStartDate(); ?></dd>
                            <dt>Última Parc.:</dt>
                            <dd><?php echo $vehicleProposal->getProposal()->getEndDate(); ?></dd>
                            <dt>Observações:</dt>
                            <dd><?php echo $vehicleProposal->getProposal()->getNotes(); ?></dd>
                        </div>
                        <div class="col-xs-6">
                            <dt>Status da Proposta:</dt>
                            <dd><?php echo $status; ?></dd>
                            <dt>Telefone do Lojista:</dt>
                            <dd><?php echo $this->phone($vehicleProposal->getShopman()->getPerson()->getContact()->getPhone()); ?></dd>
                            <dt>Telefone do Vendedor:</dt>
                            <dd><?php echo $this->phone($vehicleProposal->getSeller()->getPerson()->getContact()->getPhone()); ?></dd>
                            <dt>Empresa:</dt>
                            <dd><?php echo $vehicleProposal->getProposal()->getCompany()->getFancyName(); ?></dd>
                            <dt>Operador:</dt>
                            <dd><?php echo $vehicleProposal->getProposal()->getEmployee()->getPerson()->getName(); ?></dd>
                            <dt>Total da Compra:</dt>
                            <dd><?php echo $this->currency($vehicleProposal->getValue()); ?></dd>
                            <dt>Total Financiado:</dt>
                            <dd><?php echo $this->currency($vehicleProposal->getProposal()->getValue()); ?></dd>
                            <dt>Parcelas:</dt>
                            <dd><?php echo $vehicleProposal->getProposal()->getParcelAmount(); ?></dd>
                            <dt>Entrada:</dt>
                            <dd><?php echo $this->currency($vehicleProposal->getInValue()); ?></dd>
                            <dt>Valor da Parcela:</dt>
                            <dd><?php echo $this->currency($vehicleProposal->getProposal()->getParcelValue()); ?></dd>
                        </div>
                    </div>
                </dl>
            </div>
        </div>
        <div class="panel <?php echo $class; ?>">
            <div class="panel-heading">
                <div class="panel-title"><i class="fa fa-truck"></i> Produtos da Proposta</div>
            </div>
            <?php if (0 == count($vehicleProposal->getVehicles())): ?>
                <div class="panel-body">
                    <div class="alert alert-info">
                        <?php echo $this->translate('Nenhum registro encontrado.') ?>
                    </div>
                </div>
            <?php else: ?>
                <table class="table table-condensed table-hover">
                    <tr>
                        <th class=""><?php echo $this->translate('MARCA'); ?></th>
                        <th class=""><?php echo $this->translate('MODELO'); ?></th>
                        <th class=""><?php echo $this->translate('VERSÃO'); ?></th>
                        <th class=""><?php echo $this->translate('ANO/MODELO'); ?></th>
                        <th class=""><?php echo $this->translate('PLACA'); ?></th>
                        <th class=""><?php echo $this->translate('VALOR'); ?></th>
                    </tr>
                    <?php foreach ($vehicleProposal->getVehicles() as $vehicle) : ?>
                        <tr>
                            <td><?php echo $this->escapeHtml($vehicle->getBrand()->getName()); ?></td>
                            <td><?php echo $this->escapeHtml($vehicle->getModel()->getName()); ?></td>
                            <td><?php echo $this->escapeHtml($vehicle->getVersion()->getName()); ?></td>
                            <td>
                                <?php echo $vehicle->getYear(); ?>
                                <?php echo ($vehicle->getYearModel()) ? " / " . $vehicle->getYearModel() : ""; ?>
                            </td>
                            <td><?php echo $this->escapeHtml($vehicle->getPlate()); ?></td>
                            <td><?php echo $this->currency($vehicle->getValue()); ?></td>
                        </tr>
                    <?php endforeach; ?>
                </table>
            <?php endif; ?>
        </div>

        <?php echo $this->partial('dtl-proposal/proposal/view-customer', array('class' => $class, 'customer' => $customer)); ?>

    </div>
</div>
