<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'DtlDealer\Form\Fieldset\Dealer'     => __DIR__ . '/src/DtlDealer/Form/Fieldset/Dealer.php',
  'DtlDealer\Form\Helper\Dealer'       => __DIR__ . '/src/DtlDealer/Form/Helper/Dealer.php',
  'DtlDealer\Form\Dealer'              => __DIR__ . '/src/DtlDealer/Form/Dealer.php',
  'DtlDealer\Entity\Repository\Dealer' => __DIR__ . '/src/DtlDealer/Entity/Repository/Dealer.php',
  'DtlDealer\Entity\Dealer'            => __DIR__ . '/src/DtlDealer/Entity/Dealer.php',
  'DtlDealer\Module'                   => __DIR__ . '/Module.php',
);
