<?php
$title = $this->translate('Adicionar Despesa');
$this->headTitle($title);
$form = $this->form;
$form->setAttribute('action', $this->url('dtladmin/dtlfinancial/expense/add'));
$form->prepare();
?>
<div class="modal-header">
    <h3 class="header-title"><i class="fa fa-upload"></i> <?php echo $this->escapeHtml($title); ?></h3>
</div>
<?php echo $this->form()->openTag($form); ?>
<div class="modal-body">
    <?php $expense = $form->get('expense'); ?>
    <?php echo $this->formHidden($expense->get('id')); ?>
    <?php $launch = $expense->get('launch'); ?>
    <div class="row">
        <div class="col-md-12">
            <div class="form-group form-group-sm">
                <?php echo $this->formLabel($expense->get('supplier')); ?>
                <?php echo $this->formSelect($expense->get('supplier')); ?>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="form-group form-group-sm">
                <?php echo $this->formLabel($launch->get('description')); ?>
                <?php echo $this->formText($launch->get('description')); ?>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group form-group-sm">
                <?php echo $this->formLabel($launch->get('currentAccount')); ?>
                <?php echo $this->formSelect($launch->get('currentAccount')); ?>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group form-group-sm">
                <?php echo $this->formLabel($launch->get('accountingItem')); ?>
                <?php echo $this->formSelect($launch->get('accountingItem')); ?>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group form-group-sm">
                <?php echo $this->formLabel($launch->get('date')); ?>
                <?php echo $this->dtlBaseFormDate($launch->get('date')); ?>
            </div>
        </div>  
        <div class="col-md-6">
            <div class="form-group form-group-sm">
                <?php echo $this->formLabel($launch->get('value')); ?>
                <div class="input-group">
                    <span class="input-group-addon">R$</span>
                    <?php echo $this->formText($launch->get('value')); ?>
                </div>
            </div>
        </div>
    </div>
    <?php echo $this->formHidden($form->get('security')); ?>
</div>
<div class="modal-footer">
    <?php echo $this->formElement($form->get('submit')); ?>
    <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-remove"></i><?php echo $this->translate('Fechar'); ?></button>
</div>
<?php echo $this->form()->closeTag(); ?>
