<?php
$title = $this->translate('Editar Categoria');
$this->headTitle($title);
$form = $this->form;
$form->setAttribute('action', $this->url('dtladmin/dtlcategory/edit', array('id' => $this->id)));
$form->prepare();
?>
<h1 class="container-header"><?php echo $this->escapeHtml($title); ?></h1>
<?php echo $this->form()->openTag($form); ?>
<div class="form-gorup">
    <?php $category = $form->get('category'); ?>
    <?php echo $this->formHidden($category->get('id')); ?>
    <div class="row">
        <div class="col-md-6">
            <?php echo $this->formLabel($category->get('name')); ?>
            <?php echo $this->formText($category->get('name')); ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <?php echo $this->formLabel($category->get('type')); ?>
            <?php echo $this->formSelect($category->get('type')); ?>
        </div>
    </div>
</div>
<?php echo $this->formHidden($form->get('security')); ?>
<br/>
<div class="btn-group">
    <?php echo $this->formElement($form->get('submit')); ?>
    <?php echo $this->formElement($form->get('cancel')); ?>
</div>
<?php echo $this->form()->closeTag(); ?>
