<form action="" method="post" name="categorySearch" id="categorySearch">
    <div class="form-group">
        <label for="category_cod_search">Código</label>
        <input type="text" class="form-control input-sm" id="category_cod_search" name="category_cod_search" value="" placeholder="<?php echo $this->translate('Código do Categoria'); ?>" />
    </div>
    <div class="form-group">
        <label for="category_name_search">Categoria</label>
        <input type="text" class="form-control input-sm" id="category_name_search" name="category_name_search" value="" placeholder="<?php echo $this->translate('Nome do Categoria'); ?>" />
    </div>
    <button type="submit" class="btn btn-warning btn-sm" name="submit" value="Filtrar"><?php echo $this->translate('Filtrar'); ?></button>
    <button type="button" onclick="window.location.href = '/admin/category'" class="btn btn-default btn-sm"><?php echo $this->translate('Limpar'); ?></button>
</form>