<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'DtlShopman\Form\Shopman'                        => __DIR__ . '/src/DtlShopman/Form/Shopman.php',
  'DtlShopman\Form\Fieldset\Shopman'               => __DIR__ . '/src/DtlShopman/Form/Fieldset/Shopman.php',
  'DtlShopman\Form\Fieldset\ShopmanProduct'        => __DIR__ . '/src/DtlShopman/Form/Fieldset/ShopmanProduct.php',
  'DtlShopman\Form\ShopmanProduct'                 => __DIR__ . '/src/DtlShopman/Form/ShopmanProduct.php',
  'DtlShopman\Factory\Shopman'                     => __DIR__ . '/src/DtlShopman/Factory/Shopman.php',
  'DtlShopman\Factory\ShopmanProduct'              => __DIR__ . '/src/DtlShopman/Factory/ShopmanProduct.php',
  'DtlShopman\Controller\ShopmanProductController' => __DIR__ . '/src/DtlShopman/Controller/ShopmanProductController.php',
  'DtlShopman\Controller\ShopmanController'        => __DIR__ . '/src/DtlShopman/Controller/ShopmanController.php',
  'DtlShopman\Entity\Repository\Shopman'           => __DIR__ . '/src/DtlShopman/Entity/Repository/Shopman.php',
  'DtlShopman\Entity\Shopman'                      => __DIR__ . '/src/DtlShopman/Entity/Shopman.php',
  'DtlShopman\Module'                              => __DIR__ . '/Module.php',
);
