<div class="panel panel-warning">
    <div class="panel-heading">
        <div class="panel-title"><i class="glyphicon glyphicon-thumbs-up"></i> <?php echo $this->escapeHtml('Lista de Referências do Cliente'); ?></div>
    </div>
    <?php if (0 == count($this->customerReferences)): ?>
        <div class="panel-body">
            <div class="alert alert-info">
                <?php echo $this->translate('Nenhum registro encontrado.') ?>
            </div>
        </div>
    <?php else: ?>
        <table class="table table-condensed table-hover">
            <tr>
                <th class=""><?php echo $this->translate('TIPO'); ?></th>
                <th class=""><?php echo $this->translate('REFERÊNCIA'); ?></th>
                <th class="" colspan="2"><?php echo $this->translate('TELEFONE'); ?></th>
            </tr>
            <?php foreach ($this->customerReferences as $key => $customerReference) : ?>
                <tr>
                    <td><?php echo $this->escapeHtml($customerReference['referenceType']); ?></td>
                    <td><?php echo $this->escapeHtml($customerReference['referenceName']); ?></td>
                    <td><?php echo $this->phone($customerReference['referencePhone']); ?></td>
                    <td>
                        <div class="btn-group btn-group-xs pull-right">
                            <a class="btn btn-default" href="javascript: proposalCustomerReferenceDelete('<?php echo $key; ?>', '<?php echo $customerReference['referenceId']; ?>')"><i class="glyphicon glyphicon-remove"></i></a>
                        </div>
                    </td>
                </tr>
            <?php endforeach; ?>
        <?php endif; ?>
    </table>
</div>