<div class="row">
    <div class="col-md-4">
        <?php $customerVehicle = $this->customerVehicle; ?>
        <div class="form-group">
            <?php $vehicle = $customerVehicle->get('vehicle'); ?>

            <?php echo $this->formLabel($vehicle->get('brand')); ?>
            <?php echo $this->formSelect($vehicle->get('brand')); ?>

            <?php echo $this->formLabel($vehicle->get('type')); ?>
            <?php echo $this->formSelect($vehicle->get('type')); ?>

            <?php echo $this->formLabel($vehicle->get('model')); ?>
            <?php echo $this->formSelect($vehicle->get('model')); ?>

            <?php echo $this->formLabel($vehicle->get('version')); ?>
            <?php echo $this->formSelect($vehicle->get('version')); ?>
            <div class='row'>
                <div class="col-md-6">
                    <?php echo $this->formLabel($vehicle->get('year')); ?>
                    <?php echo $this->formText($vehicle->get('year')); ?>
                </div>
                <div class='col-md-6'>
                    <?php echo $this->formLabel($vehicle->get('yearModel')); ?>
                    <?php echo $this->formText($vehicle->get('yearModel')); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <?php echo $this->formLabel($vehicle->get('plate')); ?>
                    <?php echo $this->formText($vehicle->get('plate')); ?>
                </div>
                <div class='col-md-6'>
                    <?php echo $this->formLabel($vehicle->get('color')); ?>
                    <?php echo $this->formText($vehicle->get('color')); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6">
                    <?php echo $this->formLabel($vehicle->get('value')); ?>
                    <div class="input-group">
                        <span class="input-group-addon">R$</span>
                        <?php echo $this->formText($vehicle->get('value')); ?>
                    </div>
                </div>
                <div class="col-lg-6">
                    <br>
                    <input type="button" name="submit" id="submit" value="Inserir" 
                           onclick="javascript: proposalCustomerVehicleAdd();" class="btn btn-info" />
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-8">
        <div class="proposal-customer-vehicle-list"></div>
    </div>
</div>
<script type="text/javascript">
    proposalCustomerVehicleList();
</script>