<div class="row">
    <div class="col-md-4">
        <?php $customerReference = $this->customerReference; ?>
        <div class="form-group">
            <?php $reference = $customerReference->get('reference'); ?>
            
            <?php echo $this->formLabel($reference->get('type')); ?>
            <?php echo $this->formSelect($reference->get('type')); ?>

            <?php echo $this->formLabel($reference->get('name')); ?>
            <?php echo $this->formText($reference->get('name')); ?>

            <?php echo $this->formLabel($reference->get('phone')); ?>
            <?php echo $this->formText($reference->get('phone')); ?>
            
            <br>
            <input type="button" name="submit" id="submit" value="Inserir" 
                   onclick="javascript: proposalCustomerReferenceAdd();" class="btn btn-info" />
        </div>
    </div>
    <div class="col-md-8">
        <div class="proposal-customer-reference-list"></div>
    </div>
</div>
<script type="text/javascript">
    proposalCustomerReferenceList();
</script>