<div class="row">
    <div class="col-md-4">
        <?php $customerPatrimony = $this->customerPatrimony; ?>
        <div class="form-group">
            <?php $patrimony = $customerPatrimony->get('patrimony'); ?>
            
            <?php echo $this->formLabel($patrimony->get('name')); ?>
            <?php echo $this->formText($patrimony->get('name')); ?>

            <?php echo $this->formLabel($patrimony->get('value')); ?>
            <div class="input-group">
                <span class="input-group-addon">R$</span>
                <?php echo $this->formText($patrimony->get('value')); ?>
            </div>
            
            <br>
            <input type="button" name="submit" id="submit" value="Inserir" 
                   onclick="javascript: proposalCustomerPatrimonyAdd();" class="btn btn-info" />
        </div>
    </div>
    <div class="col-md-8">
        <div class="proposal-customer-patrimony-list"></div>
    </div>
</div>
<script type="text/javascript">
    proposalCustomerPatrimonyList();
</script>