<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'DtlProduct\Form\Fieldset\Product'         => __DIR__ . '/src/DtlProduct/Form/Fieldset/Product.php',
  'DtlProduct\Form\Fieldset\Category'        => __DIR__ . '/src/DtlProduct/Form/Fieldset/Category.php',
  'DtlProduct\Form\Product'                  => __DIR__ . '/src/DtlProduct/Form/Product.php',
  'DtlProduct\Form\Category'                 => __DIR__ . '/src/DtlProduct/Form/Category.php',
  'DtlProduct\Factory\Product'               => __DIR__ . '/src/DtlProduct/Factory/Product.php',
  'DtlProduct\Factory\Category'              => __DIR__ . '/src/DtlProduct/Factory/Category.php',
  'DtlProduct\Controller\CategoryController' => __DIR__ . '/src/DtlProduct/Controller/CategoryController.php',
  'DtlProduct\Controller\ProductController'  => __DIR__ . '/src/DtlProduct/Controller/ProductController.php',
  'DtlProduct\Entity\Repository\DtlProduct'     => __DIR__ . '/src/DtlProduct/Entity/Repository/Product.php',
  'DtlProduct\Entity\Product'                => __DIR__ . '/src/DtlProduct/Entity/Product.php',
  'DtlProduct\Entity\Category'               => __DIR__ . '/src/DtlProduct/Entity/Category.php',
  'DtlProduct\Module'                        => __DIR__ . '/Module.php',
);
