<?php

// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'DtlReference\Form\Fieldset\Reference' => __DIR__ . '/src/DtlReference/Form/Fieldset/Reference.php',
    'DtlReference\Entity\Reference' => __DIR__ . '/src/DtlReference/Entity/Reference.php',
    'DtlReference\Module' => __DIR__ . '/Module.php',
);
