<?php

// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'DtlBankAccount\Form\View\Helper\BankAccountForm' => __DIR__ . '/src/DtlBankAccount/Form/View/Helper/BankAccountForm.php',
    'DtlBankAccount\Form\Fieldset\BankAccount' => __DIR__ . '/src/DtlBankAccount/Form/Fieldset/BankAccount.php',
    'DtlBankAccount\Entity\BankAccount' => __DIR__ . '/src/DtlBankAccount/Entity/BankAccount.php',
    'DtlBankAccount\Module' => __DIR__ . '/Module.php',
);
