<?php $dealers = $this->dealers; ?>
<?php foreach ($dealers as $key => $dealer): ?>
    <fieldset>
        <legend><h3>Vendedor <?php echo $key + 1; ?></h3></legend>
        <?php echo $this->formHidden($dealer->get('id')); ?>
        <?php $person = $dealer->get('person'); ?>
        <?php echo $this->personForm($person); ?>

        <?php if ($this->params['type'] == base64_encode(1)): ?>
            <?php $legal = $person->get('legal'); ?>
            <?php echo $this->legalForm($legal); ?>
        <?php elseif ($this->params['type'] == base64_encode(0)): ?>
            <?php $individual = $person->get('individual'); ?>
            <?php echo $this->individualForm($individual); ?>
        <?php endif; ?>
    </fieldset>
<?php endforeach;
