<?php
$company = $this->company;
$address = $company->getAddress();
$contact = $company->getContact();
$title = 'Detalhes de ' . $company->getName();
$this->headTitle($title);
?>
<div>
    <h4>Cliente</h4>
    <div class="row">
        <div class="col-md-6">
            <blockquote>
                <p class="text-danger">
                    <?php echo $company->getName(); ?>
                </p>
            </blockquote>
        </div>
        <div class="pull-right">
            <div class="btn-group">
                <a class="btn btn-default" href="<?php echo $this->url('dtladmin/dtlcompany/add'); ?>"> <i class="glyphicon glyphicon-plus-sign"></i> <?php echo $this->translate('Novo'); ?></a>
                <a class="btn btn-default" href="<?php echo $this->url('dtladmin/dtlcompany/edit', array('id' => $company->getId())); ?>"><i class="glyphicon glyphicon-edit"></i> <?php echo $this->translate('Editar'); ?></a>
                <a class="btn btn-default" href="<?php echo $this->url('dtladmin/dtlcompany/delete', array('id' => $company->getId())); ?>"><i class="glyphicon glyphicon-remove"></i> <?php echo $this->translate('Apagar'); ?></a>
                <a class="btn btn-default" href="<?php echo $this->url('dtladmin/dtlcompany'); ?>"><i class="glyphicon glyphicon-chevron-left"></i> <?php echo $this->translate('Voltar'); ?></a>
            </div>
        </div>
    </div>
</div>
<dl class="dl-horizontal">
    <legend>Dados da Empresa</legend>
    <dt>Razão Social:</dt>
    <dd><?php echo $company->getName(); ?>&nbsp;</dd>
    <dt>Nome Fantasia:</dt>
    <dd><?php echo $company->getFancyName(); ?>&nbsp;</dd>
    <dt>CNPJ:</dt>
    <dd><?php echo $this->cnpj($company->getCnpj()); ?>&nbsp;</dd>
    <dt>Inscrição Estadual:</dt>
    <dd><?php echo $company->getSubscription(); ?>&nbsp;</dd>
    <dt>Representante:</dt>
    <dd><?php echo $company->getRepresentativeName(); ?>&nbsp;</dd>
    <dt>Telefone do Rep.:</dt>
    <dd><?php echo $this->phone($company->getRepresentativePhone()); ?>&nbsp;</dd>

    <legend>Endereço</legend>
    <dt>Endereço:</dt>
    <dd><?php echo $address->getName(); ?>, nº <?php echo $address->getNumber(); ?></dd>
    <dt>Complemento:</dt>
    <dd><?php echo $address->getComplement(); ?>&nbsp;</dd>
    <dt>Bairro:</dt>
    <dd><?php echo $address->getQuarter(); ?>&nbsp;</dd>
    <dt>CEP:</dt>
    <dd><?php echo $this->cep($address->getPostalCode()); ?>&nbsp;</dd>
    <dt>Cidade:</dt>
    <dd><?php echo ($address->getCity()) ? $address->getCity()->getName() : ''; ?>&nbsp;</dd>
    <dt>Estado:</dt>
    <dd><?php echo ($address->getState()) ? $address->getState()->getName() : ''; ?>&nbsp;</dd>
    <dt>País:</dt>
    <dd><?php echo ($address->getCountry()) ? $address->getCountry()->getName() : ''; ?>&nbsp;</dd>

    <legend>Contato</legend>
    <dt>Email:</dt>
    <dd><?php echo $contact->getEmail(); ?>&nbsp;</dd>
    <dt>Website:</dt>
    <dd><?php echo $contact->getUrl(); ?>&nbsp;</dd>
    <dt>Telefone:</dt>
    <dd><?php echo $this->phone($contact->getPhone()); ?>&nbsp;</dd>
    <dt>Celular:</dt>
    <dd><?php echo $this->phone($contact->getCell()); ?>&nbsp;</dd>
    <dt>FAX:</dt>
    <dd><?php echo $this->phone($contact->getFax()); ?>&nbsp;</dd>
</dl>