<?php
$title = $this->translate('Veículos do Cliente');
$this->headTitle($title);
$form = $this->form;
$form->prepare();
?>
<legend><h2><i class="fa fa-building-o"></i> <?php echo $this->escapeHtml($title); ?></h2></legend>

<div class="">
    <div class="col-md-4">
        <?php echo $this->form()->openTag($form); ?>
        <?php $customerVehicle = $form->get('customerVehicle'); ?>
        <div class="form-group">
            <?php echo $this->formLabel($customerVehicle->get('customer')); ?>
            <?php echo $this->formSelect($customerVehicle->get('customer')); ?>

            <?php $vehicle = $customerVehicle->get('vehicle'); ?>

            <?php echo $this->formLabel($vehicle->get('brand')); ?>
            <?php echo $this->formSelect($vehicle->get('brand')); ?>

            <?php echo $this->formLabel($vehicle->get('type')); ?>
            <?php echo $this->formSelect($vehicle->get('type')); ?>

            <?php echo $this->formLabel($vehicle->get('model')); ?>
            <?php echo $this->formSelect($vehicle->get('model')); ?>

            <?php echo $this->formLabel($vehicle->get('version')); ?>
            <?php echo $this->formSelect($vehicle->get('version')); ?>
            <div class='row'>
                <div class="col-md-6">
                    <?php echo $this->formLabel($vehicle->get('year')); ?>
                    <?php echo $this->formText($vehicle->get('year')); ?>
                </div>
                <div class='col-md-6'>
                    <?php echo $this->formLabel($vehicle->get('yearModel')); ?>
                    <?php echo $this->formText($vehicle->get('yearModel')); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <?php echo $this->formLabel($vehicle->get('plate')); ?>
                    <?php echo $this->formText($vehicle->get('plate')); ?>
                </div>
                <div class='col-md-6'>
                    <?php echo $this->formLabel($vehicle->get('color')); ?>
                    <?php echo $this->formText($vehicle->get('color')); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6">
                    <?php echo $this->formLabel($vehicle->get('value')); ?>
                    <div class="input-group">
                        <span class="input-group-addon">R$</span>
                        <?php echo $this->formText($vehicle->get('value')); ?>
                    </div>
                </div>
            </div>
        </div>
        <?php echo $this->formHidden($form->get('security')); ?>
        <div class="btn-group">
            <?php echo $this->formElement($form->get('submit')); ?>
            <?php echo $this->formElement($form->get('cancel')); ?>
        </div>
        <?php echo $this->form()->closeTag(); ?>
    </div>
    <div class="col-md-8">
        <div class="customer-vehicle-list"></div>
    </div>
</div>
<script type="text/javascript">
    customerVehicleList('<?php echo $this->customerId; ?>');
</script>