<div class="row">
    <div class="col-md-4">
        <?php $product = $this->caixaProposal; ?>
        <div class="form-group">
            <div class="row">
                <div class="col-md-12">
                    <?php echo $this->formLabel($product->get('product')); ?>
                    <?php echo $this->formSelect($product->get('product')); ?>
                </div>
            </div>
            <br/>
            <div class="row">
                <div class="col-md-6">
                    <input type="button" class="btn btn-primary" value="Inserir Produto" onclick="caixaProposalAdd();" />
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-8">
        <div class="caixa-proposal-list"></div>
    </div>
</div>
<script type="text/javascript">
    caixaProposalList();
</script>