<?php
$title = $this->translate('Caixa');
$this->headTitle($title);
$this->placeholder('title')->set($title);
$this->placeholder('title-icon')->set('<i class="fa fa-usd"></i>');
?>
<div class="page-body">
    <div class="row">
        <div class="col-md-3">
            <div class="widget-box no-header">
                <div class="widget-body">
                    <div class="widget-main">
                        <div class="clearfix">
                            <a data-toggle="modal" data-target="#addRevenue" class="btn btn-success btn-block app-tooltip" href="<?php echo $this->url('dtladmin/dtlfinancial/revenue/add'); ?>" title="Nova Receita"><i class="fa fa-download"></i> Nova Receita</a>
                            <a data-toggle="modal" data-target="#addExpense" class="btn btn-danger btn-block app-tooltip" href="<?php echo $this->url('dtladmin/dtlfinancial/expense/add'); ?>" title="Nova Despesa"><i class="fa fa-upload"></i> Nova Despesa</a>
                        </div>
                    </div>
                </div>
            </div>

            <div class="widget-box">
                <div class="widget-header">
                    <i class="widget-icon glyphicon glyphicon-usd"></i>
                    <h4 class="widget-caption">Resumo do Caixa</h4>
                </div>
                <div class="widget-body">
                    <div class="widget-main">
                        <?php if ((double) $this->lastBalance >= 0): ?>
                            <h4 class="text-info" dir="rtl">
                                <small>Saldo Anterior</small>
                                <?php echo $this->currency((double) $this->lastBalance); ?>
                            </h4>
                        <?php else: ?>
                            <h4 class="text-danger" dir="rtl">
                                <small>Saldo Anterior</small>
                                <?php echo $this->currency((double) $this->lastBalance); ?>
                            </h4>
                        <?php endif; ?>
                        <hr/>
                        <?php if ((double) $this->balance >= 0): ?>
                            <h4 class="text-info" dir="rtl">
                                <small>Saldo Atual</small>
                                <?php echo $this->currency((double) $this->balance); ?>
                            </h4>
                        <?php else: ?>
                            <h4 class="text-danger" dir="rtl">
                                <small>Saldo Atual</small>
                                <?php echo $this->currency((double) $this->balance); ?>
                            </h4>
                        <?php endif; ?>
                    </div>
                </div>
            </div>

            <div class="widget-box">
                <div class="widget-header">
                    <i class="widget-icon fa fa-gear"></i> 
                    <h4 class="widget-caption">Opções de Visualização</h4>
                </div>
                <div class="widget-body">
                    <div class="widget-main">
                        <form>
                            <div class="input-group input-group-sm">
                                <input type="text" id="dt" name="dt" value="<?php echo date('d/m/Y'); ?>" class="form-control datepicker" />
                                <span class="input-group-btn">
                                    <input type="submit" id="submit" name="submit" value="Ok" class="btn btn-default" />
                                </span>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-9">
            <div class="widget-box">
                <div class="widget-header">
                    <i class="widget-icon glyphicon glyphicon-usd"></i> 
                    <h4 class="widget-caption">Caixa do Dia - <?php echo $this->date(new \DateTime($this->date)); ?></h4>
                </div>
                <div class="widget-body">
                    <div class="widget-main">
                        <table class="table table-striped no-datatables">
                            <thead>
                                <tr>
                                    <th class="col-md-2"><?php echo $this->translate('DATA'); ?></th>
                                    <th><?php echo $this->translate('DESCRIÇÃO'); ?></th>
                                    <th><?php echo $this->translate('DÉBITO'); ?></th>
                                    <th><?php echo $this->translate('CRÉDITO'); ?></th>
                                    <th><?php echo $this->translate('SALDO'); ?></th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td colspan="4" dir="rtl">SALDO ANTERIOR</td>
                                    <td><b><?php echo $this->currency($this->lastBalance); ?></b></td>
                                </tr>
                                <?php if (!count($this->cash)): ?>
                                    <tr>
                                        <td colspan="10" class="text-center alert alert-info"><?php echo ($this->translate('Não há lançamentos no dia até o momento.')) ?></td>
                                    </tr>
                                <?php else: ?>
                                    <?php foreach ($this->cash as $launch) : ?>
                                        <?php $cashLaunch = $this->launch($launch->getId()); ?>
                                        <?php if ($cashLaunch instanceof \DtlFinancial\Entity\Revenue): ?>
                                            <tr class="text-info">
                                                <td><?php echo $this->date($launch->getDate()); ?></td>
                                                <td><?php echo $this->escapeHtml($launch->getDescription()); ?></td>
                                                <td>-</td>
                                                <td><?php echo $this->currency($launch->getValue()); ?></td>
                                                <td>&nbsp;</td>
                                            </tr>
                                        <?php elseif ($cashLaunch instanceof \DtlFinancial\Entity\Expense): ?>
                                            <tr class="text-danger">
                                                <td><?php echo $this->date($launch->getDate()); ?></td>
                                                <td><?php echo $this->escapeHtml($launch->getDescription()); ?></td>
                                                <td><?php echo $this->currency($launch->getValue()); ?></td>
                                                <td>-</td>
                                                <td>&nbsp;</td>
                                            </tr>
                                        <?php endif; ?>
                                    <?php endforeach; ?>
                                <?php endif; ?>
                                <tr style="font-weight: bold; background: #fafafa;">
                                    <td colspan="2" dir="rtl"><b>TOTAL</b></td>
                                    <td class="text-danger"><?php echo $this->currency($this->expense); ?></td>
                                    <td class="text-info"><?php echo $this->currency($this->revenue); ?></td>
                                    <td><?php echo $this->currency($this->balance); ?></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" aria-hidden="true" tabindex="-1" id="addRevenue">
        <div class="modal-dialog">
            <div class="modal-content"></div>
        </div>
    </div>
    <div class="modal fade" aria-hidden="true" tabindex="-1" id="addExpense">
        <div class="modal-dialog">
            <div class="modal-content"></div>
        </div>
    </div>
</div>