<?php
$title = $this->translate('Editar Proposta de Empréstimo Consignado');
$this->headTitle($title);
$form = $this->form;
$form->setAttribute('action', $this->url('dtladmin/dtlproposal/loan-proposal/edit', array('id' => $this->loan->getId())));
$form->prepare();
?>
<?php echo $this->form()->openTag($form); ?>
<div class="row">
    <div class="col-md-6">
        <h2 class="container-header">
            <i class="fa fa-money"></i> <?php echo $this->escapeHtml($title); ?>
        </h2>
    </div>
    <div class="col-md-6">
        <div class="btn-group pull-right">
            <input type="submit" class="btn btn-primary" value="Salvar Proposta" />
        </div>
    </div>
</div>
<div class="clearfix"></div><br/>
<?php $loan = $form->get('loan'); ?>
<?php $proposal = $loan->get('proposal'); ?>
<fieldset>
    <div class="panel-group">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Dados Básicos'); ?></h3>
            </div>
            <div class="panel-body">
                <div class="form-group">
                    <div class="row">
                        <div class="col-md-3">
                            <?php echo $this->formLabel($loan->get('benefitNumber')); ?>
                            <?php echo $this->formText($loan->get('benefitNumber')); ?>
                        </div>
                        <div class="col-md-1">
                            <?php echo $this->formLabel($loan->get('benefitUf')); ?>
                            <?php echo $this->formText($loan->get('benefitUf')); ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <?php echo $this->formLabel($proposal->get('company')); ?>
                            <?php echo $this->formSelect($proposal->get('company')); ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <?php if ($this->employee()): ?>
                                <?php echo $this->formSelect($proposal->get('employee')->setValue($this->employee()->getId())->setAttribute('class', 'hide')); ?>
                            <?php else: ?>
                                <?php echo $this->formLabel($proposal->get('employee')); ?>
                                <?php echo $this->formSelect($proposal->get('employee')); ?>
                            <?php endif; ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <?php echo $this->formLabel($proposal->get('bank')); ?>
                            <?php echo $this->formSelect($proposal->get('bank')); ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <?php echo $this->formLabel($loan->get('shopman')); ?>
                            <?php echo $this->formSelect($loan->get('shopman')); ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <?php echo $this->formLabel($loan->get('product')); ?>
                            <?php echo $this->formSelect($loan->get('product')); ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <?php echo $this->formLabel($proposal->get('notes')); ?>
                            <?php echo $this->formTextarea($proposal->get('notes')); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Cliente'); ?></h3>
            </div>
            <div class="panel-body">
                <?php $customer = $proposal->get('customer'); ?>
                <?php echo $this->customerForm($customer, $this->post, true, $this->loan->getProposal()->getCustomer()); ?>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Contas do Cliente'); ?></h3>
            </div>
            <div class="panel-body">
                <?php $customerBankAccount = new DtlCustomer\Form\Fieldset\CustomerBankAccount($this->entityManager, 0); ?>
                <?php $customerBankAccount->remove('customer'); ?>
                <?php echo $this->customerBankAccountForm($customerBankAccount); ?>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Resumo da Proposta'); ?></h3>
            </div>
            <div class="panel-body">
                <?php echo $this->proposalForm($proposal); ?>
                <div class="row">
                    <div class="col-md-2">
                        <?php echo $this->formLabel($loan->get('margin')); ?>
                        <div class="input-group">
                            <span class="input-group-addon">R$</span>
                            <?php echo $this->formText($loan->get('margin')); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <input type="submit" class="btn btn-primary" value="Salvar Proposta" />
</fieldset>
<?php
echo $this->form()->closeTag();