<?php
$title = $this->translate('Pre Cadastro da Proposta');
$this->headTitle($title);
$form = $this->form;
$form->prepare();
?>
<div class="modal" id="preProposalModal" tabindex="-1" role="dialog" aria-labelledgy="pre-proposal-label" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title"><?php echo $this->escapeHtml($title); ?></h4>
            </div>
            <div class="modal-body">
                <?php echo $this->form()->openTag($form); ?>
                <div class="form-group">
                    <?php $preProposal = $form->get('preProposal'); ?>
                    <?php echo $this->formElementErrors($preProposal->get('cpf')); ?>
                    <?php echo $this->formElementErrors($preProposal->get('cnpj')); ?>
                    <div class="row">
                        <div class="col-md-6">
                            <?php echo $this->formHidden($preProposal->get('type')->setValue('MA==')); ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <?php echo $this->formLabel($preProposal->get('cpf')); ?>
                            <?php echo $this->formText($preProposal->get('cpf')); ?>
                        </div>
                    </div>
                </div>
                <?php echo $this->formHidden($form->get('security')); ?>
            </div>
            <div class="modal-footer">
                <?php echo $this->formElement($form->get('cancel')); ?>
                <?php echo $this->formSubmit($form->get('submit')); ?>
            </div>
            <?php echo $this->form()->closeTag(); ?>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<script type="text/javascript">
    $('#preProposalModal').modal({
        backdrop: "static"
    }).show();
</script>