<?php
$loan = $this->loan;
$proposal = $loan->getProposal();
$customer = $proposal->getCustomer();
$title = 'Detalhes da Proposta nº ' . $loan->getId();
$this->headTitle($title);
?>
<?php $class = ''; ?>
<?php $status = ''; ?>
<?php if ($loan->getProposal()->getIsChecking()): ?>
    <?php $class = 'panel-info'; ?>
    <?php $status = 'ABERTA'; ?>
<?php elseif ($loan->getProposal()->getIsCanceled()): ?>
    <?php $class = 'panel-canceled'; ?>
    <?php $status = 'CANCELADA'; ?>
<?php elseif ($loan->getProposal()->getIsRefused()): ?>
    <?php $class = 'panel-danger'; ?>
    <?php $status = 'RECUSADA'; ?>
<?php elseif ($loan->getProposal()->getIsAborted()): ?>
    <?php $class = 'panel-warning'; ?>
    <?php $status = 'ABORTADA'; ?>
<?php elseif ($loan->getProposal()->getIsApproved()): ?>
    <?php $class = 'panel-muted'; ?>
    <?php $status = 'APROVADA'; ?>
<?php elseif ($loan->getProposal()->getIsIntegrated()): ?>
    <?php $class = 'panel-success'; ?>
    <?php $status = 'INTEGRADA'; ?>
<?php elseif ($loan->getProposal()->getIsPending()): ?>
    <?php $class = 'panel-primary'; ?>
    <?php $status = 'PENDENTE'; ?>
<?php endif; ?>
<div class="panel <?php echo $class; ?>">
    <div class="panel-heading">
        <div class="row">
            <div class="col-xs-5">
                <div class="panel-title">
                    <i class="fa fa-money"></i> 
                    Proposta Nº <?php echo str_pad($loan->getId(), 8, '0', STR_PAD_LEFT); ?>
                </div>
            </div>
            <div class="col-xs-7 hidden-print">
                <div class="btn-group btn-group-sm pull-right">
                    <a class="btn btn-default" data-toggle="tooltip" title="Apagar" href="<?php
                    echo $this->url('dtladmin/dtlproposal/loan-proposal/delete', array('action' => 'delete',
                        'id' => $loan->getId()));
                    ?>"><i class="glyphicon glyphicon-remove"></i> Apagar</a>
                    <a class="btn btn-default" data-toggle="tooltip" title="Editar" href="<?php
                    echo $this->url('dtladmin/dtlproposal/loan-proposal/edit', array(
                        'id' => $loan->getId()));
                    ?>"><i class="glyphicon glyphicon-edit"></i> Editar</a>
                    <a class="btn btn-default app-tooltip" data-toggle="modal" title="Migração Bancária" data-target="#bankReport<?php echo $loan->getId(); ?>"
                       href="<?php echo $this->url('dtladmin/dtlproposal/loan-proposal/bank', array('action' => 'bank', 'id' => $loan->getId())); ?>">
                        <i class="glyphicon glyphicon-lock"></i> Migrar Banco</a>
                    <?php if (!$loan->getProposal()->getIsIntegrated()): ?>
                        <a class="btn btn-default app-tooltip" data-toggle="modal" data-placement="left" title="Status da Proposta" data-target="#proposalStatus<?php echo $loan->getId(); ?>"
                           href="<?php echo $this->url('dtladmin/dtlproposal/loan-proposal/status', array('action' => 'status', 'id' => $loan->getId())); ?>">
                            <i class="glyphicon glyphicon-repeat"></i> Status</a>
                    <?php endif; ?>
                    <a class="btn btn-default app-tooltip" data-toggle="modal" title="Histórico" data-target="#proposalHistory<?php echo $loan->getId(); ?>"
                       href="<?php echo $this->url('dtladmin/dtlproposal/loan-proposal/history', array('action' => 'history', 'id' => $loan->getId())); ?>">
                        <i class="glyphicon glyphicon-time"></i> Histórico</a>
                    <a href="javascript: window.print();" class="btn btn-default">
                        <i class="glyphicon glyphicon-print"></i> 
                        <?php echo $this->translate('Imprimir'); ?>
                    </a>
                    <a class="btn btn-default" data-toggle="tooltip" title="Voltar" href="<?php
                    echo $this->url('dtladmin/dtlproposal/loan-proposal', array('action' => 'print',
                        'id' => $loan->getId()));
                    ?>"><i class="glyphicon glyphicon-chevron-left"></i> Voltar</a>

                    <div class="modal" id="proposalHistory<?php echo $loan->getId(); ?>" tabindex="-1" role="dialog" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content"></div>
                        </div>
                    </div>
                    <div class="modal" id="proposalStatus<?php echo $loan->getId(); ?>" tabindex="-1" role="dialog" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content"></div>
                        </div>
                    </div>
                    <div class="modal" id="bankReport<?php echo $loan->getId(); ?>" tabindex="-1" role="dialog" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="panel-body">
        <div class="panel <?php echo $class; ?>">
            <div class="panel-heading">
                <div class="panel-title"><i class=""></i> Dados Básicos da Proposta</div>
            </div>
            <div class="panel-body">
                <dl class="dl-horizontal">
                    <div class="row">
                        <div class="col-xs-6">
                            <dt>Número da Proposta:</dt>
                            <dd><?php echo str_pad($loan->getId(), 8, '0', STR_PAD_LEFT); ?></dd>
                            <dt>Banco:</dt>
                            <dd><?php echo $loan->getProposal()->getBank()->getName(); ?></dd>
                            <dt>Cidade:</dt>
                            <?php if ($loan->getProposal()->getCompany()->getAddress()): ?>
                            <dd><?php echo ($loan->getProposal()->getCompany()->getAddress()->getCity()) ? $loan->getProposal()->getCompany()->getAddress()->getCity()->getName() : ''; ?></dd>
                            <?php endif; ?>
                            <dt>Lojista:</dt>
                            <dd><?php echo $loan->getShopman()->getName(); ?></dd>
                            <dt>Produto:</dt>
                            <dd><?php echo $loan->getProduct()->getName(); ?></dd>
                            <dt>Data de Cadastro:</dt>
                            <dd><?php echo $this->date($loan->getProposal()->getTimestamp()); ?></dd>
                            <dt>Data Base:</dt>
                            <dd><?php echo $loan->getProposal()->getBaseDate(); ?></dd>
                            <dt>Primeira Parc.:</dt>
                            <dd><?php echo $loan->getProposal()->getStartDate(); ?></dd>
                            <dt>Última Parc.:</dt>
                            <dd><?php echo $loan->getProposal()->getEndDate(); ?></dd>
                            <dt>Observações:</dt>
                            <dd><?php echo $loan->getProposal()->getNotes(); ?></dd>
                        </div>
                        <div class="col-xs-6">
                            <dt>Status da Proposta:</dt>
                            <dd><?php echo $status; ?></dd>
                            <dt>Telefone do Lojista:</dt>
                            <dd><?php echo $this->phone($loan->getShopman()->getPerson()->getContact()->getPhone()); ?></dd>
                            <dt>Empresa:</dt>
                            <dd><?php echo $loan->getProposal()->getCompany()->getFancyName(); ?></dd>
                            <dt>Operador:</dt>
                            <dd><?php echo $loan->getProposal()->getEmployee()->getName(); ?></dd>
                            <dt>Total Consignado:</dt>
                            <dd><?php echo $this->currency($loan->getProposal()->getValue()); ?></dd>
                            <dt>Parcelas:</dt>
                            <dd><?php echo $loan->getProposal()->getParcelAmount(); ?></dd>
                            <dt>Valor da Parcela:</dt>
                            <dd><?php echo $this->currency($loan->getProposal()->getParcelValue()); ?></dd>
                            <dt>Nº do Benefício:</dt>
                            <dd><?php echo $loan->getBenefitNumber(); ?></dd>
                            <dt>UF do Benefício:</dt>
                            <dd><?php echo $loan->getBenefitUf(); ?></dd>
                            <dt>Margem Consignável:</dt>
                            <dd><?php echo $this->currency($loan->getMargin()); ?></dd>
                        </div>
                    </div>
                </dl>
            </div>
        </div>

        <?php echo $this->partial('dtl-proposal/proposal/view-customer', array('class' => $class, 'customer' => $customer)); ?>

    </div>
</div>
