<?php
$title = $this->translate('Fornecedores');
$this->headTitle($title);
?>
<div class="row">
    <div class="col-md-2">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-md-12">
                        <div class="panel-title"><i class="glyphicon glyphicon-search"></i> <?php echo $this->escapeHtml('Filtrar'); ?></div>
                    </div>
                </div>
            </div>
            <div class="panel-body">
                <?php echo $this->partial('dtl-supplier/supplier/search'); ?>
            </div>
        </div>
    </div>
    <div class="col-md-10">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-md-6">
                        <div class="panel-title"><i class="fa fa-truck"></i> <?php echo $this->escapeHtml($title); ?></div>
                    </div>
                    <div class="col-md-6">
                        <div class="btn-group pull-right">
                            <a class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown" href="#"> <i class="glyphicon glyphicon-plus-sign"></i> <?php echo $this->translate('Novo'); ?> &nbsp; <span class="caret"></span></a>
                            <ul class="dropdown-menu pull-right">
                                <li><a href="<?php echo $this->url('dtladmin/dtlsupplier/add', array('type' => base64_encode(0)));
                ?>"><i class="glyphicon glyphicon-user"></i> Pessoa Física</a></li>
                                <li><a href="<?php echo $this->url('dtladmin/dtlsupplier/add', array('type' => base64_encode(1)));
                ?>"><i class="fa fa-legal"></i> Pessoa Jurídica</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <table class="table table-condensed table-hover">
                <tr>
                    <th class="col-lg-1"><?php echo $this->translate('CÓD'); ?></th>
                    <th class=""><?php echo $this->translate('FORNECEDOR'); ?></th>
                    <th class="col-md-2"><?php echo $this->translate('CPF/CNPJ'); ?></th>
                    <th class="col-md-2"><?php echo $this->translate('TELEFONE'); ?></th>
                    <th class="col-md-2"><?php echo $this->translate(''); ?></th>
                </tr>
                <?php if (0 == count($this->supplier)): ?>
                    <tr>
                        <td colspan="10" class="alert alert-info text-center"><?php echo $this->translate('Não há nenhum registro no banco de dados.') ?></td>
                    </tr>
                <?php else: ?>
                    <?php foreach ($this->supplier as $supplier) : ?>
                        <tr>
                            <td><?php echo str_pad($supplier->getId(), 8, '0', STR_PAD_LEFT); ?></td>
                            <td><?php echo $this->escapeHtml($supplier->getPerson()->getName()); ?></td>
                            <?php if ($supplier->getPerson()->getType() == 1): ?>
                                <td><?php echo $this->cnpj($supplier->getPerson()->getLegal()->getCnpj()); ?></td>
                            <?php else: ?>
                                <td><?php echo $this->cpf($supplier->getPerson()->getIndividual()->getCpf()); ?></td>
                            <?php endif; ?>
                            <td><?php echo $this->escapeHtml($this->phone($supplier->getPerson()->getContact()->getPhone())); ?></td>
                            <td>
                                <div class="btn-group btn-group-xs pull-right">
                                    <a class="btn btn-default" data-toggle="tooltip" title="Ver Detalhes" href="<?php
                                    echo $this->url('dtladmin/dtlsupplier/view', array('action' => 'view',
                                        'id' => $supplier->getId()));
                                    ?>"><i class="glyphicon glyphicon-folder-open"></i></a>
                                    <a class="btn btn-default" data-toggle="tooltip" title="Apagar" href="<?php
                                    echo $this->url('dtladmin/dtlsupplier/delete', array('action' => 'delete',
                                        'id' => $supplier->getId()));
                                    ?>"><i class="glyphicon glyphicon-remove"></i></a>
                                    <a class="btn btn-default" data-toggle="tooltip" title="Editar" href="<?php
                                    echo $this->url('dtladmin/dtlsupplier/edit', array('action' => 'edit',
                                        'id' => $supplier->getId(), 'type' => base64_encode($supplier->getPerson()->getType())));
                                    ?>"><i class="glyphicon glyphicon-edit"></i></a>
                                </div>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                <?php endif; ?>
            </table>
            <div class="panel-footer">
                <?php
                $paginationInfo = $this->placeholder('pagination');
                if (!isset($paginationInfo->route)) {
                    $paginationInfo->route = 'dtladmin/dtlsupplier';
                    $paginationInfo->params = array();
                }
                ?>
                <?php echo $this->paginationControl($this->supplier, 'Sliding', 'layout/pagination'); ?>
            </div>
        </div>
    </div>
</div>