<?php
$title = $this->translate('Editar Comissão');
$this->headTitle($title);
$form = $this->form;
$form->setAttribute('action', $this->url('dtladmin/dtlproposal/realty-proposal-commission/edit', array('id' => $this->id)));
$form->prepare();
?>
<h1 class="container-header"><i class="glyphicon glyphicon-male"></i> <?php echo $this->escapeHtml($title); ?></h1>
<?php echo $this->form()->openTag($form); ?>
<div class="form-group">
    <?php $realtyProposalCommission = $form->get('realtyProposalCommission'); ?>
    <?php echo $this->formHidden($realtyProposalCommission->get('id')); ?>
    <div class="row">
        <div class="col-md-2">
            <?php echo $this->formLabel($realtyProposalCommission->get('value')); ?>
            <div class="input-group">
                <?php echo $this->formText($realtyProposalCommission->get('value')); ?>
                <div class="input-group-addon">%</div>
            </div>
        </div>
    </div>
</div>
<?php echo $this->formHidden($form->get('security')); ?>
<div class="btn-group">
    <?php echo $this->formElement($form->get('submit')); ?>
    <?php echo $this->formElement($form->get('cancel')); ?>
</div>
<?php echo $this->form()->closeTag(); ?>
