<?php
$title = $this->translate('Novo Modelo de Veículo');
$this->headTitle($title);
$form = $this->form;
$form->prepare();
?>
<h2 class="container-header"><?php echo $this->escapeHtml($title); ?></h2>
<div class="row">
    <div class="col-md-4">
        <?php echo $this->form()->openTag($form); ?>
        <fieldset>
            <legend><?php echo $title; ?></legend>
            <?php $vehicleModel = $form->get('vehicleModel'); ?>
            <div class="form-group">
                <?php echo $this->formHidden($vehicleModel->get('id')); ?>
                <div class="row">
                    <div class="col-md-12">
                        <?php echo $this->formLabel($vehicleModel->get('brand')); ?>
                        <?php echo $this->formSelect($vehicleModel->get('brand')); ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <?php echo $this->formLabel($vehicleModel->get('type')); ?>
                        <?php echo $this->formSelect($vehicleModel->get('type')); ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <?php echo $this->formLabel($vehicleModel->get('name')); ?>
                        <?php echo $this->formText($vehicleModel->get('name')); ?>
                    </div>
                </div>
                <?php echo $this->formHidden($form->get('security')); ?>
            </div>
            <div class="btn-group btn-group-sm">  
                <?php echo $this->formElement($form->get('submit')); ?>
                <?php echo $this->formElement($form->get('cancel')); ?>
            </div>
        </fieldset>
        <?php echo $this->form()->closeTag(); ?>
    </div>
    <div class="col-md-8">
        <legend>Lista de Modelos</legend>
        <div class="vehicle-model-list">
            <div class="alert alert-info">
                Selecione a Marca e o Tipo de veículo que deseja listar.
            </div>
        </div>
    </div>
</div>