<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'DtlCurrentAccount\Form\CurrentAccount'                 => __DIR__ . '/src/DtlCurrentAccount/Form/CurrentAccount.php',
  'DtlCurrentAccount\Form\Fieldset\CurrentAccount'        => __DIR__ . '/src/DtlCurrentAccount/Form/Fieldset/CurrentAccount.php',
  'DtlCurrentAccount\Form\Fieldset\CreditCard'            => __DIR__ . '/src/DtlCurrentAccount/Form/Fieldset/CreditCard.php',
  'DtlCurrentAccount\Factory\CurrentAccount'              => __DIR__ . '/src/DtlCurrentAccount/Factory/CurrentAccount.php',
  'DtlCurrentAccount\Controller\CurrentAccountController' => __DIR__ . '/src/DtlCurrentAccount/Controller/CurrentAccountController.php',
  'DtlCurrentAccount\Entity\CurrentAccount'               => __DIR__ . '/src/DtlCurrentAccount/Entity/CurrentAccount.php',
  'DtlCurrentAccount\Entity\CreditCard'                   => __DIR__ . '/src/DtlCurrentAccount/Entity/CreditCard.php',
  'DtlCurrentAccount\Module'                              => __DIR__ . '/Module.php',
);
