<?php
$title = $this->translate('Editar Banco');
$this->headTitle($title);
$form = $this->form;
$form->setAttribute('action', $this->url('dtladmin/dtlbank/edit', array('id' => $this->id)));
$form->prepare();
$this->placeholder('title')->set($title);
$this->placeholder('title-icon')->set('<i class="fa fa-bank"></i>')
?>
<div class="page-body">
    <div class="well">
        <?php echo $this->form()->openTag($form); ?>
        <?php $bank = $form->get('bank'); ?>
        <div class="form-group">
            <?php echo $this->formHidden($bank->get('id')); ?>
            <div class="row">
                <div class="col-md-2">
                    <div class="form-group">
                        <?php echo $this->formLabel($bank->get('code')); ?>
                        <?php echo $this->formText($bank->get('code')); ?>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <?php echo $this->formLabel($bank->get('name')); ?>
                        <?php echo $this->formText($bank->get('name')); ?>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <?php echo $this->formLabel($bank->get('url')); ?>
                        <?php echo $this->formText($bank->get('url')); ?>
                    </div>
                </div>
            </div>
        </div>
        <?php echo $this->formHidden($form->get('security')); ?>
        <div class="button-bar">
            <?php echo $this->formElement($form->get('submit')); ?>
            <?php echo $this->formElement($form->get('cancel')); ?>
        </div>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>