<?php
$title = $this->translate('Bancos');
$this->headTitle($title);
$this->placeholder('title')->set($title);
$this->placeholder('title-icon')->set('<i class="fa fa-bank"></i>');
?>
<div class="page-body">
    <div class="widget-box">
        <div class="widget-header">
            <div class="widget-caption">
                <div class="widget-icon"><i class="fa fa-bars"></i></div>
                <?php // echo $this->translate('Gerencie os bancos.'); ?>
            </div>
            <div class="widget-toolbar">
                <div class="btn-group">
                    <a class="btn btn-normal btn-success" href="<?php echo $this->url('dtladmin/dtlbank/add'); ?>"><i class="fa fa-plus-circle"></i>&nbsp;<?php echo $this->translate('Novo Banco'); ?></a>
                </div>
            </div>
        </div>
        <div class="widget-body">
            <div class="widget-main">
                <table class="table table-striped table-hover table-bordered ">
                    <thead>
                        <tr>
                            <th><?php echo $this->translate('BANCO'); ?></th>
                            <th class="col-md-1"><?php echo $this->translate('Nº'); ?></th>
                            <th><?php echo $this->translate('WEB'); ?></th>
                            <th class="text-right"></th>
                        </tr>
                    </thead>
                    <?php if (!count($this->bank)): ?>
                        <tbody>
                            <tr>
                                <td colspan="10" class="alert alert-info text-center"><?php echo $this->translate('Nenhum registro encontrado.') ?></td>
                            </tr>
                        <?php else: ?>
                            <?php foreach ($this->bank as $bank) : ?>
                                <tr>
                                    <td><?php echo $this->escapeHtml($bank->getName()); ?></td>
                                    <td><?php echo str_pad($bank->getCode(), 3, '0', STR_PAD_LEFT); ?></td>
                                    <td><?php echo $this->escapeHtml($bank->getUrl()); ?></td>
                                    <td>
                                        <div class="text-right">
                                            <a class="btn btn-xs btn-info icon-only" href="<?php echo $this->url('dtladmin/dtlbank/edit', array('id' => $bank->getId()))
                                ?>"><i class="fa fa-edit"></i></a>
                                            <a data-toggle="modal" data-target="#dtlBankDelete<?php echo $bank->getId(); ?>" class="btn btn-xs btn-danger icon-only" href="<?php echo $this->url('dtladmin/dtlbank/delete', array('id' => $bank->getId()))
                                ?>"><i class="fa fa-times"></i></a>
                                        </div>
                                    </td>
                                </tr>
                            <div class="modal fade" role="modal" aria-hidden="true" tabindex="-1" id="dtlBankDelete<?php echo $bank->getId(); ?>">
                                <div class="modal-dialog">
                                    <div class="modal-content"></div>
                                </div>
                            </div>
                        <?php endforeach; ?>
                    <?php endif; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
