<?php
$title = $this->translate('Interessados');
$this->headTitle($title);
?>
<div class="row">
    <div class="col-md-2 hidden-print">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-md-12">
                        <div class="panel-title"><i class="glyphicon glyphicon-search"></i> <?php echo $this->escapeHtml('Filtrar'); ?></div>
                    </div>
                </div>
            </div>
            <div class="panel-body">
                <?php echo $this->partial('dtl-pretender/pretender/search'); ?>
            </div>
        </div>
    </div>
    <div class="col-md-10">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-md-6">
                        <div class="panel-title"><i class="fa fa-truck"></i> <?php echo $this->escapeHtml($title); ?></div>
                    </div>
                    <div class="col-md-6 hidden-print">
                        <div class="btn-group pull-right">
                            <a onclick="javascript: window.print();" class="btn btn-default btn-sm" href="#"> <i class="fa fa-print"></i> <?php echo $this->translate('Imprimir'); ?></a>
                            <a class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown" href="#"> <i class="glyphicon glyphicon-plus-sign"></i> <?php echo $this->translate('Novo'); ?> &nbsp; <span class="caret"></span></a>
                            <ul class="dropdown-menu pull-right">
                                <li><a href="<?php echo $this->url('dtladmin/dtlpretender/add', array('type' => base64_encode(0)));
                ?>"><i class="glyphicon glyphicon-user"></i> Pessoa Física</a></li>
                                <li><a href="<?php echo $this->url('dtladmin/dtlpretender/add', array('type' => base64_encode(1)));
                ?>"><i class="fa fa-legal"></i> Pessoa Jurídica</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <table class="table table-condensed table-hover">
                <tr>
                    <th class="col-lg-1"><?php echo $this->translate('CÓD'); ?></th>
                    <th class=""><?php echo $this->translate('INTERESSADO'); ?></th>
                    <th class=""><?php echo $this->translate('TIPO DE IMÓVEL'); ?></th>
                    <th class=""><?php echo $this->translate('VL. DO IMÓVEL'); ?></th>
                    <th class=""><?php echo $this->translate('VL. SOLICITADO'); ?></th>
                    <th class=""><?php echo $this->translate('TELEFONE'); ?></th>
                    <th class=""><?php echo $this->translate('CELULAR'); ?></th>
                    <th class=""><?php echo $this->translate(''); ?></th>
                </tr>
                <?php if (0 == count($this->pretender)): ?>
                    <tr>
                        <td colspan="10" class="alert alert-info text-center"><?php echo $this->translate('Não há nenhum registro no banco de dados.') ?></td>
                    </tr>
                <?php else: ?>
                    <?php foreach ($this->pretender as $pretender) : ?>
                        <tr>
                            <td><?php echo str_pad($pretender->getId(), 8, '0', STR_PAD_LEFT); ?></td>
                            <td><?php echo $this->escapeHtml($pretender->getPerson()->getName()); ?></td>
                            <td><?php echo $this->escapeHtml($pretender->getRealtyType()->getName()); ?></td>
                            <td><?php echo $this->escapeHtml($this->currency($pretender->getValue())); ?></td>
                            <td><?php echo $this->escapeHtml($this->currency($pretender->getValue())); ?></td>
                            <td><?php echo $this->escapeHtml($this->phone($pretender->getPerson()->getContact()->getPhone())); ?></td>
                            <td><?php echo $this->escapeHtml($this->phone($pretender->getPerson()->getContact()->getCell())); ?></td>
                            <td class="hidden-print">
                                <div class="btn-group btn-group-xs pull-right">
                                    <a class="btn btn-default" data-toggle="tooltip" title="Ver Detalhes" href="<?php
                                    echo $this->url('dtladmin/dtlpretender/view', array('action' => 'view',
                                        'id' => $pretender->getId()));
                                    ?>"><i class="glyphicon glyphicon-folder-open"></i></a>
                                    <a class="btn btn-default" data-toggle="tooltip" title="Apagar" href="<?php
                                    echo $this->url('dtladmin/dtlpretender/delete', array('action' => 'delete',
                                        'id' => $pretender->getId()));
                                    ?>"><i class="glyphicon glyphicon-remove"></i></a>
                                    <a class="btn btn-default" data-toggle="tooltip" title="Editar" href="<?php
                                    echo $this->url('dtladmin/dtlpretender/edit', array('action' => 'edit',
                                        'id' => $pretender->getId(), 'type' => base64_encode($pretender->getPerson()->getType())));
                                    ?>"><i class="glyphicon glyphicon-edit"></i></a>
                                </div>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                <?php endif; ?>
            </table>
            <div class="panel-footer hidden-print">
                <?php
                $paginationInfo = $this->placeholder('pagination');
                if (!isset($paginationInfo->route)) {
                    $paginationInfo->route = 'dtladmin/dtlpretender';
                    $paginationInfo->params = array();
                }
                ?>
                <?php echo $this->paginationControl($this->pretender, 'Sliding', 'layout/pagination'); ?>
            </div>
        </div>
    </div>
</div>