<?php echo $this->doctype(); ?>
<html>
    <head>
        <?php
        echo $this->headMeta()
                ->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8')
                ->appendHttpEquiv('Content-Language', 'pt-BR')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
                ->appendHttpEquiv('Cache-Control', 'max-age=31536000; public')
                ->appendHttpEquiv('Last-Modified', gmdate('D, d M Y H:i:s') . " GMT")
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ?>

        <?php echo $this->headTitle('Impressão - Valoriza 2.0')->setSeparator(' - ')->setAutoEscape(false) ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/application-print.css', array('media' => 'print, screen'))
//                ->prependStylesheet($this->basePath() . '/css/jquery-ui/smoothness/jquery-ui-1.10.3.custom.min.css')
//                ->prependStylesheet($this->basePath() . '/font-awesome/css/font-awesome.min.css')
//                ->prependStylesheet($this->basePath() . '/bootstrap/css/bootstrap-theme.css')
                ->prependStylesheet($this->basePath() . '/bootstrap/css/bootstrap.min.css', array('media' => 'print, screen'))
        ?>
        <!--[if IE 7]>
            <link rel="stylesheet" href="/font-awesome/css/font-awesome-ie7.min.css">
        <![endif]-->
        <!--[if lte IE 8]><script language="javascript" type="text/javascript" src="/js/excanvas.min.js"></script><![endif]-->
        <?php
//        echo $this->headScript()->prependFile($this->basePath() . '/js/application.js', 'text/javascript', array('charset' => 'UTF-8'))
//                ->prependFile($this->basePath() . '/js/jquery.price.js')
//                ->prependFile($this->basePath() . '/js/jquery-masked.js')
//                ->prependFile($this->basePath() . '/bootstrap/js/bootstrap.min.js')
//                ->prependFile($this->basePath() . '/js/jquery.ui.datepicker-pt-BR.js')
//                ->prependFile($this->basePath() . '/js/jquery-ui.min.js', 'text/javascript', array('async' => 'async'))
//                ->prependFile($this->basePath() . '/js/jquery.min.js', 'text/javascript', array('async' => 'async'))
//                ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
//                ->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ?>
    </head>
    <body>
        <div class="app-print">
            <?php echo $this->content; ?>
            <hr/>
        </div>
    </body>
</html>
