<?php

// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'DtlDepartment\Form\Fieldset\Department' => __DIR__ . '/src/DtlDepartment/Form/Fieldset/Department.php',
    'DtlDepartment\Form\Department' => __DIR__ . '/src/DtlDepartment/Form/Department.php',
    'DtlDepartment\Factory\Department' => __DIR__ . '/src/DtlDepartment/Factory/Department.php',
    'DtlDepartment\Controller\DepartmentController' => __DIR__ . '/src/DtlDepartment/Controller/DepartmentController.php',
    'DtlDepartment\Entity\Department' => __DIR__ . '/src/DtlDepartment/Entity/Department.php',
    'DtlDepartment\Module' => __DIR__ . '/Module.php',
);
