<?php
$title = $this->translate('Usuários');
$this->headTitle($title);
$this->placeholder('title')->set($title);
$this->placeholder('title-icon')->set('<i class="fa fa-lock"></i>')
?>
<div class="page-body">
    <div class="widget-box">
        <div class="widget-header">
            <div class="widget-caption">
                <?php echo $this->translate('Gerencie seus usuários'); ?>
            </div>
            <div class="widget-toolbar">
                <div class="btn-group">
                    <a class="btn btn-success btn-normal" href="<?php echo $this->url('dtladmin/dtluser/add'); ?>">
                        <i class="fa fa-plus-circle"></i> <?php echo $this->translate('Novo Usuário'); ?>
                    </a>
                </div>
            </div>
        </div>
        <div class="widget-body">
            <div class="widget-main">
                <table class="table table-striped  table-hover table-bordered" id="user-table">
                    <thead>
                        <tr>
                            <th>CÓD</th>
                            <th><?php echo $this->translate('NOME'); ?></th>
                            <th><?php echo $this->translate('USUÁRIO'); ?></th>
                            <th><?php echo $this->translate('E-MAIL'); ?></th>
                            <th class="text-right"></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->users as $user): ?>
                            <tr>
                                <td><?php echo $user->getId(); ?></td>
                                <td><?php echo $user->getDisplayName(); ?></td>
                                <td><?php echo $user->getUsername(); ?></td>
                                <td><?php echo $user->getEmail(); ?></td>
                                <td class="text-right">
                                    <div class="btn-group-xs">
                                        <a class="btn btn-info icon-only btn-xs" href="<?php echo $this->url('dtladmin/dtluser/edit', array('id' => $user->getId())); ?>">
                                            <i class="fa fa-edit"></i>
                                        </a>
                                        <a data-toggle="modal" data-target="#dtlUserDelete<?php echo $user->getId(); ?>" class="btn btn-danger icon-only btn-xs" href="<?php echo $this->url('dtladmin/dtluser/delete', array('id' => $user->getId())); ?>">
                                            <i class="fa fa-times"></i>
                                        </a>
                                    </div>
                                </td>
                            </tr>
                        <div class="modal modal-danger fade" role="modal" aria-hidden="true" tabindex="-1" id="dtlUserDelete<?php echo $user->getId(); ?>">
                            <div class="modal-dialog">
                                <div class="modal-content"></div>
                            </div>
                        </div>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
