<?php $total = 0; ?>
<div class="panel panel-warning">
    <div class="panel-heading">
        <div class="panel-title">
            <i class="fa fa-truck"></i> 
            Listagem de Veículos
        </div>
    </div>
    <?php if (0 == count($this->vehicles)): ?>
        <div class="panel-body">
            <div class="alert alert-info">
                <?php echo $this->translate('Nenhum registro encontrado.') ?>
            </div>
        </div>
    <?php else: ?>
        <table class="table table-condensed table-hover">
            <tr>
                <th class=""><?php echo $this->translate('MARCA'); ?></th>
                <th class=""><?php echo $this->translate('MODELO'); ?></th>
                <th class=""><?php echo $this->translate('VERSÃO'); ?></th>
                <th class=""><?php echo $this->translate('ANO/MODELO'); ?></th>
                <th class=""><?php echo $this->translate('PLACA'); ?></th>
                <th class="" colspan="2"><?php echo $this->translate('VALOR'); ?></th>
            </tr>
            
            <?php foreach ($this->vehicles as $key => $vehicle) : ?>
                <tr>
                    <td><?php echo $this->escapeHtml($vehicle['brandName']); ?></td>
                    <td><?php echo $this->escapeHtml($vehicle['modelName']); ?></td>
                    <td><?php echo $this->escapeHtml($vehicle['versionName']); ?></td>
                    <td>
                        <?php echo $vehicle['year']; ?>
                        <?php echo ($vehicle['yearModel']) ? " / " . $vehicle['yearModel'] : ""; ?>
                    </td>
                    <td><?php echo $this->escapeHtml($vehicle['plate']); ?></td>
                    <td><?php echo $this->currency($vehicle['value']); ?></td>
                    <td>
                        <div class="btn-group btn-group-xs pull-right">
                            <a class="btn btn-default btn-xs" href="javascript: vehicleProposalDelete('<?php echo $key ?>', '<?php echo $vehicle['id']?>')"><i class="glyphicon glyphicon-remove"></i></a>
                        </div>
                    </td>
                </tr>
                <?php $total += $vehicle['value']; ?>
            <?php endforeach; ?>
            <tr class="text-success">
                <td colspan="5" class="text-right"><b>TOTAL:</b></td>
                <td colspan="2"><b><?php echo $this->currency($total); ?></b></td>
            </tr>
        </table>
    <?php endif; ?>
</div>
<script type="text/javascript">
    !function($) {
        $(function() {
            $('#value').val('<?php echo $this->currency($total, false); ?>');
        });
    }(window.jQuery);
</script>