<?php
$title = $this->translate('Nova Forma de Pagamento');
$this->headTitle($title);
$form = $this->form;
$form->setAttribute('action', $this->url('dtladmin/dtlpaymenttype/add'));
$form->prepare();
$this->placeholder('title')->set($title);
$this->placeholder('title-icon')->set('<i class="fa fa-money"></i>');
?>
<?php echo $this->form()->openTag($form); ?>
<div class="modal-header">
    <h3 class="header-title"><i class="fa fa-money"></i> <?php echo $this->escapeHtml($title); ?></h3>
</div>
<div class="modal-body">
    <?php $paymentType = $form->get('paymentType'); ?>
    <?php echo $this->formHidden($paymentType->get('id')); ?>
    <div class="form-group">
        <?php echo $this->formLabel($paymentType->get('name')); ?>
        <?php echo $this->formText($paymentType->get('name')); ?>
    </div>
</div>
<div class="modal-footer">
    <?php echo $this->formElement($form->get('save')); ?>
    <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="fa fa-times"></i> <?php echo $this->translate('Cancelar'); ?></button>
</div>
<?php echo $this->form()->closeTag(); ?>
<script type="text/javascript">
    $(document).ready(function () {
        $('#paymentType').bootstrapValidator();
    });
</script>