<?php
$title = $this->translate('Formas de Pagamento');
$this->headTitle($title);
$this->placeholder('title')->set($title);
$this->placeholder('title-icon')->set('<i class="fa fa-money"></i>');
?>
<div class="page-body">
    <div class="widget-box">
        <div class="widget-header">
            <div class="widget-caption">
                <div class="widget-icon">
                    <i class="fa fa-bars"></i>
                </div>
                <?php echo $this->escapeHtml($title); ?>
            </div>
            <div class="widget-toolbar">
                <div class="btn-group">
                    <a data-toggle="modal" data-target="#paymentTypeNew" class="btn btn-normal btn-success" href="<?php echo $this->url('dtladmin/dtlpaymenttype/add'); ?>"> <i class="fa fa-plus-circle"></i> <?php echo $this->translate('Nova Forma da Pagamento'); ?></a>
                </div>
            </div>
        </div>
        <div class="widget-body">
            <div class="widget-main">
                <table class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th><?php echo $this->translate('FORMA DE PAGAMENTO'); ?></th>
                            <th class="text-right"></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->paymentType as $paymentType) : ?>
                            <tr>
                                <td><?php echo $this->escapeHtml($paymentType->getName()); ?></td>
                                <td>
                                    <div class="text-right">
                                        <a data-toggle="modal" data-target="#paymentTypeEdit" class="btn btn-info btn-xs icon-only" href="<?php echo $this->url('dtladmin/dtlpaymenttype/edit', array('id' => $paymentType->getId())); ?>"><i class="fa fa-edit"></i></a>
                                        <a data-toggle="modal" data-target="#paymentTypeDelete" class="btn btn-danger btn-xs icon-only" href="<?php echo $this->url('dtladmin/dtlpaymenttype/delete', array('id' => $paymentType->getId())); ?>"><i class="fa fa-times"></i></a>
                                    </div>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<div class="modal modal-success fade" aria-hidden="true" tabindex="-1" id="paymentTypeNew" role="modal">
    <div class="modal-dialog"><div class="modal-content"></div> </div>
</div>
<div class="modal modal-danger fade" aria-hidden="true" tabindex="-1" id="paymentTypeDelete" role="modal">
    <div class="modal-dialog"><div class="modal-content"></div> </div>
</div>
<div class="modal modal-primary fade" aria-hidden="true" tabindex="-1" id="paymentTypeEdit" role="modal">
    <div class="modal-dialog"><div class="modal-content"></div> </div>
</div>
