<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <?php
        echo $this->headMeta()
                ->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8')
                ->appendHttpEquiv('Content-Language', 'pt-BR')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
                ->appendHttpEquiv('Cache-Control', 'max-age=31536000; public')
                ->appendHttpEquiv('Last-Modified', gmdate('D, d M Y H:i:s') . " GMT")
                ->appendName('viewport', 'width=device-width, initial-scale=1.0');

        echo $this->headScript()
                ->prependFile($this->basePath() . '/js/application.js', 'text/javascript', array('charset' => 'UTF-8'))
                ->prependFile($this->basePath() . '/js/jquery.mask.min.js')
                ->prependFile($this->basePath() . '/datepicker/js/bootstrap-datetimepicker.min.js')
                ->prependFile($this->basePath() . '/js/moment.min.js', 'text/javascript', array('async' => 'async'))
                ->prependFile($this->basePath() . '/js/jquery.min.js', 'text/javascript', array('async' => 'async'))
        ?>
    </head>
    <body>
        <div class="container-fluid">
            <?php echo $this->content; ?>
        </div>
        <?php
        echo $this->inlineScript();
        ?>
        <script type="text/javascript">
            $(function () {
                $('.datepicker').datetimepicker({
                    locale: 'pt-br',
                    format: 'L',
                    useCurrent: false
                });
            });
        </script>
    </body>
</html>
