<?php

return [
    'bjyauthorize' => [
        'default_role' => 'guest',
        'template' => 'application/error/403',
        /* this module uses a meta-role that inherits from any roles that should
         * be applied to the active user. the identity provider tells us which
         * roles the "identity role" should inherit from.
         *
         * for ZfcUser, this will be your default identity provider
         */
//        'identity_provider' => \BjyAuthorize\Provider\Identity\ZfcUserZendDb::class,

        /* If you only have a default role and an authenticated role, you can
         * use the 'AuthenticationIdentityProvider' to allow/restrict access
         * with the guards based on the state 'logged in' and 'not logged in'.
         *
         * 'default_role'       => 'guest',         // not authenticated
         * 'authenticated_role' => 'user',          // authenticated
         * 'identity_provider'  => \BjyAuthorize\Provider\Identity\AuthenticationIdentityProvider::class,
         */
        'identity_provider' => \BjyAuthorize\Provider\Identity\AuthenticationIdentityProvider::class,
        /* role providers simply provide a list of roles that should be inserted
         * into the Zend\Acl instance. the module comes with two providers, one
         * to specify roles in a config file and one to load roles using a
         * Zend\Db adapter.
         */
        'role_providers' => [
            /* here, 'guest' and 'user are defined as top-level roles, with
             * 'admin' inheriting from user
             */
            \BjyAuthorize\Provider\Role\Config::class => [
                'guest' => [],
                'user' => [
                    'children' => [
                        'admin' => [],
                    ],
                ],
            ],
        // this will load roles from the user_role table in a database
// format: user_role(role_id(varchar], parent(varchar))
//            \BjyAuthorize\Provider\Role\ObjectRepositoryProvider::class => [
//                'table'                 => 'user_role',
//                'identifier_field_name' => 'id',
//                'role_id_field'         => 'role_id',
//                'parent_role_field'     => 'parent_id',
//            ],
// this will load roles from
// the 'BjyAuthorize\Provider\Role\ObjectRepositoryProvider' service
//            \BjyAuthorize\Provider\Role\ObjectRepositoryProvider::class => [
//                'role_entity_class' => 'User\Entity\Role',
//                'object_manager' => 'doctrine.entitymanager.orm_default',
//            ],
        ],
        // resource providers provide a list of resources that will be tracked
// in the ACL. like roles, they can be hierarchical
        'resource_providers' => [
            \BjyAuthorize\Provider\Resource\Config::class => [
                'menu' => [],
                'proposal_actions' => [],
            ],
        ],
        /* rules can be specified here with the format:
         * [roles (array], resource, [privilege (array|string], assertion])
         * assertions will be loaded using the service manager and must implement
         * Zend\Acl\Assertion\AssertionInterface.
         * *if you use assertions, define them using the service manager!*
         */
        'rule_providers' => [
            \BjyAuthorize\Provider\Rule\Config::class => [
                'allow' => [
// allow guests and users (and admins, through inheritance)
// the "wear" privilege on the resource "pants"
                    [['admin'], 'proposal_actions', 'all'],
                    [['user', 'admin'], 'proposal_actions', 'restricted'],
                    [['admin'], 'menu', 'all'],
                    [['user', 'admin'], 'menu', 'restricted'],
                ],
                // Don't mix allow/deny rules if you are using role inheritance.
// There are some weird bugs.
                'deny' => [
// ...
                ],
            ],
        ],
        /* Currently, only controller and route guards exist
         *
         * Consider enabling either the controller or the route guard depending on your needs.
         */
        'guards' => [
            /* If this guard is specified here (i.e. it is enabled], it will block
             * access to all controllers and actions unless they are specified here.
             * You may omit the 'action' index to allow access to the entire controller
             */
            \BjyAuthorize\Guard\Controller::class => [
//                ['controller' => 'index', 'action' => 'index', 'roles' => ['guest', 'user']],
// You can also specify an array of actions or an array of controllers (or both)
// allow "guest" and "admin" to access actions "list" and "manage" on these "index",
// "static" and "console" controllers
//                ['controller' => 'zfcuser', 'roles' => ['user']],
// Below is the default index action used by the ZendSkeletonApplication
                ['controller' => 'Application\Controller\Index', 'roles' => ['guest', 'user']],
                ['controller' => 'ZFTool\Controller\Create', 'roles' => ['guest']],
                ['controller' => 'Admin\Controller\Index', 'roles' => ['guest', 'user', 'admin']],
                ['controller' => 'Proposal\Controller\Proposal', 'roles' => ['user', 'admin']],
                ['controller' => 'Proposal\Controller\VehicleProposal', 'roles' => ['user', 'admin']],
                ['controller' => 'Proposal\Controller\Loan', 'roles' => ['user', 'admin']],
                ['controller' => 'Proposal\Controller\RealtyProposal', 'roles' => ['user', 'admin']],
                ['controller' => 'Proposal\Controller\CaixaProposal', 'roles' => ['user', 'admin']],
                ['controller' => 'Employee\Controller\Employee', 'roles' => ['admin']],
                ['controller' => 'Customer\Controller\Customer', 'roles' => ['user', 'admin']],
                ['controller' => 'Customer\Controller\CustomerPatrimony', 'roles' => ['user', 'admin']],
                ['controller' => 'Customer\Controller\CustomerVehicle', 'roles' => ['user', 'admin']],
                ['controller' => 'Customer\Controller\CustomerBankAccount', 'roles' => ['user', 'admin']],
                ['controller' => 'Customer\Controller\CustomerReference', 'roles' => ['user', 'admin']],
                ['controller' => 'Shopman\Controller\Shopman', 'roles' => ['user', 'admin']],
                ['controller' => 'Shopman\Controller\ShopmanProduct', 'roles' => ['admin']],
                ['controller' => 'Seller\Controller\Seller', 'roles' => ['user', 'admin']],
                ['controller' => 'Realtor\Controller\Realtor', 'roles' => ['admin']],
                ['controller' => 'Supplier\Controller\Supplier', 'roles' => ['admin']],
                ['controller' => 'Financial\Controller\Index', 'roles' => ['admin']],
                ['controller' => 'Financial\Controller\Receivable', 'roles' => ['admin']],
                ['controller' => 'Financial\Controller\Payable', 'roles' => ['admin']],
                ['controller' => 'Financial\Controller\Revenue', 'roles' => ['admin']],
                ['controller' => 'Financial\Controller\Expense', 'roles' => ['admin']],
                ['controller' => 'Financial\Controller\Cash', 'roles' => ['admin']],
                ['controller' => 'Company\Controller\Company', 'roles' => ['admin']],
                ['controller' => 'Product\Controller\Category', 'roles' => ['admin']],
                ['controller' => 'Product\Controller\Product', 'roles' => ['admin']],
                ['controller' => 'Business\Controller\Business', 'roles' => ['admin']],
                ['controller' => 'Bank\Controller\Bank', 'roles' => ['admin']],
                ['controller' => 'Currency\Controller\Currency', 'roles' => ['admin']],
                ['controller' => 'CurrentAccount\Controller\CurrentAccount', 'roles' => ['admin']],
                ['controller' => 'PaymentType\Controller\PaymentType', 'roles' => ['admin']],
                ['controller' => 'AccountingItem\Controller\AccountingItem', 'roles' => ['admin']],
                ['controller' => 'DocumentType\Controller\DocumentType', 'roles' => ['admin']],
                ['controller' => 'EmployeeStatus\Controller\EmployeeStatus', 'roles' => ['admin']],
                ['controller' => 'Occupation\Controller\Occupation', 'roles' => ['admin']],
                ['controller' => 'Office\Controller\Office', 'roles' => ['admin']],
                ['controller' => 'Department\Controller\Department', 'roles' => ['admin']],
                ['controller' => 'Vehicle\Controller\Index', 'roles' => ['user', 'admin']],
                ['controller' => 'Vehicle\Controller\VehicleBrand', 'roles' => ['admin']],
                ['controller' => 'Vehicle\Controller\VehicleType', 'roles' => ['user', 'admin']],
                ['controller' => 'Vehicle\Controller\VehicleModel', 'roles' => ['user', 'admin']],
                ['controller' => 'Vehicle\Controller\VehicleVersion', 'roles' => ['user', 'admin']],
                ['controller' => 'Proposal\Controller\RealtyProposalCommission', 'roles' => ['admin']],
                ['controller' => 'Realty\Controller\RealtyType', 'roles' => ['admin']],
                ['controller' => 'Realty\Controller\RealtyFeature', 'roles' => ['user', 'admin']],
                ['controller' => 'zfcuser', 'roles' => ['guest', 'user']],
                ['controller' => 'Report\Controller\Index', 'roles' => ['admin']],
                ['controller' => 'Report\Controller\Caixa', 'roles' => ['admin']],
                ['controller' => 'fileupload_examples', 'roles' => ['user', 'admin']],
                ['controller' => 'fileupload_prgexamples', 'roles' => ['user', 'admin']],
                ['controller' => 'fileupload_progressexamples', 'roles' => ['user', 'admin']],
                ['controller' => 'DtlFile\Controller\File', 'roles' => ['user', 'admin']],
                ['controller' => 'Pretender\Controller\Pretender', 'roles' => ['user', 'admin']],
                ['controller' => 'DtlLocation\Controller\Country', 'roles' => ['user', 'admin']],
                ['controller' => 'DtlLocation\Controller\State', 'roles' => ['user', 'admin']],
                ['controller' => 'DtlLocation\Controller\City', 'roles' => ['user', 'admin']],
            ],
            /* If this guard is specified here (i.e. it is enabled], it will block
             * access to all routes unless they are specified here.
             */
            \BjyAuthorize\Guard\Route::class => [
                ['route' => 'home', 'roles' => ['guest', 'user']],
                ['route' => 'zftool-create-module', 'roles' => ['guest']],
                ['route' => 'zftool-create-controller', 'roles' => ['guest']],
                ['route' => 'zftool-create-action', 'roles' => ['guest']],
                ['route' => 'admin', 'roles' => ['guest', 'user', 'admin']],
                ['route' => 'admin/fixaddress', 'roles' => ['guest', 'user', 'admin']],
                ['route' => 'zfcuser', 'roles' => ['guest']],
                ['route' => 'zfcuser/logout', 'roles' => ['user']],
                ['route' => 'zfcuser/login', 'roles' => ['guest']],
                ['route' => 'zftool-create-action', 'roles' => ['guest']],
                ['route' => 'admin/proposal', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/proposal', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/proposal/calculate', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/proposal/deletecustomerbankaccount', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/proposal/addcustomerbankaccount', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/proposal/listcustomerbankaccount', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/proposal/deletecustomervehicle', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/proposal/addcustomervehicle', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/proposal/listcustomervehicle', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/proposal/deletecustomerpatrimony', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/proposal/addcustomerpatrimony', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/proposal/listcustomerpatrimony', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/proposal/deletecustomerreference', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/proposal/addcustomerreference', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/proposal/listcustomerreference', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/proposal/print', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/proposal/printHistory', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/proposal/upload', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/vehicle-proposal', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/vehicle-proposal/pre', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/vehicle-proposal/add', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/vehicle-proposal/edit', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/vehicle-proposal/view', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/vehicle-proposal/delete', 'roles' => ['admin']],
                ['route' => 'admin/proposal/vehicle-proposal/search', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/vehicle-proposal/bank', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/vehicle-proposal/history', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/vehicle-proposal/status', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/vehicle-proposal/deletevehicle', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/vehicle-proposal/addvehicle', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/vehicle-proposal/listvehicles', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/vehicle-proposal/calculateValue', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/vehicle-proposal/print', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/vehicle-proposal/exportCsv', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/loan', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/loan/pre', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/loan/add', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/loan/edit', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/loan/view', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/loan/delete', 'roles' => ['admin']],
                ['route' => 'admin/proposal/loan/search', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/loan/bank', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/loan/history', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/loan/status', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/loan/exportPdf', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/loan/exportCsv', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/realty-proposal', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/realty-proposal/pre', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/realty-proposal/add', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/realty-proposal/edit', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/realty-proposal/view', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/realty-proposal/delete', 'roles' => ['admin']],
                ['route' => 'admin/proposal/realty-proposal/search', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/realty-proposal/bank', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/realty-proposal/history', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/realty-proposal/status', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/realty-proposal/evaluation', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/realty-proposal/evaluationEdit', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/realty-proposal/exportCsv', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/realty-proposal/calculate', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/realty-proposal/upload', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/realty-proposal/deleteFile', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/realty-proposal-commission', 'roles' => ['admin']],
                ['route' => 'admin/proposal/realty-proposal-commission/add', 'roles' => ['admin']],
                ['route' => 'admin/proposal/realty-proposal-commission/edit', 'roles' => ['admin']],
                ['route' => 'admin/proposal/realty-proposal-commission/delete', 'roles' => ['admin']],
                ['route' => 'admin/proposal/caixa-proposal', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/caixa-proposal/pre', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/caixa-proposal/add', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/caixa-proposal/edit', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/caixa-proposal/view', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/caixa-proposal/delete', 'roles' => ['admin']],
                ['route' => 'admin/proposal/caixa-proposal/search', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/caixa-proposal/bank', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/caixa-proposal/history', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/caixa-proposal/status', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/caixa-proposal/deleteproduct', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/caixa-proposal/addproduct', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/caixa-proposal/listproducts', 'roles' => ['user', 'admin']],
                ['route' => 'admin/proposal/caixa-proposal/exportCsv', 'roles' => ['user', 'admin']],
                ['route' => 'admin/employee', 'roles' => ['admin']],
                ['route' => 'admin/employee/add', 'roles' => ['admin']],
                ['route' => 'admin/employee/edit', 'roles' => ['admin']],
                ['route' => 'admin/employee/delete', 'roles' => ['admin']],
                ['route' => 'admin/employee/view', 'roles' => ['admin']],
                ['route' => 'admin/employee/launchsalary', 'roles' => ['admin']],
                ['route' => 'admin/customer', 'roles' => ['user', 'admin']],
                ['route' => 'admin/customer/add', 'roles' => ['user', 'admin']],
                ['route' => 'admin/customer/edit', 'roles' => ['user', 'admin']],
                ['route' => 'admin/customer/delete', 'roles' => ['user', 'admin']],
                ['route' => 'admin/customer/view', 'roles' => ['user', 'admin']],
                ['route' => 'admin/customer/exportCsv', 'roles' => ['user', 'admin']],
                ['route' => 'admin/customer/customer-patrimony', 'roles' => ['user', 'admin']],
                ['route' => 'admin/customer/customer-patrimony/add', 'roles' => ['user', 'admin']],
                ['route' => 'admin/customer/customer-patrimony/edit', 'roles' => ['user', 'admin']],
                ['route' => 'admin/customer/customer-patrimony/delete', 'roles' => ['user', 'admin']],
                ['route' => 'admin/customer/customer-patrimony/list', 'roles' => ['user', 'admin']],
                ['route' => 'admin/customer/customer-patrimony/post', 'roles' => ['user', 'admin']],
                ['route' => 'admin/customer/customer-vehicle', 'roles' => ['user', 'admin']],
                ['route' => 'admin/customer/customer-vehicle/add', 'roles' => ['user', 'admin']],
                ['route' => 'admin/customer/customer-vehicle/edit', 'roles' => ['user', 'admin']],
                ['route' => 'admin/customer/customer-vehicle/delete', 'roles' => ['user', 'admin']],
                ['route' => 'admin/customer/customer-vehicle/list', 'roles' => ['user', 'admin']],
                ['route' => 'admin/customer/customer-vehicle/post', 'roles' => ['user', 'admin']],
                ['route' => 'admin/customer/customer-bank-account', 'roles' => ['user', 'admin']],
                ['route' => 'admin/customer/customer-bank-account/add', 'roles' => ['user', 'admin']],
                ['route' => 'admin/customer/customer-bank-account/delete', 'roles' => ['user', 'admin']],
                ['route' => 'admin/customer/customer-bank-account/edit', 'roles' => ['user', 'admin']],
                ['route' => 'admin/customer/customer-bank-account/delete', 'roles' => ['user', 'admin']],
                ['route' => 'admin/customer/customer-bank-account/list', 'roles' => ['user', 'admin']],
                ['route' => 'admin/customer/customer-bank-account/post', 'roles' => ['user', 'admin']],
                ['route' => 'admin/customer/customer-reference', 'roles' => ['user', 'admin']],
                ['route' => 'admin/customer/customer-reference/add', 'roles' => ['user', 'admin']],
                ['route' => 'admin/customer/customer-reference/delete', 'roles' => ['user', 'admin']],
                ['route' => 'admin/customer/customer-reference/edit', 'roles' => ['user', 'admin']],
                ['route' => 'admin/customer/customer-reference/delete', 'roles' => ['user', 'admin']],
                ['route' => 'admin/customer/customer-reference/list', 'roles' => ['user', 'admin']],
                ['route' => 'admin/customer/customer-reference/post', 'roles' => ['user', 'admin']],
                ['route' => 'admin/shopman', 'roles' => ['admin']],
                ['route' => 'admin/shopman/add', 'roles' => ['admin']],
                ['route' => 'admin/shopman/edit', 'roles' => ['admin']],
                ['route' => 'admin/shopman/view', 'roles' => ['admin']],
                ['route' => 'admin/shopman/delete', 'roles' => ['admin']],
                ['route' => 'admin/shopman/fill', 'roles' => ['user', 'admin']],
                ['route' => 'admin/shopman/fillproduct', 'roles' => ['user', 'admin']],
                ['route' => 'admin/shopman/shopman-product', 'roles' => ['admin']],
                ['route' => 'admin/shopman/shopman-product/list', 'roles' => ['admin']],
                ['route' => 'admin/shopman/shopman-product/add', 'roles' => ['admin']],
                ['route' => 'admin/shopman/shopman-product/delete', 'roles' => ['admin']],
                ['route' => 'admin/seller', 'roles' => ['admin']],
                ['route' => 'admin/seller/add', 'roles' => ['admin']],
                ['route' => 'admin/seller/edit', 'roles' => ['admin']],
                ['route' => 'admin/seller/view', 'roles' => ['admin']],
                ['route' => 'admin/seller/delete', 'roles' => ['admin']],
                ['route' => 'admin/realtor', 'roles' => ['admin']],
                ['route' => 'admin/realtor/add', 'roles' => ['admin']],
                ['route' => 'admin/realtor/edit', 'roles' => ['admin']],
                ['route' => 'admin/realtor/view', 'roles' => ['admin']],
                ['route' => 'admin/realtor/delete', 'roles' => ['admin']],
                ['route' => 'admin/supplier', 'roles' => ['admin']],
                ['route' => 'admin/supplier/add', 'roles' => ['admin']],
                ['route' => 'admin/supplier/edit', 'roles' => ['admin']],
                ['route' => 'admin/supplier/view', 'roles' => ['admin']],
                ['route' => 'admin/supplier/delete', 'roles' => ['admin']],
                ['route' => 'admin/financial', 'roles' => ['admin']],
                ['route' => 'admin/financial/receivable', 'roles' => ['admin']],
                ['route' => 'admin/financial/receivable/add', 'roles' => ['user', 'admin']],
                ['route' => 'admin/financial/receivable/edit', 'roles' => ['admin']],
                ['route' => 'admin/financial/receivable/delete', 'roles' => ['admin']],
                ['route' => 'admin/financial/receivable/view', 'roles' => ['admin']],
                ['route' => 'admin/financial/payable/discharge', 'roles' => ['admin']],
                ['route' => 'admin/financial/payable', 'roles' => ['admin']],
                ['route' => 'admin/financial/payable/add', 'roles' => ['user', 'admin']],
                ['route' => 'admin/financial/payable/edit', 'roles' => ['admin']],
                ['route' => 'admin/financial/payable/delete', 'roles' => ['admin']],
                ['route' => 'admin/financial/payable/view', 'roles' => ['admin']],
                ['route' => 'admin/financial/payable/discharge', 'roles' => ['admin']],
                ['route' => 'admin/financial/revenue', 'roles' => ['admin']],
                ['route' => 'admin/financial/revenue/add', 'roles' => ['user', 'admin']],
                ['route' => 'admin/financial/revenue/edit', 'roles' => ['admin']],
                ['route' => 'admin/financial/revenue/delete', 'roles' => ['admin']],
                ['route' => 'admin/financial/revenue/view', 'roles' => ['admin']],
                ['route' => 'admin/financial/expense', 'roles' => ['admin']],
                ['route' => 'admin/financial/expense/add', 'roles' => ['user', 'admin']],
                ['route' => 'admin/financial/expense/edit', 'roles' => ['admin']],
                ['route' => 'admin/financial/expense/delete', 'roles' => ['admin']],
                ['route' => 'admin/financial/expense/view', 'roles' => ['admin']],
                ['route' => 'admin/financial/cash', 'roles' => ['admin']],
                ['route' => 'admin/company', 'roles' => ['admin']],
                ['route' => 'admin/company/add', 'roles' => ['admin']],
                ['route' => 'admin/company/edit', 'roles' => ['admin']],
                ['route' => 'admin/company/delete', 'roles' => ['admin']],
                ['route' => 'admin/company/view', 'roles' => ['admin']],
                ['route' => 'admin/category', 'roles' => ['admin']],
                ['route' => 'admin/category/add', 'roles' => ['admin']],
                ['route' => 'admin/category/edit', 'roles' => ['admin']],
                ['route' => 'admin/category/delete', 'roles' => ['admin']],
                ['route' => 'admin/category/view', 'roles' => ['admin']],
                ['route' => 'admin/product', 'roles' => ['admin']],
                ['route' => 'admin/product/add', 'roles' => ['admin']],
                ['route' => 'admin/product/edit', 'roles' => ['admin']],
                ['route' => 'admin/product/delete', 'roles' => ['admin']],
                ['route' => 'admin/product/view', 'roles' => ['admin']],
                ['route' => 'admin/product/list', 'roles' => ['admin']],
                ['route' => 'admin/business', 'roles' => ['admin']],
                ['route' => 'admin/business/add', 'roles' => ['admin']],
                ['route' => 'admin/business/edit', 'roles' => ['admin']],
                ['route' => 'admin/business/delete', 'roles' => ['admin']],
                ['route' => 'admin/business/view', 'roles' => ['admin']],
                ['route' => 'admin/bank', 'roles' => ['admin']],
                ['route' => 'admin/bank/add', 'roles' => ['admin']],
                ['route' => 'admin/bank/edit', 'roles' => ['admin']],
                ['route' => 'admin/bank/delete', 'roles' => ['admin']],
                ['route' => 'admin/bank/view', 'roles' => ['admin']],
                ['route' => 'admin/currency', 'roles' => ['admin']],
                ['route' => 'admin/currency/add', 'roles' => ['admin']],
                ['route' => 'admin/currency/edit', 'roles' => ['admin']],
                ['route' => 'admin/currency/delete', 'roles' => ['admin']],
                ['route' => 'admin/currency/view', 'roles' => ['admin']],
                ['route' => 'admin/current-account', 'roles' => ['admin']],
                ['route' => 'admin/current-account/add', 'roles' => ['admin']],
                ['route' => 'admin/current-account/edit', 'roles' => ['admin']],
                ['route' => 'admin/current-account/delete', 'roles' => ['admin']],
                ['route' => 'admin/current-account/view', 'roles' => ['admin']],
                ['route' => 'admin/payment-type', 'roles' => ['admin']],
                ['route' => 'admin/payment-type/add', 'roles' => ['admin']],
                ['route' => 'admin/payment-type/edit', 'roles' => ['admin']],
                ['route' => 'admin/payment-type/delete', 'roles' => ['admin']],
                ['route' => 'admin/payment-type/view', 'roles' => ['admin']],
                ['route' => 'admin/accounting-item', 'roles' => ['admin']],
                ['route' => 'admin/accounting-item/add', 'roles' => ['admin']],
                ['route' => 'admin/accounting-item/edit', 'roles' => ['admin']],
                ['route' => 'admin/accounting-item/delete', 'roles' => ['admin']],
                ['route' => 'admin/accounting-item/view', 'roles' => ['admin']],
                ['route' => 'admin/document-type', 'roles' => ['admin']],
                ['route' => 'admin/document-type/add', 'roles' => ['admin']],
                ['route' => 'admin/document-type/edit', 'roles' => ['admin']],
                ['route' => 'admin/document-type/delete', 'roles' => ['admin']],
                ['route' => 'admin/document-type/view', 'roles' => ['admin']],
                ['route' => 'admin/employee-status', 'roles' => ['admin']],
                ['route' => 'admin/employee-status/add', 'roles' => ['admin']],
                ['route' => 'admin/employee-status/edit', 'roles' => ['admin']],
                ['route' => 'admin/employee-status/delete', 'roles' => ['admin']],
                ['route' => 'admin/employee-status/view', 'roles' => ['admin']],
                ['route' => 'admin/occupation', 'roles' => ['admin']],
                ['route' => 'admin/occupation/add', 'roles' => ['admin']],
                ['route' => 'admin/occupation/edit', 'roles' => ['admin']],
                ['route' => 'admin/occupation/delete', 'roles' => ['admin']],
                ['route' => 'admin/occupation/view', 'roles' => ['admin']],
                ['route' => 'admin/occupation', 'roles' => ['admin']],
                ['route' => 'admin/occupation/add', 'roles' => ['admin']],
                ['route' => 'admin/occupation/edit', 'roles' => ['admin']],
                ['route' => 'admin/occupation/delete', 'roles' => ['admin']],
                ['route' => 'admin/occupation/view', 'roles' => ['admin']],
                ['route' => 'admin/office', 'roles' => ['admin']],
                ['route' => 'admin/office/add', 'roles' => ['admin']],
                ['route' => 'admin/office/edit', 'roles' => ['admin']],
                ['route' => 'admin/office/delete', 'roles' => ['admin']],
                ['route' => 'admin/office/view', 'roles' => ['admin']],
                ['route' => 'admin/department', 'roles' => ['admin']],
                ['route' => 'admin/department/add', 'roles' => ['admin']],
                ['route' => 'admin/department/edit', 'roles' => ['admin']],
                ['route' => 'admin/department/delete', 'roles' => ['admin']],
                ['route' => 'admin/department/view', 'roles' => ['admin']],
                ['route' => 'admin/vehicle', 'roles' => ['admin']],
                ['route' => 'admin/vehicle/vehicle-brand', 'roles' => ['admin']],
                ['route' => 'admin/vehicle/vehicle-brand/add', 'roles' => ['admin']],
                ['route' => 'admin/vehicle/vehicle-brand/edit', 'roles' => ['admin']],
                ['route' => 'admin/vehicle/vehicle-brand/view', 'roles' => ['admin']],
                ['route' => 'admin/vehicle/vehicle-brand/delete', 'roles' => ['admin']],
                ['route' => 'admin/vehicle/vehicle-brand/post', 'roles' => ['admin']],
                ['route' => 'admin/vehicle/vehicle-brand/list', 'roles' => ['admin']],
                ['route' => 'admin/vehicle/vehicle-type', 'roles' => ['admin']],
                ['route' => 'admin/vehicle/vehicle-type/add', 'roles' => ['admin']],
                ['route' => 'admin/vehicle/vehicle-type/edit', 'roles' => ['admin']],
                ['route' => 'admin/vehicle/vehicle-type/view', 'roles' => ['admin']],
                ['route' => 'admin/vehicle/vehicle-type/delete', 'roles' => ['admin']],
                ['route' => 'admin/vehicle/vehicle-type/post', 'roles' => ['admin']],
                ['route' => 'admin/vehicle/vehicle-type/list', 'roles' => ['admin']],
                ['route' => 'admin/vehicle/vehicle-type/fill', 'roles' => ['user', 'admin']],
                ['route' => 'admin/vehicle/vehicle-model', 'roles' => ['admin']],
                ['route' => 'admin/vehicle/vehicle-model/add', 'roles' => ['admin']],
                ['route' => 'admin/vehicle/vehicle-model/edit', 'roles' => ['admin']],
                ['route' => 'admin/vehicle/vehicle-model/view', 'roles' => ['admin']],
                ['route' => 'admin/vehicle/vehicle-model/delete', 'roles' => ['admin']],
                ['route' => 'admin/vehicle/vehicle-model/post', 'roles' => ['admin']],
                ['route' => 'admin/vehicle/vehicle-model/list', 'roles' => ['admin']],
                ['route' => 'admin/vehicle/vehicle-model/fill', 'roles' => ['user', 'admin']],
                ['route' => 'admin/vehicle/vehicle-version', 'roles' => ['admin']],
                ['route' => 'admin/vehicle/vehicle-version/add', 'roles' => ['admin']],
                ['route' => 'admin/vehicle/vehicle-version/edit', 'roles' => ['admin']],
                ['route' => 'admin/vehicle/vehicle-version/view', 'roles' => ['admin']],
                ['route' => 'admin/vehicle/vehicle-version/delete', 'roles' => ['admin']],
                ['route' => 'admin/vehicle/vehicle-version/post', 'roles' => ['admin']],
                ['route' => 'admin/vehicle/vehicle-version/list', 'roles' => ['admin']],
                ['route' => 'admin/vehicle/vehicle-version/fill', 'roles' => ['user', 'admin']],
                ['route' => 'admin/realty-type', 'roles' => ['admin']],
                ['route' => 'admin/realty-type/add', 'roles' => ['admin']],
                ['route' => 'admin/realty-type/edit', 'roles' => ['admin']],
                ['route' => 'admin/realty-type/delete', 'roles' => ['admin']],
                ['route' => 'admin/realty-type/view', 'roles' => ['admin']],
                ['route' => 'admin/realty-feature', 'roles' => ['user', 'admin']],
                ['route' => 'admin/realty-feature/calculatearea', 'roles' => ['user', 'admin']],
                ['route' => 'admin/realty-feature/calculateground', 'roles' => ['user', 'admin']],
                ['route' => 'admin/report', 'roles' => ['admin']],
                ['route' => 'admin/report/caixa', 'roles' => ['admin']],
                ['route' => 'admin/report/caixa/productsByDate', 'roles' => ['admin']],
                ['route' => 'fileupload', 'roles' => ['user', 'admin']],
                ['route' => 'fileupload/single', 'roles' => ['user', 'admin']],
                ['route' => 'fileupload/success', 'roles' => ['user', 'admin']],
                ['route' => 'fileupload/multi-html5', 'roles' => ['user', 'admin']],
                ['route' => 'fileupload/collection', 'roles' => ['user', 'admin']],
                ['route' => 'fileupload/partial', 'roles' => ['user', 'admin']],
                ['route' => 'fileupload/prg/multi-html5', 'roles' => ['user', 'admin']],
                ['route' => 'fileupload/prg/fieldset', 'roles' => ['user', 'admin']],
                ['route' => 'fileupload/progress/session', 'roles' => ['user', 'admin']],
                ['route' => 'fileupload/progress/session_partial', 'roles' => ['user', 'admin']],
                ['route' => 'admin/dtlfile', 'roles' => ['user', 'admin']],
                ['route' => 'admin/dtlfile/delete', 'roles' => ['user', 'admin']],
                ['route' => 'admin/pretender', 'roles' => ['user', 'admin']],
                ['route' => 'admin/pretender/add', 'roles' => ['user', 'admin']],
                ['route' => 'admin/pretender/edit', 'roles' => ['user', 'admin']],
                ['route' => 'admin/pretender/delete', 'roles' => ['user', 'admin']],
                ['route' => 'admin/pretender/view', 'roles' => ['user', 'admin']],
                ['route' => 'admin/dtllocation/country', 'roles' => ['user', 'admin']],
                ['route' => 'admin/dtllocation/country/add', 'roles' => ['user', 'admin']],
                ['route' => 'admin/dtllocation/country/edit', 'roles' => ['user', 'admin']],
                ['route' => 'admin/dtllocation/country/delete', 'roles' => ['user', 'admin']],
                ['route' => 'admin/dtllocation/state', 'roles' => ['user', 'admin']],
                ['route' => 'admin/dtllocation/state/add', 'roles' => ['user', 'admin']],
                ['route' => 'admin/dtllocation/state/edit', 'roles' => ['user', 'admin']],
                ['route' => 'admin/dtllocation/state/delete', 'roles' => ['user', 'admin']],
                ['route' => 'admin/dtllocation/city', 'roles' => ['user', 'admin']],
                ['route' => 'admin/dtllocation/city/add', 'roles' => ['user', 'admin']],
                ['route' => 'admin/dtllocation/city/edit', 'roles' => ['user', 'admin']],
                ['route' => 'admin/dtllocation/city/delete', 'roles' => ['user', 'admin']],
                ['route' => 'admin/dtllocation/city/fill', 'roles' => ['user', 'admin']],
            ],
        ],
    ],
];
